// DICOMDIRRecordKeyTables.swift
// DICOMKit
//
// GENERATED by Scripts/generate_dicomdir_record_keys.py from DICOM PS3.3 2026a Annex F and DICOM PS3.4
// 2026a Tables B.5-1 and GG.3-1. Do not hand-edit: fix the generator and regenerate.
//
// NEMA-verified: 2026a, checked 2026-10-01 — 34 Directory Record Types of PS3.3 2026a Table F.4-1 with their Type 1 / 1C / 2 / 2C keys from Tables F.5-1 to F.5-49 (145 keys, Include rows expanded); the record type of 174 SOP Classes of PS3.4 2026a Tables B.5-1 and GG.3-1 from the F.5 "shall be used to reference" sections and the IOD IEs; 5 SOP Classes have none; `generate_dicomdir_record_keys.py --check` re-verifies it.

import DICOMCore

extension DICOMDIRRecordKeys {
    /// Directory Record Type (0004,1430) Value per Media Storage SOP Class UID.
    static let recordTypeBySOPClass: [String: String] = [
        "1.2.840.10008.5.1.4.1.1.1": "IMAGE",  // Computed Radiography Image Storage
        "1.2.840.10008.5.1.4.1.1.1.1": "IMAGE",  // Digital X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.1.1": "IMAGE",  // Digital X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.1.2": "IMAGE",  // Digital Mammography X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.2.1": "IMAGE",  // Digital Mammography X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.1.3": "IMAGE",  // Digital Intra-Oral X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.3.1": "IMAGE",  // Digital Intra-Oral X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.2": "IMAGE",  // CT Image Storage
        "1.2.840.10008.5.1.4.1.1.2.1": "IMAGE",  // Enhanced CT Image Storage
        "1.2.840.10008.5.1.4.1.1.2.2": "IMAGE",  // Legacy Converted Enhanced CT Image Storage
        "1.2.840.10008.5.1.4.1.1.3.1": "IMAGE",  // Ultrasound Multi-frame Image Storage
        "1.2.840.10008.5.1.4.1.1.4": "IMAGE",  // MR Image Storage
        "1.2.840.10008.5.1.4.1.1.4.1": "IMAGE",  // Enhanced MR Image Storage
        "1.2.840.10008.5.1.4.1.1.4.2": "SPECTROSCOPY",  // MR Spectroscopy Storage
        "1.2.840.10008.5.1.4.1.1.4.3": "IMAGE",  // Enhanced MR Color Image Storage
        "1.2.840.10008.5.1.4.1.1.4.4": "IMAGE",  // Legacy Converted Enhanced MR Image Storage
        "1.2.840.10008.5.1.4.1.1.6.1": "IMAGE",  // Ultrasound Image Storage
        "1.2.840.10008.5.1.4.1.1.6.2": "IMAGE",  // Enhanced US Volume Storage
        "1.2.840.10008.5.1.4.1.1.6.3": "IMAGE",  // Photoacoustic Image Storage
        "1.2.840.10008.5.1.4.1.1.7": "IMAGE",  // Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.1": "IMAGE",  // Multi-frame Single Bit Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.2": "IMAGE",  // Multi-frame Grayscale Byte Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.3": "IMAGE",  // Multi-frame Grayscale Word Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.4": "IMAGE",  // Multi-frame True Color Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.9.1.1": "WAVEFORM",  // 12-lead ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.1.2": "WAVEFORM",  // General ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.1.3": "WAVEFORM",  // Ambulatory ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.1.4": "WAVEFORM",  // General 32-bit ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.2.1": "WAVEFORM",  // Hemodynamic Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.3.1": "WAVEFORM",  // Cardiac Electrophysiology Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.4.1": "WAVEFORM",  // Basic Voice Audio Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.4.2": "WAVEFORM",  // General Audio Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.5.1": "WAVEFORM",  // Arterial Pulse Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.6.1": "WAVEFORM",  // Respiratory Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.6.2": "WAVEFORM",  // Multi-channel Respiratory Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.1": "WAVEFORM",  // Routine Scalp Electroencephalogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.2": "WAVEFORM",  // Electromyogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.3": "WAVEFORM",  // Electrooculogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.4": "WAVEFORM",  // Sleep Electroencephalogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.8.1": "WAVEFORM",  // Body Position Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.100.1": "WF PRESENTATION",  // Waveform Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.9.100.2": "WF PRESENTATION",  // Waveform Acquisition Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.1": "PRESENTATION",  // Grayscale Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.2": "PRESENTATION",  // Color Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.3": "PRESENTATION",  // Pseudo-Color Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.4": "PRESENTATION",  // Blending Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.5": "PRESENTATION",  // XA/XRF Grayscale Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.6": "PRESENTATION",  // Grayscale Planar MPR Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.7": "PRESENTATION",  // Compositing Planar MPR Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.8": "PRESENTATION",  // Advanced Blending Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.9": "PRESENTATION",  // Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.10": "PRESENTATION",  // Segmented Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.11": "PRESENTATION",  // Multiple Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.12": "PRESENTATION",  // Variable Modality LUT Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.12.1": "IMAGE",  // X-Ray Angiographic Image Storage
        "1.2.840.10008.5.1.4.1.1.12.1.1": "IMAGE",  // Enhanced XA Image Storage
        "1.2.840.10008.5.1.4.1.1.12.2": "IMAGE",  // X-Ray Radiofluoroscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.12.2.1": "IMAGE",  // Enhanced XRF Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.1": "IMAGE",  // X-Ray 3D Angiographic Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.2": "IMAGE",  // X-Ray 3D Craniofacial Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.3": "IMAGE",  // Breast Tomosynthesis Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.4": "IMAGE",  // Breast Projection X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.13.1.5": "IMAGE",  // Breast Projection X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.14.1": "IMAGE",  // Intravascular Optical Coherence Tomography Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.14.2": "IMAGE",  // Intravascular Optical Coherence Tomography Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.20": "IMAGE",  // Nuclear Medicine Image Storage
        "1.2.840.10008.5.1.4.1.1.30": "IMAGE",  // Parametric Map Storage
        "1.2.840.10008.5.1.4.1.1.66": "RAW DATA",  // Raw Data Storage
        "1.2.840.10008.5.1.4.1.1.66.1": "REGISTRATION",  // Spatial Registration Storage
        "1.2.840.10008.5.1.4.1.1.66.2": "FIDUCIAL",  // Spatial Fiducials Storage
        "1.2.840.10008.5.1.4.1.1.66.3": "REGISTRATION",  // Deformable Spatial Registration Storage
        "1.2.840.10008.5.1.4.1.1.66.4": "IMAGE",  // Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.66.5": "SURFACE",  // Surface Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.66.6": "TRACT",  // Tractography Results Storage
        "1.2.840.10008.5.1.4.1.1.66.7": "IMAGE",  // Label Map Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.66.8": "IMAGE",  // Height Map Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.67": "VALUE MAP",  // Real World Value Mapping Storage
        "1.2.840.10008.5.1.4.1.1.68.1": "SURFACE SCAN",  // Surface Scan Mesh Storage
        "1.2.840.10008.5.1.4.1.1.68.2": "SURFACE SCAN",  // Surface Scan Point Cloud Storage
        "1.2.840.10008.5.1.4.1.1.77.1.1": "IMAGE",  // VL Endoscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.1.1": "IMAGE",  // Video Endoscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.2": "IMAGE",  // VL Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.2.1": "IMAGE",  // Video Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.3": "IMAGE",  // VL Slide-Coordinates Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.4": "IMAGE",  // VL Photographic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.4.1": "IMAGE",  // Video Photographic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.1": "IMAGE",  // Ophthalmic Photography 8 Bit Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.2": "IMAGE",  // Ophthalmic Photography 16 Bit Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.3": "STEREOMETRIC",  // Stereometric Relationship Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.4": "IMAGE",  // Ophthalmic Tomography Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.5": "IMAGE",  // Wide Field Ophthalmic Photography Stereographic Projection Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.6": "IMAGE",  // Wide Field Ophthalmic Photography 3D Coordinates Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.7": "IMAGE",  // Ophthalmic Optical Coherence Tomography En Face Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.8": "IMAGE",  // Ophthalmic Optical Coherence Tomography B-scan Volume Analysis Storage
        "1.2.840.10008.5.1.4.1.1.77.1.6": "IMAGE",  // VL Whole Slide Microscopy Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.7": "IMAGE",  // Dermoscopic Photography Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.8": "IMAGE",  // Confocal Microscopy Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.9": "IMAGE",  // Confocal Microscopy Tiled Pyramidal Image Storage
        "1.2.840.10008.5.1.4.1.1.78.1": "MEASUREMENT",  // Lensometry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.2": "MEASUREMENT",  // Autorefraction Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.3": "MEASUREMENT",  // Keratometry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.4": "MEASUREMENT",  // Subjective Refraction Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.5": "MEASUREMENT",  // Visual Acuity Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.6": "SR DOCUMENT",  // Spectacle Prescription Report Storage
        "1.2.840.10008.5.1.4.1.1.78.7": "MEASUREMENT",  // Ophthalmic Axial Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.8": "MEASUREMENT",  // Intraocular Lens Calculations Storage
        "1.2.840.10008.5.1.4.1.1.79.1": "SR DOCUMENT",  // Macular Grid Thickness and Volume Report
        "1.2.840.10008.5.1.4.1.1.80.1": "MEASUREMENT",  // Ophthalmic Visual Field Static Perimetry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.81.1": "IMAGE",  // Ophthalmic Thickness Map Storage
        "1.2.840.10008.5.1.4.1.1.82.1": "IMAGE",  // Corneal Topography Map Storage
        "1.2.840.10008.5.1.4.1.1.88.11": "SR DOCUMENT",  // Basic Text SR Storage
        "1.2.840.10008.5.1.4.1.1.88.22": "SR DOCUMENT",  // Enhanced SR Storage
        "1.2.840.10008.5.1.4.1.1.88.33": "SR DOCUMENT",  // Comprehensive SR Storage
        "1.2.840.10008.5.1.4.1.1.88.34": "SR DOCUMENT",  // Comprehensive 3D SR Storage
        "1.2.840.10008.5.1.4.1.1.88.35": "SR DOCUMENT",  // Extensible SR Storage
        "1.2.840.10008.5.1.4.1.1.88.40": "SR DOCUMENT",  // Procedure Log Storage
        "1.2.840.10008.5.1.4.1.1.88.50": "SR DOCUMENT",  // Mammography CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.59": "KEY OBJECT DOC",  // Key Object Selection Document Storage
        "1.2.840.10008.5.1.4.1.1.88.65": "SR DOCUMENT",  // Chest CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.67": "SR DOCUMENT",  // X-Ray Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.68": "SR DOCUMENT",  // Radiopharmaceutical Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.69": "SR DOCUMENT",  // Colon CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.70": "SR DOCUMENT",  // Implantation Plan SR Storage
        "1.2.840.10008.5.1.4.1.1.88.71": "SR DOCUMENT",  // Acquisition Context SR Storage
        "1.2.840.10008.5.1.4.1.1.88.72": "SR DOCUMENT",  // Simplified Adult Echo SR Storage
        "1.2.840.10008.5.1.4.1.1.88.73": "SR DOCUMENT",  // Patient Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.74": "SR DOCUMENT",  // Planned Imaging Agent Administration SR Storage
        "1.2.840.10008.5.1.4.1.1.88.75": "SR DOCUMENT",  // Performed Imaging Agent Administration SR Storage
        "1.2.840.10008.5.1.4.1.1.88.76": "SR DOCUMENT",  // Enhanced X-Ray Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.77": "SR DOCUMENT",  // Waveform Annotation SR Storage
        "1.2.840.10008.5.1.4.1.1.90.1": "ASSESSMENT",  // Content Assessment Results Storage
        "1.2.840.10008.5.1.4.1.1.91.1": "ANNOTATION",  // Microscopy Bulk Simple Annotations Storage
        "1.2.840.10008.5.1.4.1.1.104.1": "ENCAP DOC",  // Encapsulated PDF Storage
        "1.2.840.10008.5.1.4.1.1.104.2": "ENCAP DOC",  // Encapsulated CDA Storage
        "1.2.840.10008.5.1.4.1.1.104.3": "ENCAP DOC",  // Encapsulated STL Storage
        "1.2.840.10008.5.1.4.1.1.104.4": "ENCAP DOC",  // Encapsulated OBJ Storage
        "1.2.840.10008.5.1.4.1.1.104.5": "ENCAP DOC",  // Encapsulated MTL Storage
        "1.2.840.10008.5.1.4.1.1.128": "IMAGE",  // Positron Emission Tomography Image Storage
        "1.2.840.10008.5.1.4.1.1.130": "IMAGE",  // Enhanced PET Image Storage
        "1.2.840.10008.5.1.4.1.1.128.1": "IMAGE",  // Legacy Converted Enhanced PET Image Storage
        "1.2.840.10008.5.1.4.1.1.131": "PRESENTATION",  // Basic Structured Display Storage
        "1.2.840.10008.5.1.4.1.1.481.1": "IMAGE",  // RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.2": "RT DOSE",  // RT Dose Storage
        "1.2.840.10008.5.1.4.1.1.481.3": "RT STRUCTURE SET",  // RT Structure Set Storage
        "1.2.840.10008.5.1.4.1.1.481.4": "RT TREAT RECORD",  // RT Beams Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.5": "RT PLAN",  // RT Plan Storage
        "1.2.840.10008.5.1.4.1.1.481.6": "RT TREAT RECORD",  // RT Brachy Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.7": "RT TREAT RECORD",  // RT Treatment Summary Record Storage
        "1.2.840.10008.5.1.4.1.1.481.8": "RT PLAN",  // RT Ion Plan Storage
        "1.2.840.10008.5.1.4.1.1.481.9": "RT TREAT RECORD",  // RT Ion Beams Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.10": "RADIOTHERAPY",  // RT Physician Intent Storage
        "1.2.840.10008.5.1.4.1.1.481.11": "RADIOTHERAPY",  // RT Segment Annotation Storage
        "1.2.840.10008.5.1.4.1.1.481.12": "RADIOTHERAPY",  // RT Radiation Set Storage
        "1.2.840.10008.5.1.4.1.1.481.13": "RADIOTHERAPY",  // C-Arm Photon-Electron Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.14": "RADIOTHERAPY",  // Tomotherapeutic Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.15": "RADIOTHERAPY",  // Robotic-Arm Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.16": "RADIOTHERAPY",  // RT Radiation Record Set Storage
        "1.2.840.10008.5.1.4.1.1.481.17": "RADIOTHERAPY",  // RT Radiation Salvage Record Storage
        "1.2.840.10008.5.1.4.1.1.481.18": "RADIOTHERAPY",  // Tomotherapeutic Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.19": "RADIOTHERAPY",  // C-Arm Photon-Electron Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.20": "RADIOTHERAPY",  // Robotic Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.21": "RADIOTHERAPY",  // RT Radiation Set Delivery Instruction Storage
        "1.2.840.10008.5.1.4.1.1.481.22": "RADIOTHERAPY",  // RT Treatment Preparation Storage
        "1.2.840.10008.5.1.4.1.1.481.23": "RADIOTHERAPY",  // Enhanced RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.24": "RADIOTHERAPY",  // Enhanced Continuous RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.25": "RADIOTHERAPY",  // RT Patient Position Acquisition Instruction Storage
        "1.2.840.10008.5.1.4.34.7": "PLAN",  // RT Beams Delivery Instruction Storage
        "1.2.840.10008.5.1.4.34.10": "PLAN",  // RT Brachy Application Setup Delivery Instruction Storage
        "1.2.840.10008.5.1.4.38.1": "HANGING PROTOCOL",  // Hanging Protocol Storage
        "1.2.840.10008.5.1.4.39.1": "PALETTE",  // Color Palette Storage
        "1.2.840.10008.5.1.4.43.1": "IMPLANT",  // Generic Implant Template Storage
        "1.2.840.10008.5.1.4.44.1": "IMPLANT ASSY",  // Implant Assembly Template Storage
        "1.2.840.10008.5.1.4.45.1": "IMPLANT GROUP",  // Implant Template Group Storage
        "1.2.840.10008.5.1.4.1.1.201.1": "INVENTORY",  // Inventory Storage
    ]

    /// SOP Classes of PS3.4 Tables B.5-1 / GG.3-1 for which PS3.3 2026a defines no Directory Record Type.
    static let sopClassesWithoutRecordType: [String: String] = [
        "1.2.840.10008.5.1.4.1.1.200.2": "CT Performed Procedure Protocol Storage",
        "1.2.840.10008.5.1.4.1.1.200.8": "XA Performed Procedure Protocol Storage",
        "1.2.840.10008.5.1.4.1.1.200.1": "CT Defined Procedure Protocol Storage",
        "1.2.840.10008.5.1.4.1.1.200.3": "Protocol Approval Storage",
        "1.2.840.10008.5.1.4.1.1.200.7": "XA Defined Procedure Protocol Storage",
    ]

    /// Type 1 / 1C / 2 / 2C keys per Directory Record Type, in table order.
    static let keyTable: [String: (table: String, keys: [Key])] = [
        "PATIENT": (table: "F.5-1", keys: [
            Key(tag: Tag(group: 0x0010, element: 0x0010), name: "Patient's Name", type: "2"),
            Key(tag: Tag(group: 0x0010, element: 0x0020), name: "Patient ID", type: "1"),
        ]),
        "STUDY": (table: "F.5-2", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0020), name: "Study Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0030), name: "Study Time", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x1030), name: "Study Description", type: "2"),
            Key(tag: Tag(group: 0x0020, element: 0x000D), name: "Study Instance UID", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0010), name: "Study ID", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0050), name: "Accession Number", type: "2"),
        ]),
        "SERIES": (table: "F.5-3", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0060), name: "Modality", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x000E), name: "Series Instance UID", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0011), name: "Series Number", type: "1"),
        ]),
        "IMAGE": (table: "F.5-4", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
        ]),
        "RT DOSE": (table: "F.5-19", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x3004, element: 0x000A), name: "Dose Summation Type", type: "1"),
        ]),
        "RT STRUCTURE SET": (table: "F.5-20", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x3006, element: 0x0002), name: "Structure Set Label", type: "1"),
            Key(tag: Tag(group: 0x3006, element: 0x0008), name: "Structure Set Date", type: "2"),
            Key(tag: Tag(group: 0x3006, element: 0x0009), name: "Structure Set Time", type: "2"),
        ]),
        "RT PLAN": (table: "F.5-21", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x300A, element: 0x0002), name: "RT Plan Label", type: "1"),
            Key(tag: Tag(group: 0x300A, element: 0x0006), name: "RT Plan Date", type: "2"),
            Key(tag: Tag(group: 0x300A, element: 0x0007), name: "RT Plan Time", type: "2"),
        ]),
        "RT TREAT RECORD": (table: "F.5-22", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x3008, element: 0x0250), name: "Treatment Date", type: "2"),
            Key(tag: Tag(group: 0x3008, element: 0x0251), name: "Treatment Time", type: "2"),
        ]),
        "PRESENTATION": (table: "F.5-23", keys: [
            Key(tag: Tag(group: 0x0070, element: 0x0082), name: "Presentation Creation Date", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0083), name: "Presentation Creation Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
            Key(tag: Tag(group: 0x0008, element: 0x1115), name: "Referenced Series Sequence", type: "1C"),
            Key(tag: Tag(group: 0x0070, element: 0x0402), name: "Blending Sequence", type: "1C"),
        ]),
        "WAVEFORM": (table: "F.5-24", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
        ]),
        "SR DOCUMENT": (table: "F.5-25", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA491), name: "Completion Flag", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA493), name: "Verification Flag", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA030), name: "Verification DateTime", type: "1C"),
            Key(tag: Tag(group: 0x0040, element: 0xA043), name: "Concept Name Code Sequence", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA730), name: "Content Sequence", type: "1C"),
        ]),
        "KEY OBJECT DOC": (table: "F.5-26", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA043), name: "Concept Name Code Sequence", type: "1"),
            Key(tag: Tag(group: 0x0040, element: 0xA730), name: "Content Sequence", type: "1C"),
        ]),
        "SPECTROSCOPY": (table: "F.5-27", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0008), name: "Image Type", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x9092), name: "Referenced Image Evidence Sequence", type: "1C"),
            Key(tag: Tag(group: 0x0028, element: 0x0008), name: "Number of Frames", type: "1"),
            Key(tag: Tag(group: 0x0028, element: 0x0010), name: "Rows", type: "1"),
            Key(tag: Tag(group: 0x0028, element: 0x0011), name: "Columns", type: "1"),
            Key(tag: Tag(group: 0x0028, element: 0x9001), name: "Data Point Rows", type: "1"),
            Key(tag: Tag(group: 0x0028, element: 0x9002), name: "Data Point Columns", type: "1"),
        ]),
        "RAW DATA": (table: "F.5-28", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "2"),
        ]),
        "REGISTRATION": (table: "F.5-29", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "FIDUCIAL": (table: "F.5-30", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "HANGING PROTOCOL": (table: "F.5-31", keys: [
            Key(tag: Tag(group: 0x0072, element: 0x0002), name: "Hanging Protocol Name", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x0004), name: "Hanging Protocol Description", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x0006), name: "Hanging Protocol Level", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x0008), name: "Hanging Protocol Creator", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x000A), name: "Hanging Protocol Creation DateTime", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x000C), name: "Hanging Protocol Definition Sequence", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x0014), name: "Number of Priors Referenced", type: "1"),
            Key(tag: Tag(group: 0x0072, element: 0x000E), name: "Hanging Protocol User Identification Code Sequence", type: "2"),
        ]),
        "ENCAP DOC": (table: "F.5-32", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "2"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "2"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0042, element: 0x0010), name: "Document Title", type: "2"),
            Key(tag: Tag(group: 0x0040, element: 0xE001), name: "HL7 Instance Identifier", type: "1C"),
            Key(tag: Tag(group: 0x0040, element: 0xA043), name: "Concept Name Code Sequence", type: "2"),
            Key(tag: Tag(group: 0x0042, element: 0x0012), name: "MIME Type of Encapsulated Document", type: "1"),
        ]),
        "VALUE MAP": (table: "F.5-34", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "STEREOMETRIC": (table: "F.5-35", keys: [
        ]),
        "PALETTE": (table: "F.5-36", keys: [
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "IMPLANT": (table: "F.5-37", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0070), name: "Manufacturer", type: "1"),
            Key(tag: Tag(group: 0x0022, element: 0x1095), name: "Implant Name", type: "1"),
            Key(tag: Tag(group: 0x0068, element: 0x6210), name: "Implant Size", type: "1C"),
            Key(tag: Tag(group: 0x0022, element: 0x1097), name: "Implant Part Number", type: "1"),
        ]),
        "IMPLANT ASSY": (table: "F.5-38", keys: [
            Key(tag: Tag(group: 0x0076, element: 0x0001), name: "Implant Assembly Template Name", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0070), name: "Manufacturer", type: "1"),
            Key(tag: Tag(group: 0x0076, element: 0x0020), name: "Procedure Type Code Sequence", type: "1"),
        ]),
        "IMPLANT GROUP": (table: "F.5-39", keys: [
            Key(tag: Tag(group: 0x0078, element: 0x0001), name: "Implant Template Group Name", type: "1"),
            Key(tag: Tag(group: 0x0078, element: 0x0020), name: "Implant Template Group Issuer", type: "1"),
        ]),
        "PLAN": (table: "F.5-40", keys: [
        ]),
        "MEASUREMENT": (table: "F.5-41", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "SURFACE": (table: "F.5-42", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "SURFACE SCAN": (table: "F.5-43", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
        ]),
        "TRACT": (table: "F.5-44", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "ASSESSMENT": (table: "F.5-45", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0012), name: "Instance Creation Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0013), name: "Instance Creation Time", type: "2"),
        ]),
        "RADIOTHERAPY": (table: "F.5-46", keys: [
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x3010, element: 0x0033), name: "User Content Label", type: "1C"),
            Key(tag: Tag(group: 0x3010, element: 0x0034), name: "User Content Long Label", type: "1C"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
            Key(tag: Tag(group: 0x0070, element: 0x0084), name: "Content Creator's Name", type: "2"),
        ]),
        "ANNOTATION": (table: "F.5-47", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
        ]),
        "INVENTORY": (table: "F.5-48", keys: [
            Key(tag: Tag(group: 0x0008, element: 0x0023), name: "Content Date", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0033), name: "Content Time", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0401), name: "Inventory Purpose", type: "2"),
            Key(tag: Tag(group: 0x0008, element: 0x0403), name: "Inventory Level", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0400), name: "Scope of Inventory Sequence", type: "2"),
            Key(tag: Tag(group: 0x0008, element: 0x0426), name: "Inventory Completion Status", type: "1"),
            Key(tag: Tag(group: 0x0008, element: 0x0428), name: "Total Number of Study Records", type: "1"),
        ]),
        "WF PRESENTATION": (table: "F.5-49", keys: [
            Key(tag: Tag(group: 0x0070, element: 0x0082), name: "Presentation Creation Date", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0083), name: "Presentation Creation Time", type: "1"),
            Key(tag: Tag(group: 0x0020, element: 0x0013), name: "Instance Number", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0080), name: "Content Label", type: "1"),
            Key(tag: Tag(group: 0x0070, element: 0x0081), name: "Content Description", type: "2"),
            Key(tag: Tag(group: 0x0008, element: 0x1115), name: "Referenced Series Sequence", type: "1C"),
        ]),
    ]
}
