// NEMA-verified: 2026a, checked 2026-10-01 — the "Additional DICOMDIR Keys" of PS3.11 2026a Tables A.3-2 (9 top-level rows), B.3-2 (10), D.3-2 (2), E.3-2 (7), H.3-2 (19), I.3-2 (9), each applied to the profiles of the Annex whose X.3.3 section names it (J, M, N use H.3-2), 1C conditions as the Notes column states; Icon Image Sequence (0088,0200) per A.3.3.2 / B.3.3.2 (Type 1, 128 x 128, 8 bits, MONOCHROME2) and E.3.3.3 (may, 64 x 64) within PS3.3 2026a F.7 / C.7.6.1.1.6 (Samples per Pixel 1, MONOCHROME1 / MONOCHROME2 / PALETTE COLOR, Bits Allocated = Bits Stored 1 or 8, High Bit = Bits Stored - 1, Pixel Representation 0, no Planar Configuration, square pixels); tables generated by Scripts/generate_dicomdir_profile_rules.py (D239)
import Foundation
import DICOMCore

extension DICOMDIRProfileRules {

    /// A row of a PS3.11 "Additional DICOMDIR Keys" table (generated: DICOMDIRProfileTables.swift).
    struct AdditionalKey: Sendable {
        let name: String
        let tag: Tag
        /// Directory Record Type column ("IMAGE or SPECTROSCOPY" split).
        let recordTypes: [String]
        /// "1", "1C", "2".
        let type: String
        /// The 1C condition the Notes state, classified by the generator: "present",
        /// "presentNonZero", "presentInSubordinates", "presentOrSharedFunctionalGroups",
        /// "xaImage", "biplane", "xaBiplane"; "" for Type 1 / 2.
        let condition: String
        /// Notes column, verbatim.
        let notes: String
    }

    /// A PS3.11 "Icon Images" section (A.3.3.2, B.3.3.2, E.3.3.3).
    struct IconImageRule: Sendable {
        let section: String
        /// Directory Record Types that carry the icon.
        let recordTypes: [String]
        /// "shall include" (true) or "may include" (false).
        let required: Bool
        let rows: Int
        let columns: Int
        /// Bits Allocated (and Bits Stored).
        let bits: Int
        /// Permitted Photometric Interpretations; empty: PS3.3 F.7 alone.
        let photometricInterpretations: [String]
    }

    /// PS3.3 2026a F.7: "Photometric Interpretation (0028,0004) shall have a Value of either
    /// MONOCHROME 1, MONOCHROME 2 or PALETTE COLOR".
    static let iconPhotometricInterpretations = ["MONOCHROME1", "MONOCHROME2", "PALETTE COLOR"]

    /// The PS3.11 2026a Annex that defines `profile` (the letter of its SOP Class table).
    static func annex(of profile: DICOMDIRProfile) -> String? {
        tableLabel(for: profile).map { String($0.prefix(1)) }
    }

    /// The PS3.11 2026a "Additional DICOMDIR Keys" table `profile` applies, or nil when its
    /// Annex specifies none (C, G, K, L) or the profile is not a PS3.11 one.
    public static func additionalKeyTableLabel(for profile: DICOMDIRProfile) -> String? {
        annex(of: profile).flatMap { additionalKeyTableByAnnex[$0] }
    }

    /// The additional key elements of a `recordType` record for the instance `file`, under
    /// `profile`: Type 1 keys copied (Icon Image Sequence copied when the instance's own icon meets
    /// the profile, else generated from the instance's pixels), Type 2 keys copied or zero length,
    /// Type 1C keys when their Notes condition holds. Throws ``Refusal/missingProfileKey(profile:recordType:key:tag:table:reason:)``
    /// when a required key cannot be supplied.
    static func additionalKeyElements(for recordType: DirectoryRecordType, profile: DICOMDIRProfile,
                                      file: DICOMFile, sopClassUID: String) throws -> [Tag: DataElement] {
        guard let annex = annex(of: profile) else { return [:] }
        let dataSet = file.dataSet
        var out: [Tag: DataElement] = [:]
        let iconRule = iconImageRules[annex].flatMap { $0.recordTypes.contains(recordType.rawValue) ? $0 : nil }

        if let label = additionalKeyTableByAnnex[annex] {
            func refuse(_ key: AdditionalKey, _ reason: String) -> Refusal {
                .missingProfileKey(profile: profile.rawValue, recordType: recordType.rawValue, key: key.name,
                                   tag: key.tag.description, table: label, reason: reason)
            }
            for key in additionalKeyTables[label] ?? [] where key.recordTypes.contains(recordType.rawValue) {
                let present = DICOMDIRRecordKeys.present(key.tag, in: dataSet)
                if key.tag == .iconImageSequence {
                    let rule = iconRule ?? IconImageRule(section: "PS3.3 F.7", recordTypes: key.recordTypes, required: true,
                                                         rows: 64, columns: 64, bits: 8, photometricInterpretations: [])
                    do {
                        out[key.tag] = try iconImageSequence(for: file, rule: rule)
                    } catch let error as IconError {
                        throw refuse(key, "\(error.reason) [PS3.11 2026a \(rule.section); PS3.3 2026a F.7]")
                    }
                    continue
                }
                switch key.type {
                case "1":
                    guard let present else { throw refuse(key, "absent or empty in the instance") }
                    out[key.tag] = present
                case "2":
                    out[key.tag] = dataSet[key.tag] ?? DICOMDIRRecordKeys.emptyElement(key.tag)
                default:
                    switch key.condition {
                    case "presentOrSharedFunctionalGroups":
                        if let element = present ?? sharedFunctionalGroupsElement(key.tag, in: dataSet) {
                            out[key.tag] = element
                        }
                    case "xaImage":
                        if sopClassUID == xaImageStorage {
                            guard let present else { throw refuse(key, "absent in an XA Image instance (\(key.notes))") }
                            out[key.tag] = present
                        }
                    case "biplane", "xaBiplane":
                        let values = (dataSet.strings(for: .imageType) ?? []).map { $0.trimmingCharacters(in: .whitespaces) }
                        let biplane = key.condition == "biplane"
                            ? values.contains { $0 == "BIPLANE A" || $0 == "BIPLANE B" }
                            : sopClassUID == xaImageStorage && values.count >= 3 && ["BIPLANE A", "BIPLANE B"].contains(values[2])
                        if biplane, present == nil { throw refuse(key, "absent in a BIPLANE A / B instance (\(key.notes))") }
                        if let present { out[key.tag] = present }   // "May be present otherwise"
                    default:  // present, presentNonZero, presentInSubordinates
                        if let present { out[key.tag] = present }
                    }
                }
            }
        }
        // E.3.3.3: SERIES / IMAGE records "may include" icons; the instance's own icon is copied when
        // it meets the restrictions, none is generated.
        if let rule = iconRule, !rule.required, out[.iconImageSequence] == nil,
           let element = dataSet[.iconImageSequence], let item = element.sequenceItems?.first,
           element.sequenceItems?.count == 1, iconProblems(item, rule: rule).isEmpty {
            out[.iconImageSequence] = element
        }
        return out
    }

    private static let xaImageStorage = "1.2.840.10008.5.1.4.1.1.12.1"

    /// An element of a functional group Sequence of the Shared Functional Groups Sequence
    /// (5200,9229), e.g. Pixel Spacing in the Pixel Measures Sequence.
    private static func sharedFunctionalGroupsElement(_ tag: Tag, in dataSet: DataSet) -> DataElement? {
        guard let shared = dataSet.sequence(for: .sharedFunctionalGroupsSequence)?.first else { return nil }
        for groupTag in shared.elements.keys.sorted(by: { ($0.group, $0.element) < ($1.group, $1.element) }) {
            guard let items = shared[groupTag]?.sequenceItems else { continue }
            for item in items {
                if let element = item[tag], element.length > 0 || element.vr == .SQ && !(element.sequenceItems ?? []).isEmpty {
                    return element
                }
            }
        }
        return nil
    }

    // MARK: - Icon Image Sequence (PS3.3 F.7)

    struct IconError: Error { let reason: String }

    /// What keeps an Icon Image Sequence Item from meeting `rule` and PS3.3 2026a F.7.
    static func iconProblems(_ item: SequenceItem, rule: IconImageRule) -> [String] {
        func us(_ tag: Tag) -> Int? { item[tag]?.uint16Value.map(Int.init) }
        var problems: [String] = []
        let pi = item.string(for: .photometricInterpretation)?.trimmingCharacters(in: .whitespaces) ?? ""
        let allowed = rule.photometricInterpretations.isEmpty ? iconPhotometricInterpretations : rule.photometricInterpretations
        if us(.samplesPerPixel) != 1 { problems.append("Samples per Pixel is not 1") }
        if !allowed.contains(pi) { problems.append("Photometric Interpretation \(pi) is not \(allowed.joined(separator: " / "))") }
        if us(.rows) != rule.rows || us(.columns) != rule.columns {
            problems.append("Rows / Columns are not \(rule.rows) / \(rule.columns)")
        }
        if us(.bitsAllocated) != rule.bits || us(.bitsStored) != rule.bits { problems.append("Bits Allocated / Stored are not \(rule.bits)") }
        if let stored = us(.bitsStored), us(.highBit) != stored - 1 { problems.append("High Bit is not Bits Stored - 1") }
        if us(.pixelRepresentation) != 0 { problems.append("Pixel Representation is not 0000H") }
        if item[.planarConfiguration] != nil { problems.append("Planar Configuration is present") }
        if let ratio = item.strings(for: .pixelAspectRatio), ratio.count == 2, ratio[0].trimmingCharacters(in: .whitespaces) != ratio[1].trimmingCharacters(in: .whitespaces) {
            problems.append("pixels are not square")
        }
        let needed = rule.rows * rule.columns * max(rule.bits, 8) / 8
        if (item[.pixelData]?.valueData.count ?? 0) < needed { problems.append("Pixel Data is shorter than \(needed) bytes") }
        return problems
    }

    /// The Icon Image Sequence for `file`: its own icon when it meets `rule`, else one Item made
    /// from its pixels (MONOCHROME2, 8 bits, `rule.rows` x `rule.columns`). For a Multi-frame
    /// Image the frame is Representative Frame Number (0028,6010), else the one about a third of
    /// the way through (A.3.3.2 / B.3.3.2 Notes).
    static func iconImageSequence(for file: DICOMFile, rule: IconImageRule) throws -> DataElement {
        if let element = file.dataSet[.iconImageSequence], element.sequenceItems?.count == 1,
           let item = element.sequenceItems?.first, iconProblems(item, rule: rule).isEmpty {
            return element
        }
        let pixels = try iconPixels(from: file, rows: rule.rows, columns: rule.columns)
        var icon = DataSet()
        icon.setUInt16(1, for: .samplesPerPixel)
        icon.setString("MONOCHROME2", for: .photometricInterpretation, vr: .CS)
        icon.setUInt16(UInt16(rule.rows), for: .rows)
        icon.setUInt16(UInt16(rule.columns), for: .columns)
        icon.setUInt16(8, for: .bitsAllocated)
        icon.setUInt16(8, for: .bitsStored)
        icon.setUInt16(7, for: .highBit)
        icon.setUInt16(0, for: .pixelRepresentation)
        // B.3.3.2 Note: "It is recommended that the Icon Images be encoding using VR OB encoding."
        icon[.pixelData] = DataElement.data(tag: .pixelData, vr: .OB, data: Data(pixels))
        var holder = DataSet()
        holder.setSequence([SequenceItem(elements: icon.allElements)], for: .iconImageSequence)
        guard let element = holder[.iconImageSequence] else { throw IconError(reason: "icon could not be encoded") }
        return element
    }

    /// 8-bit MONOCHROME2 samples, `rows` x `columns`, of the instance's representative frame:
    /// windowed by its first Window Center / Width (after Rescale Slope / Intercept) or its
    /// range, MONOCHROME1 inverted, colour as luminance, fitted with its aspect ratio kept and
    /// padded with black.
    static func iconPixels(from file: DICOMFile, rows: Int, columns: Int) throws -> [UInt8] {
        let dataSet = file.dataSet
        guard dataSet[.pixelData] != nil else { throw IconError(reason: "the instance has no Pixel Data to make an icon from") }
        let descriptor: PixelDataDescriptor
        do { descriptor = try dataSet.tryPixelDataDescriptor() } catch {
            throw IconError(reason: "the instance's Image Pixel Module cannot be read (\(error))")
        }
        let frames = max(1, descriptor.numberOfFrames)
        var frame = frames > 1 ? frames / 3 : 0
        if let representative = dataSet.uint16(for: Tag(group: 0x0028, element: 0x6010)).map(Int.init),
           representative >= 1, representative <= frames {
            frame = representative - 1
        }
        let pixelData: PixelData
        do { pixelData = try file.pixelData(frame: frame) } catch {
            throw IconError(reason: "frame \(frame + 1) of the instance cannot be decoded (\(error))")
        }
        let srcRows = descriptor.rows, srcColumns = descriptor.columns
        guard srcRows > 0, srcColumns > 0 else { throw IconError(reason: "the instance has no Rows / Columns") }

        // Luminance 0...1 per source pixel
        var luminance = [Double](repeating: 0, count: srcRows * srcColumns)
        let pi = dataSet.string(for: .photometricInterpretation)?.trimmingCharacters(in: .whitespaces) ?? ""
        if descriptor.samplesPerPixel == 1, pi == "PALETTE COLOR" {
            guard let lut = dataSet.paletteColorLUT(), let values = pixelData.pixelValues(forFrame: 0) else {
                throw IconError(reason: "the PALETTE COLOR lookup table cannot be read")
            }
            for (i, v) in values.prefix(luminance.count).enumerated() {
                let c = lut.lookup(v)
                luminance[i] = (0.299 * Double(c.red) + 0.587 * Double(c.green) + 0.114 * Double(c.blue)) / 255
            }
        } else if descriptor.samplesPerPixel == 1 {
            guard let raw = pixelData.pixelValues(forFrame: 0), !raw.isEmpty else {
                throw IconError(reason: "the instance's pixel values cannot be read")
            }
            let slope = dataSet.decimalString(for: .rescaleSlope)?.value ?? 1
            let intercept = dataSet.decimalString(for: .rescaleIntercept)?.value ?? 0
            let values = raw.map { Double($0) * slope + intercept }
            let center = dataSet.decimalStrings(for: .windowCenter)?.first?.value
            let width = dataSet.decimalStrings(for: .windowWidth)?.first?.value
            let low: Double, high: Double
            if let center, let width, width >= 1 {
                // PS3.3 C.11.2.1.2.1 linear function
                low = center - 0.5 - (width - 1) / 2
                high = center - 0.5 + (width - 1) / 2
            } else {
                low = values.min() ?? 0
                high = values.max() ?? 1
            }
            let span = max(high - low, 1e-9)
            for (i, v) in values.prefix(luminance.count).enumerated() {
                let y = min(max((v - low) / span, 0), 1)
                luminance[i] = pi == "MONOCHROME1" ? 1 - y : y
            }
        } else if descriptor.samplesPerPixel == 3 {
            let maxValue = Double(max(descriptor.maxPossibleValue, 1))
            let ybr = pi.hasPrefix("YBR")
            for r in 0..<srcRows {
                for c in 0..<srcColumns {
                    guard let v = pixelData.colorValue(row: r, column: c, frame: 0) else { continue }
                    let y = ybr ? Double(v.red) : 0.299 * Double(v.red) + 0.587 * Double(v.green) + 0.114 * Double(v.blue)
                    luminance[r * srcColumns + c] = min(max(y / maxValue, 0), 1)
                }
            }
        } else {
            throw IconError(reason: "Samples per Pixel \(descriptor.samplesPerPixel) cannot be made into a monochrome icon")
        }

        // Fit with the aspect ratio kept (square pixels assumed), area average, centred.
        let scale = min(Double(columns) / Double(srcColumns), Double(rows) / Double(srcRows))
        let fitColumns = max(1, min(columns, Int((Double(srcColumns) * scale).rounded())))
        let fitRows = max(1, min(rows, Int((Double(srcRows) * scale).rounded())))
        let left = (columns - fitColumns) / 2, top = (rows - fitRows) / 2
        var out = [UInt8](repeating: 0, count: rows * columns)
        for oy in 0..<fitRows {
            let y0 = min(srcRows - 1, oy * srcRows / fitRows)
            let y1 = max(y0 + 1, min(srcRows, (oy + 1) * srcRows / fitRows))
            for ox in 0..<fitColumns {
                let x0 = min(srcColumns - 1, ox * srcColumns / fitColumns)
                let x1 = max(x0 + 1, min(srcColumns, (ox + 1) * srcColumns / fitColumns))
                var sum = 0.0
                for y in y0..<y1 { for x in x0..<x1 { sum += luminance[y * srcColumns + x] } }
                let mean = sum / Double((y1 - y0) * (x1 - x0))
                out[(top + oy) * columns + left + ox] = UInt8(min(255, max(0, (mean * 255).rounded())))
            }
        }
        return out
    }
}
