import Foundation

/// DICOM UID Generator
///
/// Generates unique identifiers (UIDs) for DICOM objects following
/// the DICOM PS3.5 Section 9 - Unique Identifiers specification.
///
/// UIDs are composed of numeric components separated by periods (dots).
/// The maximum total length is 64 characters.
///
/// Reference: DICOM PS3.5 Section 9 - Unique Identifiers (UIDs)
///
/// NEMA-verified: 2026a, checked 2026-09-29 — the generated form satisfies every rule of
/// PS3.5 2026a §9.1 (components are digit strings; no component other than "0" starts
/// with 0; "." separators; at most 64 characters), and `DICOMUniqueIdentifier.parse`
/// enforces the same rules on the result. §9.2.2 requires a privately defined UID to be
/// built on an organisation's own registered root; the default root is the library's
/// private root (arc .4), no longer the OFFIS DCMTK root. No other standard data.
/// NEMA-verified: 2026a, checked 2026-10-01 — a root that breaks §9.1 or leaves no room for the
/// suffix within 64 characters yields a UUID derived UID ("2.25." + the UUID as a decimal
/// integer, Annex B.2) instead of crashing or truncating the unique suffix (D139).
public struct UIDGenerator: Sendable {

    /// Default UID root for generated UIDs.
    ///
    /// PS3.5 §9.2.2 requires privately defined UIDs to be built on a registered `<Org Root>`
    /// that the defining organisation owns. This library's private root is
    /// `1.2.826.0.1.3680043.10.511` (the same root the JP3D transfer syntaxes and the
    /// JP3D Volume Document SOP Class use); arc `.4` under it is reserved for generated
    /// Study / Series / SOP Instance UIDs, arc `.3` for the Implementation Class UID, so
    /// generated identifiers can never collide with the `.1`, `.2` and `.10` arcs.
    ///
    /// Before 2026-09-29 the default was the OFFIS DCMTK root `1.2.276.0.7230010.3`, which
    /// belongs to another organisation. Deployments with their own registered root should
    /// still pass it to `init(root:)`.
    ///
    /// Reference: PS3.5 Section 9.1 - UID Encoding Rules; Section 9.2.2 - Privately Defined Unique Identifiers
    public static let defaultRoot = "1.2.826.0.1.3680043.10.511.4"

    /// The OFFIS DCMTK root that was the default before 2026-09-29. Kept so callers that
    /// want to recognise UIDs generated by older DICOMKit versions can compare against it.
    @available(*, deprecated, message: "1.2.276.0.7230010.3 is the OFFIS DCMTK organisation root, not this library's; use defaultRoot (PS3.5 9.2.2)")
    public static let legacyDCMTKRoot = "1.2.276.0.7230010.3"
    
    /// The UID root prefix for generated UIDs
    public let root: String
    
    /// Creates a UID generator with the specified root
    /// - Parameter root: The UID root prefix to use for generated UIDs
    public init(root: String = UIDGenerator.defaultRoot) {
        self.root = root
    }
    
    /// Generates a unique UID based on timestamp and random components
    ///
    /// The generated UID format is:
    /// `{root}.{timestamp}.{random}`
    ///
    /// where:
    /// - root: The configured UID root
    /// - timestamp: Unix timestamp in microseconds
    /// - random: Random component for uniqueness
    ///
    /// When that UID cannot be built — the root breaks the PS3.5 9.1 encoding rules (an empty or
    /// non-numeric component, a leading zero) or leaves too little of the 64 characters for the
    /// suffix — a UUID derived UID (`2.25.<UUID as a decimal integer>`, PS3.5 B.2) is returned
    /// instead. Before 2026-10-01 a malformed root crashed (force unwrap) and a long root had its
    /// unique suffix cut off, so every call returned the same UID (D139).
    ///
    /// Reference: PS3.5 Section 9.1 - UID Encoding Rules; Annex B.2 - UUID Derived UID
    ///
    /// - Returns: A new unique DICOMUniqueIdentifier
    public func generate() -> DICOMUniqueIdentifier {
        // Get timestamp in microseconds
        let timestamp = UInt64(Date().timeIntervalSince1970 * 1_000_000)
        
        // Generate random component (0-999999)
        let random = UInt32.random(in: 0..<1_000_000)
        
        return Self.uid(root: root, suffix: "\(timestamp).\(random)")
    }
    
    /// Generates a unique UID with a specific type suffix
    ///
    /// The generated UID format is:
    /// `{root}.{type}.{timestamp}.{random}`; see ``generate()`` for the PS3.5 B.2 fallback.
    ///
    /// - Parameter type: A numeric identifier for the type of object (e.g., 1 for Study, 2 for Series, 3 for Instance)
    /// - Returns: A new unique DICOMUniqueIdentifier
    public func generate(type: UInt8) -> DICOMUniqueIdentifier {
        let timestamp = UInt64(Date().timeIntervalSince1970 * 1_000_000)
        let random = UInt32.random(in: 0..<1_000_000)
        
        return Self.uid(root: root, suffix: "\(type).\(timestamp).\(random)")
    }

    /// Whether `root` can prefix generated UIDs: it satisfies the PS3.5 9.1 encoding rules and
    /// leaves room within the 64 characters for the longest suffix ``generate(type:)`` appends
    /// (`.<type>.<µs timestamp>.<random>`, at most 28 characters).
    public static func isUsableRoot(_ root: String) -> Bool {
        DICOMUniqueIdentifier.parse(root) != nil
            && root.count + maximumSuffixLength <= DICOMUniqueIdentifier.maximumLength
    }

    /// `.` + 3-digit type + `.` + 16-digit µs timestamp (until the year 2286) + `.` + 6-digit random.
    static let maximumSuffixLength = 1 + 3 + 1 + 16 + 1 + 6

    /// A UUID derived UID: the root "2.25." followed by the 128-bit UUID as an unsigned decimal
    /// integer without leading zeros, at most 39 digits (PS3.5 2026a Annex B.2). Always valid
    /// under PS3.5 9.1 and at most 44 characters.
    public static func uuidDerivedUID(_ uuid: UUID = UUID()) -> DICOMUniqueIdentifier {
        let t = uuid.uuid
        var bytes = [t.0, t.1, t.2, t.3, t.4, t.5, t.6, t.7, t.8, t.9, t.10, t.11, t.12, t.13, t.14, t.15]
        var digits: [Character] = []
        // Repeated division of the big-endian 128-bit value by 10.
        while bytes.contains(where: { $0 != 0 }) {
            var remainder = 0
            for i in 0..<bytes.count {
                let value = remainder * 256 + Int(bytes[i])
                bytes[i] = UInt8(value / 10)
                remainder = value % 10
            }
            digits.append(Character(String(remainder)))
        }
        let value = "2.25." + (digits.isEmpty ? "0" : String(digits.reversed()))
        // Always parses: "2", "25" and a digit string without leading zeros, 44 characters at most.
        return DICOMUniqueIdentifier.parse(value) ?? "2.25.0"
    }

    /// `{root}.{suffix}` when it is a valid UID of at most 64 characters, else a UUID derived UID.
    private static func uid(root: String, suffix: String) -> DICOMUniqueIdentifier {
        let candidate = "\(root).\(suffix)"
        if candidate.count <= DICOMUniqueIdentifier.maximumLength,
           let uid = DICOMUniqueIdentifier.parse(candidate) {
            return uid
        }
        return uuidDerivedUID()
    }
    
    /// Generates a Study Instance UID
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a study
    public func generateStudyInstanceUID() -> DICOMUniqueIdentifier {
        return generate(type: 1)
    }
    
    /// Generates a Series Instance UID
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a series
    public func generateSeriesInstanceUID() -> DICOMUniqueIdentifier {
        return generate(type: 2)
    }
    
    /// Generates a SOP Instance UID
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a SOP instance
    public func generateSOPInstanceUID() -> DICOMUniqueIdentifier {
        return generate(type: 3)
    }
}

// MARK: - Static Convenience Methods

extension UIDGenerator {
    /// Shared default UID generator using the default root
    public static let shared = UIDGenerator()
    
    /// Generates a unique UID using the default generator
    /// - Returns: A new unique DICOMUniqueIdentifier
    public static func generateUID() -> DICOMUniqueIdentifier {
        return shared.generate()
    }
    
    /// Generates a Study Instance UID using the default generator
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a study
    public static func generateStudyInstanceUID() -> DICOMUniqueIdentifier {
        return shared.generateStudyInstanceUID()
    }
    
    /// Generates a Series Instance UID using the default generator
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a series
    public static func generateSeriesInstanceUID() -> DICOMUniqueIdentifier {
        return shared.generateSeriesInstanceUID()
    }
    
    /// Generates a SOP Instance UID using the default generator
    /// - Returns: A new unique DICOMUniqueIdentifier suitable for a SOP instance
    public static func generateSOPInstanceUID() -> DICOMUniqueIdentifier {
        return shared.generateSOPInstanceUID()
    }
}
