// NEMA-verified: 2026a, checked 2026-09-30 — Segmentation Type (BINARY, FRACTIONAL, LABELMAP), Segments Overlap and Fractional Type terms per PS3.3 2026a Table C.8.20-2 and C.8.20.2.3; Algorithm Type per Table C.8.20-4; Pixel Padding Value for LABELMAP per A.51.4 and C.8.20.2.4; SOP Class UIDs per PS3.6 Table A-1 and PS3.4 B.5.1.25; Palette Color Lookup Table and ICC Profile Modules required with PALETTE COLOR per Table A.51-1, absent otherwise per A.1.3.2 (D37b); Segmented Property Category/Type Code Sequences Type 1 per Table C.8.20-4 (D37d)
// NEMA-verified: 2026a, checked 2026-10-01 — Patient (Table C.7-1) / General Study (Table C.7-3) Type 2 rows and Enhanced General Equipment Module (Table C.7-8b, 4 Type 1 rows) carried for buildDataSet, both M in PS3.3 2026a Table A.51-1 (D71)
//
// Segmentation.swift
// DICOMKit
//
// Created by DICOMKit on 2026-02-05.
// Copyright © 2026 DICOMKit. All rights reserved.
//

import Foundation
import DICOMCore

/// DICOM Segmentation IOD
///
/// A Segmentation object contains labeled image regions representing anatomical structures,
/// pathological regions, or other areas of interest. Segmentations can be binary (presence/absence),
/// fractional (probability values) or a label map (one frame per slice whose pixel value is the
/// Segment Number) and are commonly generated by AI/ML algorithms or manual annotation tools.
///
/// Reference: PS3.3 A.51 - Segmentation IOD
/// Reference: PS3.3 C.8.20 - Segmentation Modules
/// Reference: PS3.4 B.5.1.25 - Segmentation Storage SOP Classes
public struct Segmentation: Sendable {

    // MARK: - SOP Class UIDs (PS3.6 Table A-1)

    /// Segmentation Storage — Segmentation Type BINARY or FRACTIONAL (PS3.4 B.5.1.25)
    public static let segmentationStorageUID = "1.2.840.10008.5.1.4.1.1.66.4"

    /// Label Map Segmentation Storage — Segmentation Type LABELMAP (PS3.4 B.5.1.25)
    public static let labelMapSegmentationStorageUID = "1.2.840.10008.5.1.4.1.1.66.7"

    /// The SOP Class UID PS3.4 B.5.1.25 assigns to a Segmentation Type
    public static func sopClassUID(for segmentationType: SegmentationType) -> String {
        switch segmentationType {
        case .binary, .fractional: return segmentationStorageUID
        case .labelmap: return labelMapSegmentationStorageUID
        }
    }

    // MARK: - Segmentation Identification

    /// SOP Instance UID
    public let sopInstanceUID: String

    /// SOP Class UID: Segmentation Storage (1.2.840.10008.5.1.4.1.1.66.4) for BINARY and
    /// FRACTIONAL, Label Map Segmentation Storage (1.2.840.10008.5.1.4.1.1.66.7) for LABELMAP
    public let sopClassUID: String
    
    /// Series Instance UID
    public let seriesInstanceUID: String
    
    /// Study Instance UID
    public let studyInstanceUID: String
    
    /// Instance Number
    public let instanceNumber: Int?

    /// Series Number (0020,0011), Type 1 in the Segmentation Series Module (Table C.8.20-1)
    public let seriesNumber: Int?

    /// Content Label - a label that identifies the content
    public let contentLabel: String?
    
    /// Content Description - human-readable description
    public let contentDescription: String?
    
    /// Content Creator's Name
    public let contentCreatorName: DICOMPersonName?
    
    /// Content Date
    public let contentDate: DICOMDate?
    
    /// Content Time
    public let contentTime: DICOMTime?
    
    // MARK: - Segmentation Type and Properties
    
    /// Type of segmentation (BINARY, FRACTIONAL or LABELMAP)
    public let segmentationType: SegmentationType

    /// Segmentation fractional type (only for FRACTIONAL)
    public let segmentationFractionalType: SegmentationFractionalType?

    /// Maximum fractional value (only for FRACTIONAL)
    public let maxFractionalValue: Int?

    /// Segments Overlap (0062,0013), Type 3. "If present, shall be NO if Segmentation
    /// Type (0062,0001) is LABELMAP" (PS3.3 Table C.8.20-2).
    public let segmentsOverlap: SegmentsOverlap?

    /// Pixel Padding Value (0028,0120): for a LABELMAP, the Segment Number treated as
    /// background (PS3.3 A.51.4, C.8.20.2.4, C.7.5.1.1.2). Shall not be present unless
    /// Segmentation Type is LABELMAP.
    public let pixelPaddingValue: Int?

    /// Number of segments
    public let numberOfSegments: Int
    
    /// Segment sequence - definitions of all segments
    public let segments: [Segment]
    
    // MARK: - Image Reference
    
    /// Frame of Reference UID
    public let frameOfReferenceUID: String?
    
    /// Dimension Organization UID
    public let dimensionOrganizationUID: String?
    
    /// Referenced Series Sequence
    public let referencedSeries: [SegmentationReferencedSeries]
    
    // MARK: - Pixel Data Properties
    
    /// Number of frames
    public let numberOfFrames: Int
    
    /// Rows
    public let rows: Int
    
    /// Columns
    public let columns: Int
    
    /// Bits Allocated
    public let bitsAllocated: Int
    
    /// Bits Stored
    public let bitsStored: Int
    
    /// High Bit
    public let highBit: Int
    
    /// Samples Per Pixel
    public let samplesPerPixel: Int
    
    /// Photometric Interpretation
    public let photometricInterpretation: String
    
    /// Pixel Representation (0 = unsigned, 1 = signed)
    public let pixelRepresentation: Int
    
    // MARK: - Functional Groups
    
    /// Shared Functional Groups Sequence
    public let sharedFunctionalGroups: FunctionalGroup?
    
    /// Per-Frame Functional Groups Sequence
    public let perFrameFunctionalGroups: [FunctionalGroup]

    // MARK: - PALETTE COLOR (LABELMAP only)

    /// Palette Color Lookup Table Module (PS3.3 2026a C.7.9, Table C.7-22a), which the
    /// Segmentation IOD requires "if Photometric Interpretation (0028,0004) has a Value of
    /// PALETTE COLOR" (Table A.51-1). PALETTE COLOR is allowed only for LABELMAP
    /// (Table C.8.20-2); the table is indexed by the stored pixel value, i.e. the Segment
    /// Number. `nil` for MONOCHROME2: a Conditional Module whose condition is not met
    /// "shall not be present" (A.1.3.2).
    public let paletteColorLookupTable: PaletteColorLUT?

    /// ICC Profile (0028,2000) of the ICC Profile Module (C.11.15, Table C.11.15-1), which
    /// the Segmentation IOD requires with PALETTE COLOR (Table A.51-1). The profile must be
    /// an Input Device ("scnr") RGB profile with a Lab or XYZ PCS (C.11.15.1.1).
    public let iccProfile: Data?

    /// Color Space (0028,2002), Type 3 in the ICC Profile Module (C.11.15.1.2 Defined
    /// Terms SRGB, ADOBERGB, ROMMRGB, DISPLAYP3)
    public let colorSpace: String?

    // MARK: - Patient, General Study and Enhanced General Equipment (Table A.51-1)

    /// The Type 2 attributes of the Patient (PS3.3 2026a Table C.7-1) and General Study
    /// (Table C.7-3) Modules, both M in Table A.51-1; written by `buildDataSet`, zero length
    /// when unknown. `SegmentationBuilder.setPatientAndStudy(_:)` sets it.
    public var patientAndStudy = SegmentationPatientAndStudy()

    /// The Enhanced General Equipment Module (Table A.51-1, M; Table C.7-8b, all Type 1),
    /// written by `buildDataSet`; it also supplies Manufacturer (0008,0070) of the General
    /// Equipment Module. `SegmentationBuilder.setEquipment(_:)` sets it.
    public var equipment = SegmentationEquipment.dicomKit
    
    // MARK: - Initialization
    
    /// Initialize a Segmentation
    ///
    /// `sopClassUID` defaults to the SOP Class PS3.4 B.5.1.25 assigns to `segmentationType`.
    public init(
        sopInstanceUID: String,
        sopClassUID: String? = nil,
        seriesInstanceUID: String,
        studyInstanceUID: String,
        instanceNumber: Int? = nil,
        seriesNumber: Int? = nil,
        contentLabel: String? = nil,
        contentDescription: String? = nil,
        contentCreatorName: DICOMPersonName? = nil,
        contentDate: DICOMDate? = nil,
        contentTime: DICOMTime? = nil,
        segmentationType: SegmentationType,
        segmentationFractionalType: SegmentationFractionalType? = nil,
        maxFractionalValue: Int? = nil,
        segmentsOverlap: SegmentsOverlap? = nil,
        pixelPaddingValue: Int? = nil,
        numberOfSegments: Int,
        segments: [Segment],
        frameOfReferenceUID: String? = nil,
        dimensionOrganizationUID: String? = nil,
        referencedSeries: [SegmentationReferencedSeries] = [],
        numberOfFrames: Int,
        rows: Int,
        columns: Int,
        bitsAllocated: Int,
        bitsStored: Int,
        highBit: Int,
        samplesPerPixel: Int = 1,
        photometricInterpretation: String = "MONOCHROME2",
        pixelRepresentation: Int = 0,
        sharedFunctionalGroups: FunctionalGroup? = nil,
        perFrameFunctionalGroups: [FunctionalGroup] = [],
        paletteColorLookupTable: PaletteColorLUT? = nil,
        iccProfile: Data? = nil,
        colorSpace: String? = nil
    ) {
        self.sopInstanceUID = sopInstanceUID
        self.sopClassUID = sopClassUID ?? Segmentation.sopClassUID(for: segmentationType)
        self.seriesInstanceUID = seriesInstanceUID
        self.studyInstanceUID = studyInstanceUID
        self.instanceNumber = instanceNumber
        self.seriesNumber = seriesNumber
        self.contentLabel = contentLabel
        self.contentDescription = contentDescription
        self.contentCreatorName = contentCreatorName
        self.contentDate = contentDate
        self.contentTime = contentTime
        self.segmentationType = segmentationType
        self.segmentationFractionalType = segmentationFractionalType
        self.maxFractionalValue = maxFractionalValue
        self.segmentsOverlap = segmentsOverlap
        self.pixelPaddingValue = pixelPaddingValue
        self.numberOfSegments = numberOfSegments
        self.segments = segments
        self.frameOfReferenceUID = frameOfReferenceUID
        self.dimensionOrganizationUID = dimensionOrganizationUID
        self.referencedSeries = referencedSeries
        self.numberOfFrames = numberOfFrames
        self.rows = rows
        self.columns = columns
        self.bitsAllocated = bitsAllocated
        self.bitsStored = bitsStored
        self.highBit = highBit
        self.samplesPerPixel = samplesPerPixel
        self.photometricInterpretation = photometricInterpretation
        self.pixelRepresentation = pixelRepresentation
        self.sharedFunctionalGroups = sharedFunctionalGroups
        self.perFrameFunctionalGroups = perFrameFunctionalGroups
        self.paletteColorLookupTable = paletteColorLookupTable
        self.iccProfile = iccProfile
        self.colorSpace = colorSpace
    }
}

// MARK: - SegmentationType

/// Type of segmentation encoding — Segmentation Type (0062,0001), Enumerated Values
/// BINARY, FRACTIONAL, LABELMAP
///
/// Reference: PS3.3 Table C.8.20-2 and C.8.20.2.3 - Segmentation Image Module
public enum SegmentationType: String, Sendable, Codable, CaseIterable {
    /// BINARY: the segmented property is present with a pixel value of 1 and absent with 0
    /// (C.8.20.2.3.1). Bits Allocated 1, one frame per segment and slice.
    case binary = "BINARY"

    /// FRACTIONAL: the segmented property is a value from 0 to Maximum Fractional Value
    /// (0062,000E), qualified by Segmentation Fractional Type (C.8.20.2.3.2). Bits Allocated 8.
    case fractional = "FRACTIONAL"

    /// LABELMAP: the presence of the segmented property is conveyed by the integer pixel
    /// value, which is one of the Segment Number (0062,0004) values; every pixel value
    /// actually encoded must be described by a Segment Sequence Item (C.8.20.2.3.3).
    /// Bits Allocated 8 or 16, Photometric Interpretation MONOCHROME2 or PALETTE COLOR, one
    /// frame per slice, no Segmentation Functional Group (Table A.51-2).
    case labelmap = "LABELMAP"

    /// Photometric Interpretation (0028,0004) Enumerated Values for this type (Table C.8.20-2)
    public var allowedPhotometricInterpretations: [String] {
        switch self {
        case .binary, .fractional: return ["MONOCHROME2"]
        case .labelmap: return ["MONOCHROME2", "PALETTE COLOR"]
        }
    }

    /// Bits Allocated (0028,0100) Enumerated Values for this type (Table C.8.20-2)
    public var allowedBitsAllocated: [Int] {
        switch self {
        case .binary: return [1]
        case .fractional: return [8]
        case .labelmap: return [8, 16]
        }
    }
}

// MARK: - SegmentsOverlap

/// Segments Overlap (0062,0013): whether any pixel is or might be in more than one Segment
///
/// Reference: PS3.3 Table C.8.20-2 and C.8.20.2.3
public enum SegmentsOverlap: String, Sendable, Codable, CaseIterable {
    /// Some Segments overlap
    case yes = "YES"
    /// Some Segments might overlap
    case undefined = "UNDEFINED"
    /// No Segments overlap (the only value allowed for LABELMAP)
    case no = "NO"
}

// MARK: - SegmentationFractionalType

/// Type of fractional segmentation values
///
/// Reference: PS3.3 C.8.20.2 - Segmentation Image Module
public enum SegmentationFractionalType: String, Sendable, Codable {
    /// Probability values (0.0 to 1.0)
    case probability = "PROBABILITY"
    
    /// Occupancy values (fraction of voxel occupied, 0.0 to 1.0)
    case occupancy = "OCCUPANCY"
}

// MARK: - Segment

/// Segment Definition
///
/// Defines a single segment with its identification, category, and visual properties.
///
/// Reference: PS3.3 C.8.20.4 - Segment Description Macro
public struct Segment: Sendable, Hashable, Identifiable {

    /// Segment Number (0062,0004), unique within the Instance. For BINARY and FRACTIONAL it
    /// starts at 1 and increases monotonically by 1; for LABELMAP it is the pixel value that
    /// encodes the segment and may be any value, including 0 (PS3.3 C.8.20.2.4).
    public let segmentNumber: Int
    
    /// Segment Label - human-readable name
    public let segmentLabel: String
    
    /// Segment Description
    public let segmentDescription: String?
    
    /// Segmentation Algorithm Type
    public let segmentAlgorithmType: SegmentAlgorithmType?
    
    /// Segmentation Algorithm Name
    public let segmentAlgorithmName: String?
    
    /// Segmented Property Category Code Sequence (0062,0003) Item (CID 7150), e.g. Tissue,
    /// Anatomical Structure. Type 1 in the Segment Description Macro (PS3.3 2026a Table
    /// C.8.20-4): optional here so partial or received models can be held, but
    /// `Segmentation.buildDataSet(pixelData:)` throws when it is `nil`.
    public let category: CodedConcept?
    
    /// Segmented Property Type Code Sequence (0062,000F) Item (CID 7151), e.g. Liver, Tumor.
    /// Type 1 (Table C.8.20-4); `Segmentation.buildDataSet(pixelData:)` throws when `nil`.
    public let type: CodedConcept?
    
    /// Anatomic Region Sequence
    public let anatomicRegion: CodedConcept?
    
    /// Anatomic Region Modifier Sequence
    public let anatomicRegionModifier: CodedConcept?
    
    /// Recommended Display Color (RGB, CIELab values 0-65535)
    public let recommendedDisplayCIELabValue: CIELabColor?
    
    /// Tracking ID for longitudinal studies
    public let trackingID: String?
    
    /// Tracking UID for globally unique identification
    public let trackingUID: String?
    
    /// Identifiable conformance
    public var id: Int { segmentNumber }
    
    /// Initialize a Segment
    public init(
        segmentNumber: Int,
        segmentLabel: String,
        segmentDescription: String? = nil,
        segmentAlgorithmType: SegmentAlgorithmType? = nil,
        segmentAlgorithmName: String? = nil,
        category: CodedConcept? = nil,
        type: CodedConcept? = nil,
        anatomicRegion: CodedConcept? = nil,
        anatomicRegionModifier: CodedConcept? = nil,
        recommendedDisplayCIELabValue: CIELabColor? = nil,
        trackingID: String? = nil,
        trackingUID: String? = nil
    ) {
        self.segmentNumber = segmentNumber
        self.segmentLabel = segmentLabel
        self.segmentDescription = segmentDescription
        self.segmentAlgorithmType = segmentAlgorithmType
        self.segmentAlgorithmName = segmentAlgorithmName
        self.category = category
        self.type = type
        self.anatomicRegion = anatomicRegion
        self.anatomicRegionModifier = anatomicRegionModifier
        self.recommendedDisplayCIELabValue = recommendedDisplayCIELabValue
        self.trackingID = trackingID
        self.trackingUID = trackingUID
    }
}

// MARK: - SegmentAlgorithmType

/// Type of algorithm used to generate the segment
///
/// Reference: PS3.3 C.8.20.4 - Segment Description Macro
public enum SegmentAlgorithmType: String, Sendable, Codable {
    /// Automatic algorithm
    case automatic = "AUTOMATIC"
    
    /// Semi-automatic algorithm (with user interaction)
    case semiautomatic = "SEMIAUTOMATIC"
    
    /// Manual segmentation by user
    case manual = "MANUAL"
}

// MARK: - CIELabColor

/// CIELab color representation
///
/// Reference: PS3.3 C.10.7 - Display Shutter Module
public struct CIELabColor: Sendable, Hashable {
    /// L* - Lightness (0-65535)
    public let l: Int
    
    /// a* - Green-Red axis (-32768 to 32767, stored as 0-65535)
    public let a: Int
    
    /// b* - Blue-Yellow axis (-32768 to 32767, stored as 0-65535)
    public let b: Int
    
    /// Initialize a CIELab color
    public init(l: Int, a: Int, b: Int) {
        self.l = l
        self.a = a
        self.b = b
    }
}

// MARK: - ReferencedSeries

/// Referenced Series for Segmentation
///
/// Identifies the series that the segmentation is derived from.
public struct SegmentationReferencedSeries: Sendable, Hashable {
    /// Series Instance UID
    public let seriesInstanceUID: String
    
    /// Referenced Instance Sequence
    public let referencedInstances: [SegmentationReferencedInstance]
    
    /// Initialize a ReferencedSeries
    public init(
        seriesInstanceUID: String,
        referencedInstances: [SegmentationReferencedInstance] = []
    ) {
        self.seriesInstanceUID = seriesInstanceUID
        self.referencedInstances = referencedInstances
    }
}

// MARK: - ReferencedInstance

/// Referenced Instance for Segmentation
public struct SegmentationReferencedInstance: Sendable, Hashable {
    /// Referenced SOP Class UID
    public let sopClassUID: String
    
    /// Referenced SOP Instance UID
    public let sopInstanceUID: String
    
    /// Referenced Frame Numbers (for multi-frame images)
    public let referencedFrameNumbers: [Int]?
    
    /// Initialize a ReferencedInstance
    public init(
        sopClassUID: String,
        sopInstanceUID: String,
        referencedFrameNumbers: [Int]? = nil
    ) {
        self.sopClassUID = sopClassUID
        self.sopInstanceUID = sopInstanceUID
        self.referencedFrameNumbers = referencedFrameNumbers
    }
}

// MARK: - FunctionalGroup

/// Functional Group containing per-frame or shared attributes
///
/// Reference: PS3.3 C.7.6.16 - Multi-frame Functional Groups Module
public struct FunctionalGroup: Sendable {
    /// Segment Identification
    public let segmentIdentification: SegmentIdentification?
    
    /// Derivation Image
    public let derivationImage: DerivationImage?
    
    /// Frame Content
    public let frameContent: FrameContent?
    
    /// Plane Position
    public let planePosition: PlanePosition?
    
    /// Plane Orientation
    public let planeOrientation: PlaneOrientation?
    
    /// Initialize a FunctionalGroup
    public init(
        segmentIdentification: SegmentIdentification? = nil,
        derivationImage: DerivationImage? = nil,
        frameContent: FrameContent? = nil,
        planePosition: PlanePosition? = nil,
        planeOrientation: PlaneOrientation? = nil
    ) {
        self.segmentIdentification = segmentIdentification
        self.derivationImage = derivationImage
        self.frameContent = frameContent
        self.planePosition = planePosition
        self.planeOrientation = planeOrientation
    }
}

// MARK: - SegmentIdentification

/// Segment Identification Functional Group (Segmentation Macro, Table C.8.20-3)
///
/// Identifies which segment this frame represents. Required per frame for BINARY and
/// FRACTIONAL; not used for LABELMAP, where the pixel value is the Segment Number
/// (Table A.51-2: "Required if … Segmentation Type (0062,0001) is not LABELMAP").
///
/// Reference: PS3.3 C.8.20.3.1 - Segmentation Macro
public struct SegmentIdentification: Sendable {
    /// Referenced Segment Number
    public let referencedSegmentNumber: Int
    
    /// Initialize a SegmentIdentification
    public init(referencedSegmentNumber: Int) {
        self.referencedSegmentNumber = referencedSegmentNumber
    }
}

// MARK: - DerivationImage

/// Derivation Image Functional Group
///
/// Describes how this frame was derived from source images.
///
/// Reference: PS3.3 C.7.6.16.2.3 - Derivation Image Functional Group Macro
public struct DerivationImage: Sendable {
    /// Source Image Sequence
    public let sourceImages: [SourceImage]
    
    /// Derivation Description
    public let derivationDescription: String?
    
    /// Derivation Code Sequence
    public let derivationCode: CodedConcept?
    
    /// Initialize a DerivationImage
    public init(
        sourceImages: [SourceImage],
        derivationDescription: String? = nil,
        derivationCode: CodedConcept? = nil
    ) {
        self.sourceImages = sourceImages
        self.derivationDescription = derivationDescription
        self.derivationCode = derivationCode
    }
}

// MARK: - SourceImage

/// Source Image reference
public struct SourceImage: Sendable {
    /// Referenced SOP Class UID
    public let sopClassUID: String
    
    /// Referenced SOP Instance UID
    public let sopInstanceUID: String
    
    /// Referenced Frame Number (for multi-frame source)
    public let referencedFrameNumber: Int?
    
    /// Purpose of Reference Code Sequence
    public let purposeOfReference: CodedConcept?
    
    /// Initialize a SourceImage
    public init(
        sopClassUID: String,
        sopInstanceUID: String,
        referencedFrameNumber: Int? = nil,
        purposeOfReference: CodedConcept? = nil
    ) {
        self.sopClassUID = sopClassUID
        self.sopInstanceUID = sopInstanceUID
        self.referencedFrameNumber = referencedFrameNumber
        self.purposeOfReference = purposeOfReference
    }
}

// MARK: - FrameContent

/// Frame Content Functional Group
///
/// Reference: PS3.3 C.7.6.16.2.2 - Frame Content Macro
public struct FrameContent: Sendable {
    /// Frame Acquisition Number
    public let frameAcquisitionNumber: Int?
    
    /// Frame Reference DateTime
    public let frameReferenceDateTime: String?
    
    /// Frame Acquisition DateTime
    public let frameAcquisitionDateTime: String?
    
    /// Dimension Index Values (0020,9157)
    public let dimensionIndexValues: [Int]?

    /// Stack ID (0020,9056)
    public let stackID: String?

    /// In-Stack Position Number (0020,9057), required if Stack ID is present
    public let inStackPositionNumber: Int?

    /// Initialize a FrameContent
    public init(
        frameAcquisitionNumber: Int? = nil,
        frameReferenceDateTime: String? = nil,
        frameAcquisitionDateTime: String? = nil,
        dimensionIndexValues: [Int]? = nil,
        stackID: String? = nil,
        inStackPositionNumber: Int? = nil
    ) {
        self.frameAcquisitionNumber = frameAcquisitionNumber
        self.frameReferenceDateTime = frameReferenceDateTime
        self.frameAcquisitionDateTime = frameAcquisitionDateTime
        self.dimensionIndexValues = dimensionIndexValues
        self.stackID = stackID
        self.inStackPositionNumber = inStackPositionNumber
    }
}

// MARK: - PlanePosition

/// Plane Position Functional Group
///
/// Reference: PS3.3 C.7.6.16.2.1 - Plane Position Macro
public struct PlanePosition: Sendable {
    /// Image Position (Patient) - x, y, z coordinates in mm
    public let imagePositionPatient: [Double]
    
    /// Initialize a PlanePosition
    public init(imagePositionPatient: [Double]) {
        self.imagePositionPatient = imagePositionPatient
    }
}

// MARK: - PlaneOrientation

/// Plane Orientation Functional Group
///
/// Reference: PS3.3 C.7.6.16.2.1 - Plane Orientation Macro
public struct PlaneOrientation: Sendable {
    /// Image Orientation (Patient) - 6 values defining row and column directions
    public let imageOrientationPatient: [Double]
    
    /// Initialize a PlaneOrientation
    public init(imageOrientationPatient: [Double]) {
        self.imageOrientationPatient = imageOrientationPatient
    }
}


// MARK: - Patient / Study and Equipment attributes (PS3.3 2026a Table A.51-1)

/// The Type 2 attributes of the Patient Module (PS3.3 2026a Table C.7-1: Patient's Name,
/// Patient ID, Patient's Birth Date, Patient's Sex) and General Study Module (Table C.7-3:
/// Study Date, Study Time, Referring Physician's Name, Study ID, Accession Number); `nil` is
/// written as zero length (value unknown, PS3.5 7.4.3)
public struct SegmentationPatientAndStudy: Sendable, Equatable, Hashable {
    public var patientName: String?
    public var patientID: String?
    public var patientBirthDate: String?
    public var patientSex: String?
    public var studyDate: String?
    public var studyTime: String?
    public var referringPhysicianName: String?
    public var studyID: String?
    public var accessionNumber: String?

    public init(
        patientName: String? = nil, patientID: String? = nil, patientBirthDate: String? = nil,
        patientSex: String? = nil, studyDate: String? = nil, studyTime: String? = nil,
        referringPhysicianName: String? = nil, studyID: String? = nil, accessionNumber: String? = nil
    ) {
        self.patientName = patientName
        self.patientID = patientID
        self.patientBirthDate = patientBirthDate
        self.patientSex = patientSex
        self.studyDate = studyDate
        self.studyTime = studyTime
        self.referringPhysicianName = referringPhysicianName
        self.studyID = studyID
        self.accessionNumber = accessionNumber
    }

    /// The attributes copied from a source image, so that the segmentation joins its study
    public init(copyingFrom source: DataSet) {
        self.init(
            patientName: source.string(for: .patientName), patientID: source.string(for: .patientID),
            patientBirthDate: source.string(for: .patientBirthDate), patientSex: source.string(for: .patientSex),
            studyDate: source.string(for: .studyDate), studyTime: source.string(for: .studyTime),
            referringPhysicianName: source.string(for: .referringPhysicianName),
            studyID: source.string(for: .studyID), accessionNumber: source.string(for: .accessionNumber))
    }

    /// (tag, VR, value) for each attribute, in data set order
    var elements: [(Tag, VR, String?)] {
        [(.studyDate, .DA, studyDate), (.studyTime, .TM, studyTime), (.accessionNumber, .SH, accessionNumber),
         (.referringPhysicianName, .PN, referringPhysicianName), (.patientName, .PN, patientName),
         (.patientID, .LO, patientID), (.patientBirthDate, .DA, patientBirthDate),
         (.patientSex, .CS, patientSex), (.studyID, .SH, studyID)]
    }
}

/// The Enhanced General Equipment Module (PS3.3 2026a Table C.7-8b): Manufacturer
/// (0008,0070), Manufacturer's Model Name (0008,1090), Device Serial Number (0018,1000) and
/// Software Versions (0018,1020), all Type 1
public struct SegmentationEquipment: Sendable, Equatable, Hashable {
    public var manufacturer: String
    public var manufacturerModelName: String
    public var deviceSerialNumber: String
    public var softwareVersions: String

    public init(manufacturer: String, manufacturerModelName: String, deviceSerialNumber: String, softwareVersions: String) {
        self.manufacturer = manufacturer
        self.manufacturerModelName = manufacturerModelName
        self.deviceSerialNumber = deviceSerialNumber
        self.softwareVersions = softwareVersions
    }

    /// DICOMKit as the producing software: Manufacturer "DICOMKit", Model Name
    /// "SegmentationBuilder", Device Serial Number = DICOMKit's Implementation Class UID (the
    /// software has no hardware serial number), Software Versions = its Implementation
    /// Version Name
    public static let dicomKit = SegmentationEquipment(
        manufacturer: "DICOMKit",
        manufacturerModelName: "SegmentationBuilder",
        deviceSerialNumber: DICOMFile.implementationClassUID,
        softwareVersions: DICOMFile.implementationVersionName)
}
