// ConfidentialityProfileTableE11.swift
// DICOMKit
//
// GENERATED by Scripts/generate_confidentiality_profile.py from DICOM PS3.15 2026a - Security and System Management Profiles,
// Table E.1-1 (651 single-tag rows; the 4 pattern rows are applied by group
// in ConfidentialityEngine). Do not hand-edit: fix the generator and regenerate.
//
// NEMA-verified: 2026a, checked 2026-09-30 — every single-tag row of PS3.15 2026a Table E.1-1 (651), with its Basic Profile action and all option columns, generated from the DocBook (D69); `generate_confidentiality_profile.py --check` re-verifies it.

extension ConfidentialityProfile {
    /// One row of PS3.15 Table E.1-1: the Basic Profile action and, per option, the
    /// action the option substitutes ("K" keep, "C" clean), as the table writes them.
    struct E11Row: Sendable, Equatable {
        let basic: String
        var uids: String? = nil
        var device: String? = nil
        var institution: String? = nil
        var patient: String? = nil
        var fullDates: String? = nil
        var modifiedDates: String? = nil
        var cleanDescriptors: String? = nil
        var cleanStructuredContent: String? = nil
        var cleanGraphics: String? = nil
    }

    /// Table E.1-1, keyed by (group << 16 | element).
    static let tableE11: [UInt32: E11Row] = [
        0x00001000: E11Row(basic: "X", uids: "K"),  // Affected SOP Instance UID
        0x00001001: E11Row(basic: "U", uids: "K"),  // Requested SOP Instance UID
        0x00020003: E11Row(basic: "U", uids: "K"),  // Media Storage SOP Instance UID
        0x00041511: E11Row(basic: "U", uids: "K"),  // Referenced SOP Instance UID in File
        0x00080012: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Instance Creation Date
        0x00080013: E11Row(basic: "X/Z/D", fullDates: "K", modifiedDates: "C"),  // Instance Creation Time
        0x00080014: E11Row(basic: "U", uids: "K"),  // Instance Creator UID
        0x00080015: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Instance Coercion DateTime
        0x00080017: E11Row(basic: "U", uids: "K"),  // Acquisition UID
        0x00080018: E11Row(basic: "U", uids: "K"),  // SOP Instance UID
        0x00080019: E11Row(basic: "U", uids: "K"),  // Pyramid UID
        0x00080020: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Study Date
        0x00080021: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Series Date
        0x00080022: E11Row(basic: "X/Z", fullDates: "K", modifiedDates: "C"),  // Acquisition Date
        0x00080023: E11Row(basic: "Z/D", fullDates: "K", modifiedDates: "C"),  // Content Date
        0x00080024: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Overlay Date
        0x00080025: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Curve Date
        0x0008002A: E11Row(basic: "X/Z/D", fullDates: "K", modifiedDates: "C"),  // Acquisition DateTime
        0x00080030: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Study Time
        0x00080031: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Series Time
        0x00080032: E11Row(basic: "X/Z", fullDates: "K", modifiedDates: "C"),  // Acquisition Time
        0x00080033: E11Row(basic: "Z/D", fullDates: "K", modifiedDates: "C"),  // Content Time
        0x00080034: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Overlay Time
        0x00080035: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Curve Time
        0x00080050: E11Row(basic: "Z"),  // Accession Number
        0x00080054: E11Row(basic: "X", device: "C"),  // Retrieve AE Title
        0x00080055: E11Row(basic: "X", device: "C"),  // Station AE Title
        0x00080058: E11Row(basic: "U", uids: "K"),  // Failed SOP Instance UID List
        0x00080080: E11Row(basic: "X/Z/D", institution: "K"),  // Institution Name
        0x00080081: E11Row(basic: "X", institution: "K"),  // Institution Address
        0x00080082: E11Row(basic: "X/Z/D", institution: "K"),  // Institution Code Sequence
        0x00080090: E11Row(basic: "Z"),  // Referring Physician's Name
        0x00080092: E11Row(basic: "X"),  // Referring Physician's Address
        0x00080094: E11Row(basic: "X"),  // Referring Physician's Telephone Numbers
        0x00080096: E11Row(basic: "X"),  // Referring Physician Identification Sequence
        0x0008009C: E11Row(basic: "Z"),  // Consulting Physician's Name
        0x0008009D: E11Row(basic: "X"),  // Consulting Physician Identification Sequence
        0x00080106: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Context Group Version
        0x00080107: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Context Group Local Version
        0x00080201: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Timezone Offset From UTC
        0x00081000: E11Row(basic: "X", device: "C"),  // Network ID
        0x00081010: E11Row(basic: "X/Z/D", device: "K"),  // Station Name
        0x00081030: E11Row(basic: "X", cleanDescriptors: "C"),  // Study Description
        0x0008103E: E11Row(basic: "X", cleanDescriptors: "C"),  // Series Description
        0x00081040: E11Row(basic: "X", institution: "K"),  // Institutional Department Name
        0x00081041: E11Row(basic: "X", institution: "K"),  // Institutional Department Type Code Sequence
        0x00081048: E11Row(basic: "X"),  // Physician(s) of Record
        0x00081049: E11Row(basic: "X"),  // Physician(s) of Record Identification Sequence
        0x00081050: E11Row(basic: "X"),  // Performing Physician's Name
        0x00081052: E11Row(basic: "X"),  // Performing Physician Identification Sequence
        0x00081060: E11Row(basic: "X"),  // Name of Physician(s) Reading Study
        0x00081062: E11Row(basic: "X"),  // Physician(s) Reading Study Identification Sequence
        0x00081070: E11Row(basic: "X/Z/D"),  // Operators' Name
        0x00081072: E11Row(basic: "X/D"),  // Operator Identification Sequence
        0x00081080: E11Row(basic: "X", cleanDescriptors: "C"),  // Admitting Diagnoses Description
        0x00081084: E11Row(basic: "X", cleanDescriptors: "C"),  // Admitting Diagnoses Code Sequence
        0x00081088: E11Row(basic: "X", cleanDescriptors: "C"),  // Pyramid Description
        0x00081110: E11Row(basic: "X/Z", uids: "K"),  // Referenced Study Sequence
        0x00081111: E11Row(basic: "X/Z/D", uids: "K"),  // Referenced Performed Procedure Step Sequence
        0x00081120: E11Row(basic: "X", uids: "K"),  // Referenced Patient Sequence
        0x00081140: E11Row(basic: "X/Z/U*", uids: "K"),  // Referenced Image Sequence
        0x00081155: E11Row(basic: "U", uids: "K"),  // Referenced SOP Instance UID
        0x00081195: E11Row(basic: "U", uids: "K"),  // Transaction UID
        0x00081301: E11Row(basic: "X", cleanDescriptors: "C"),  // Principal Diagnosis Code Sequence
        0x00081302: E11Row(basic: "X", cleanDescriptors: "C"),  // Primary Diagnosis Code Sequence
        0x00081303: E11Row(basic: "X", cleanDescriptors: "C"),  // Secondary Diagnoses Code Sequence
        0x00081304: E11Row(basic: "X", cleanDescriptors: "C"),  // Histological Diagnoses Code Sequence
        0x00082111: E11Row(basic: "X", cleanDescriptors: "C"),  // Derivation Description
        0x00082112: E11Row(basic: "X/Z/U*", uids: "K"),  // Source Image Sequence
        0x00083010: E11Row(basic: "U", uids: "K"),  // Irradiation Event UID
        0x00084000: E11Row(basic: "X", cleanDescriptors: "C"),  // Identifying Comments
        0x00100010: E11Row(basic: "Z"),  // Patient's Name
        0x00100011: E11Row(basic: "X"),  // Person Names to Use Sequence
        0x00100012: E11Row(basic: "X"),  // Name to Use
        0x00100013: E11Row(basic: "X"),  // Name to Use Comment
        0x00100014: E11Row(basic: "X"),  // Third Person Pronouns Sequence
        0x00100015: E11Row(basic: "X"),  // Pronoun Code Sequence
        0x00100016: E11Row(basic: "X", cleanDescriptors: "C"),  // Pronoun Comment
        0x00100020: E11Row(basic: "Z/D"),  // Patient ID
        0x00100021: E11Row(basic: "X"),  // Issuer of Patient ID
        0x00100030: E11Row(basic: "Z"),  // Patient's Birth Date
        0x00100032: E11Row(basic: "X"),  // Patient's Birth Time
        0x00100040: E11Row(basic: "Z", patient: "K"),  // Patient's Sex
        0x00100041: E11Row(basic: "X"),  // Gender Identity Sequence
        0x00100042: E11Row(basic: "X", patient: "C", cleanDescriptors: "C"),  // Sex Parameters for Clinical Use Category Comment
        0x00100043: E11Row(basic: "X", patient: "K"),  // Sex Parameters for Clinical Use Category Sequence
        0x00100044: E11Row(basic: "X"),  // Gender Identity Code Sequence
        0x00100045: E11Row(basic: "X", cleanDescriptors: "C"),  // Gender Identity Comment
        0x00100046: E11Row(basic: "X", patient: "K"),  // Sex Parameters for Clinical Use Category Code Sequence
        0x00100047: E11Row(basic: "X", patient: "K"),  // Sex Parameters for Clinical Use Category Reference
        0x00100050: E11Row(basic: "X"),  // Patient's Insurance Plan Code Sequence
        0x00100101: E11Row(basic: "X"),  // Patient's Primary Language Code Sequence
        0x00100102: E11Row(basic: "X"),  // Patient's Primary Language Modifier Code Sequence
        0x00101000: E11Row(basic: "X"),  // Other Patient IDs
        0x00101001: E11Row(basic: "X"),  // Other Patient Names
        0x00101002: E11Row(basic: "X"),  // Other Patient IDs Sequence
        0x00101005: E11Row(basic: "X"),  // Patient's Birth Name
        0x00101010: E11Row(basic: "X", patient: "K"),  // Patient's Age
        0x00101020: E11Row(basic: "X", patient: "K"),  // Patient's Size
        0x00101030: E11Row(basic: "X", patient: "K"),  // Patient's Weight
        0x00101040: E11Row(basic: "X"),  // Patient's Address
        0x00101050: E11Row(basic: "X"),  // Insurance Plan Identification
        0x00101060: E11Row(basic: "X"),  // Patient's Mother's Birth Name
        0x00101080: E11Row(basic: "X"),  // Military Rank
        0x00101081: E11Row(basic: "X"),  // Branch of Service
        0x00101090: E11Row(basic: "X"),  // Medical Record Locator
        0x00101100: E11Row(basic: "X"),  // Referenced Patient Photo Sequence
        0x00102000: E11Row(basic: "X", cleanDescriptors: "C"),  // Medical Alerts
        0x00102110: E11Row(basic: "X", patient: "C", cleanDescriptors: "C"),  // Allergies
        0x00102150: E11Row(basic: "X"),  // Country of Residence
        0x00102152: E11Row(basic: "X"),  // Region of Residence
        0x00102154: E11Row(basic: "X"),  // Patient's Telephone Numbers
        0x00102155: E11Row(basic: "X"),  // Patient's Telecom Information
        0x00102160: E11Row(basic: "X", patient: "K"),  // Ethnic Group
        0x00102161: E11Row(basic: "X", patient: "K"),  // Ethnic Group Code Sequence
        0x00102162: E11Row(basic: "X", patient: "K"),  // Ethnic Groups
        0x00102180: E11Row(basic: "X", cleanDescriptors: "C"),  // Occupation
        0x001021A0: E11Row(basic: "X", patient: "K"),  // Smoking Status
        0x001021B0: E11Row(basic: "X", cleanDescriptors: "C"),  // Additional Patient History
        0x001021C0: E11Row(basic: "X", patient: "K"),  // Pregnancy Status
        0x001021D0: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Last Menstrual Date
        0x001021F0: E11Row(basic: "X"),  // Patient's Religious Preference
        0x00102203: E11Row(basic: "X/Z", patient: "K"),  // Patient's Sex Neutered
        0x00102297: E11Row(basic: "X"),  // Responsible Person
        0x00102299: E11Row(basic: "X"),  // Responsible Organization
        0x00104000: E11Row(basic: "X", cleanDescriptors: "C"),  // Patient Comments
        0x00120010: E11Row(basic: "D"),  // Clinical Trial Sponsor Name
        0x00120020: E11Row(basic: "D"),  // Clinical Trial Protocol ID
        0x00120021: E11Row(basic: "Z"),  // Clinical Trial Protocol Name
        0x00120022: E11Row(basic: "X"),  // Issuer of Clinical Trial Protocol ID
        0x00120023: E11Row(basic: "X"),  // Other Clinical Trial Protocol IDs Sequence
        0x00120030: E11Row(basic: "Z", institution: "K"),  // Clinical Trial Site ID
        0x00120031: E11Row(basic: "Z", institution: "K"),  // Clinical Trial Site Name
        0x00120032: E11Row(basic: "X"),  // Issuer of Clinical Trial Site ID
        0x00120040: E11Row(basic: "D"),  // Clinical Trial Subject ID
        0x00120041: E11Row(basic: "X"),  // Issuer of Clinical Trial Subject ID
        0x00120042: E11Row(basic: "D"),  // Clinical Trial Subject Reading ID
        0x00120043: E11Row(basic: "X"),  // Issuer of Clinical Trial Subject Reading ID
        0x00120050: E11Row(basic: "Z"),  // Clinical Trial Time Point ID
        0x00120051: E11Row(basic: "X", cleanDescriptors: "C"),  // Clinical Trial Time Point Description
        0x00120055: E11Row(basic: "X"),  // Issuer of Clinical Trial Time Point ID
        0x00120060: E11Row(basic: "Z", institution: "K"),  // Clinical Trial Coordinating Center Name
        0x00120071: E11Row(basic: "X"),  // Clinical Trial Series ID
        0x00120072: E11Row(basic: "X", cleanDescriptors: "C"),  // Clinical Trial Series Description
        0x00120073: E11Row(basic: "X"),  // Issuer of Clinical Trial Series ID
        0x00120081: E11Row(basic: "D", institution: "K"),  // Clinical Trial Protocol Ethics Committee Name
        0x00120082: E11Row(basic: "X"),  // Clinical Trial Protocol Ethics Committee Approval Number
        0x00120086: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Ethics Committee Approval Effectiveness Start Date
        0x00120087: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Ethics Committee Approval Effectiveness End Date
        0x0014407C: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Calibration Time
        0x0014407E: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Calibration Date
        0x0016002B: E11Row(basic: "X", cleanDescriptors: "C"),  // Maker Note
        0x0016004B: E11Row(basic: "X", cleanDescriptors: "C"),  // Device Setting Description
        0x0016004D: E11Row(basic: "X"),  // Camera Owner Name
        0x0016004E: E11Row(basic: "X", device: "K"),  // Lens Specification
        0x0016004F: E11Row(basic: "X", device: "K"),  // Lens Make
        0x00160050: E11Row(basic: "X", device: "K"),  // Lens Model
        0x00160051: E11Row(basic: "X", device: "K"),  // Lens Serial Number
        0x00160070: E11Row(basic: "X"),  // GPS Version ID
        0x00160071: E11Row(basic: "X"),  // GPS Latitude Ref
        0x00160072: E11Row(basic: "X"),  // GPS Latitude
        0x00160073: E11Row(basic: "X"),  // GPS Longitude Ref
        0x00160074: E11Row(basic: "X"),  // GPS Longitude
        0x00160075: E11Row(basic: "X"),  // GPS Altitude Ref
        0x00160076: E11Row(basic: "X"),  // GPS Altitude
        0x00160077: E11Row(basic: "X"),  // GPS Time Stamp
        0x00160078: E11Row(basic: "X"),  // GPS Satellites
        0x00160079: E11Row(basic: "X"),  // GPS Status
        0x0016007A: E11Row(basic: "X"),  // GPS Measure Mode
        0x0016007B: E11Row(basic: "X"),  // GPS DOP
        0x0016007C: E11Row(basic: "X"),  // GPS Speed Ref
        0x0016007D: E11Row(basic: "X"),  // GPS Speed
        0x0016007E: E11Row(basic: "X"),  // GPS Track Ref
        0x0016007F: E11Row(basic: "X"),  // GPS Track
        0x00160080: E11Row(basic: "X"),  // GPS Img Direction Ref
        0x00160081: E11Row(basic: "X"),  // GPS Img Direction
        0x00160082: E11Row(basic: "X"),  // GPS Map Datum
        0x00160083: E11Row(basic: "X"),  // GPS Dest Latitude Ref
        0x00160084: E11Row(basic: "X"),  // GPS Dest Latitude
        0x00160085: E11Row(basic: "X"),  // GPS Dest Longitude Ref
        0x00160086: E11Row(basic: "X"),  // GPS Dest Longitude
        0x00160087: E11Row(basic: "X"),  // GPS Dest Bearing Ref
        0x00160088: E11Row(basic: "X"),  // GPS Dest Bearing
        0x00160089: E11Row(basic: "X"),  // GPS Dest Distance Ref
        0x0016008A: E11Row(basic: "X"),  // GPS Dest Distance
        0x0016008B: E11Row(basic: "X"),  // GPS Processing Method
        0x0016008C: E11Row(basic: "X"),  // GPS Area Information
        0x0016008D: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // GPS Date Stamp
        0x0016008E: E11Row(basic: "X"),  // GPS Differential
        0x00180010: E11Row(basic: "Z/D", cleanDescriptors: "C"),  // Contrast/Bolus Agent
        0x00180027: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Intervention Drug Stop Time
        0x00180035: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Intervention Drug Start Time
        0x00181000: E11Row(basic: "X/Z/D", device: "K"),  // Device Serial Number
        0x00181002: E11Row(basic: "U", uids: "K", device: "K"),  // Device UID
        0x00181004: E11Row(basic: "X", device: "K"),  // Plate ID
        0x00181005: E11Row(basic: "X", device: "K"),  // Generator ID
        0x00181007: E11Row(basic: "X", device: "K"),  // Cassette ID
        0x00181008: E11Row(basic: "X", device: "K"),  // Gantry ID
        0x00181009: E11Row(basic: "X", device: "K"),  // Unique Device Identifier
        0x0018100A: E11Row(basic: "X", device: "K"),  // UDI Sequence
        0x0018100B: E11Row(basic: "U", uids: "K", device: "K"),  // Manufacturer's Device Class UID
        0x00181010: E11Row(basic: "X", device: "K"),  // Secondary Capture Device ID
        0x00181011: E11Row(basic: "X", device: "K"),  // Hardcopy Creation Device ID
        0x00181012: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Date of Secondary Capture
        0x00181014: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Time of Secondary Capture
        0x00181030: E11Row(basic: "X/D", cleanDescriptors: "C"),  // Protocol Name
        0x00181042: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Contrast/Bolus Start Time
        0x00181043: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Contrast/Bolus Stop Time
        0x00181072: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Start Time
        0x00181073: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Stop Time
        0x00181078: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Start DateTime
        0x00181079: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Stop DateTime
        0x001811BB: E11Row(basic: "D", cleanDescriptors: "C"),  // Acquisition Field Of View Label
        0x00181200: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Date of Last Calibration
        0x00181201: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Time of Last Calibration
        0x00181202: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // DateTime of Last Calibration
        0x00181203: E11Row(basic: "Z", device: "K", fullDates: "K", modifiedDates: "C"),  // Calibration DateTime
        0x00181204: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Date of Manufacture
        0x00181205: E11Row(basic: "X", device: "K", fullDates: "K", modifiedDates: "C"),  // Date of Installation
        0x00181400: E11Row(basic: "X/D", cleanDescriptors: "C"),  // Acquisition Device Processing Description
        0x00182042: E11Row(basic: "U", uids: "K"),  // Target UID
        0x00184000: E11Row(basic: "X", cleanDescriptors: "C"),  // Acquisition Comments
        0x00185011: E11Row(basic: "X", device: "K"),  // Transducer Identification Sequence
        0x0018700A: E11Row(basic: "X/D", device: "K"),  // Detector ID
        0x0018700C: E11Row(basic: "X/D", device: "K", fullDates: "K", modifiedDates: "C"),  // Date of Last Detector Calibration
        0x0018700E: E11Row(basic: "X/D", device: "K", fullDates: "K", modifiedDates: "C"),  // Time of Last Detector Calibration
        0x00189074: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Frame Acquisition DateTime
        0x00189151: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Frame Reference DateTime
        0x00189185: E11Row(basic: "X", cleanDescriptors: "C"),  // Respiratory Motion Compensation Technique Description
        0x00189367: E11Row(basic: "D", device: "K"),  // X-Ray Source ID
        0x00189369: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Source Start DateTime
        0x0018936A: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Source End DateTime
        0x00189371: E11Row(basic: "D", device: "K"),  // X-Ray Detector ID
        0x00189373: E11Row(basic: "X", device: "K"),  // X-Ray Detector Label
        0x0018937B: E11Row(basic: "X", cleanDescriptors: "C"),  // Multi-energy Acquisition Description
        0x0018937F: E11Row(basic: "X", cleanDescriptors: "C"),  // Decomposition Description
        0x00189424: E11Row(basic: "X", cleanDescriptors: "C"),  // Acquisition Protocol Description
        0x00189516: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Start Acquisition DateTime
        0x00189517: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // End Acquisition DateTime
        0x00189623: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Functional Sync Pulse
        0x00189701: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Decay Correction DateTime
        0x00189804: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Exclusion Start DateTime
        0x00189919: E11Row(basic: "Z/D", fullDates: "K", modifiedDates: "C"),  // Instruction Performed DateTime
        0x00189937: E11Row(basic: "X", cleanDescriptors: "C"),  // Requested Series Description
        0x0018A002: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Contribution DateTime
        0x0018A003: E11Row(basic: "X", cleanDescriptors: "C"),  // Contribution Description
        0x0020000D: E11Row(basic: "U", uids: "K"),  // Study Instance UID
        0x0020000E: E11Row(basic: "U", uids: "K"),  // Series Instance UID
        0x00200010: E11Row(basic: "Z"),  // Study ID
        0x00200027: E11Row(basic: "X", cleanDescriptors: "C"),  // Pyramid Label
        0x00200052: E11Row(basic: "U", uids: "K"),  // Frame of Reference UID
        0x00200200: E11Row(basic: "U", uids: "K"),  // Synchronization Frame of Reference UID
        0x00203401: E11Row(basic: "X", device: "K"),  // Modifying Device ID
        0x00203403: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Modified Image Date
        0x00203405: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Modified Image Time
        0x00203406: E11Row(basic: "X"),  // Modified Image Description
        0x00204000: E11Row(basic: "X", cleanDescriptors: "C"),  // Image Comments
        0x00209158: E11Row(basic: "X", cleanDescriptors: "C"),  // Frame Comments
        0x00209161: E11Row(basic: "U", uids: "K"),  // Concatenation UID
        0x00209164: E11Row(basic: "U", uids: "K"),  // Dimension Organization UID
        0x00281199: E11Row(basic: "U", uids: "K"),  // Palette Color Lookup Table UID
        0x00281214: E11Row(basic: "U", uids: "K"),  // Large Palette Color Lookup Table UID
        0x00284000: E11Row(basic: "X"),  // Image Presentation Comments
        0x00320012: E11Row(basic: "X"),  // Study ID Issuer
        0x00320032: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Verified Date
        0x00320033: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Verified Time
        0x00320034: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Read Date
        0x00320035: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Read Time
        0x00321000: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Study Start Date
        0x00321001: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Study Start Time
        0x00321010: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Study Stop Date
        0x00321011: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Study Stop Time
        0x00321020: E11Row(basic: "X", device: "K"),  // Scheduled Study Location
        0x00321021: E11Row(basic: "X", device: "C"),  // Scheduled Study Location AE Title
        0x00321030: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for Study
        0x00321032: E11Row(basic: "X"),  // Requesting Physician
        0x00321033: E11Row(basic: "X", cleanDescriptors: "C"),  // Requesting Service
        0x00321040: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Arrival Date
        0x00321041: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Arrival Time
        0x00321050: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Completion Date
        0x00321051: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Study Completion Time
        0x00321060: E11Row(basic: "X/Z", cleanDescriptors: "C"),  // Requested Procedure Description
        0x00321066: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for Visit
        0x00321067: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for Visit Code Sequence
        0x00321070: E11Row(basic: "X", cleanDescriptors: "C"),  // Requested Contrast Agent
        0x00324000: E11Row(basic: "X", cleanDescriptors: "C"),  // Study Comments
        0x00340001: E11Row(basic: "D"),  // Flow Identifier Sequence
        0x00340002: E11Row(basic: "D"),  // Flow Identifier
        0x00340005: E11Row(basic: "D"),  // Source Identifier
        0x00340007: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Frame Origin Timestamp
        0x00380004: E11Row(basic: "X"),  // Referenced Patient Alias Sequence
        0x00380010: E11Row(basic: "X"),  // Admission ID
        0x00380011: E11Row(basic: "X"),  // Issuer of Admission ID
        0x00380014: E11Row(basic: "X"),  // Issuer of Admission ID Sequence
        0x0038001A: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Admission Date
        0x0038001B: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Admission Time
        0x0038001C: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Discharge Date
        0x0038001D: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Discharge Time
        0x0038001E: E11Row(basic: "X"),  // Scheduled Patient Institution Residence
        0x00380020: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Admitting Date
        0x00380021: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Admitting Time
        0x00380030: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Discharge Date
        0x00380032: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Discharge Time
        0x00380040: E11Row(basic: "X", cleanDescriptors: "C"),  // Discharge Diagnosis Description
        0x00380050: E11Row(basic: "X", patient: "C"),  // Special Needs
        0x00380060: E11Row(basic: "X"),  // Service Episode ID
        0x00380061: E11Row(basic: "X"),  // Issuer of Service Episode ID
        0x00380062: E11Row(basic: "X", cleanDescriptors: "C"),  // Service Episode Description
        0x00380064: E11Row(basic: "X"),  // Issuer of Service Episode ID Sequence
        0x00380300: E11Row(basic: "X"),  // Current Patient Location
        0x00380400: E11Row(basic: "X"),  // Patient's Institution Residence
        0x00380500: E11Row(basic: "X", patient: "C", cleanDescriptors: "C"),  // Patient State
        0x00384000: E11Row(basic: "X", cleanDescriptors: "C"),  // Visit Comments
        0x003A0020: E11Row(basic: "X", cleanDescriptors: "C"),  // Multiplex Group Label
        0x003A0203: E11Row(basic: "X", cleanDescriptors: "C"),  // Channel Label
        0x003A020C: E11Row(basic: "X", cleanDescriptors: "C"),  // Channel Derivation Description
        0x003A0310: E11Row(basic: "U", uids: "K"),  // Multiplex Group UID
        0x003A0314: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Impedance Measurement DateTime
        0x003A0329: E11Row(basic: "X", cleanDescriptors: "C"),  // Waveform Filter Description
        0x003A032B: E11Row(basic: "X", cleanDescriptors: "C"),  // Filter Lookup Table Description
        0x00400001: E11Row(basic: "X", device: "C"),  // Scheduled Station AE Title
        0x00400002: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step Start Date
        0x00400003: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step Start Time
        0x00400004: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step End Date
        0x00400005: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step End Time
        0x00400006: E11Row(basic: "X"),  // Scheduled Performing Physician's Name
        0x00400007: E11Row(basic: "X", cleanDescriptors: "C"),  // Scheduled Procedure Step Description
        0x00400009: E11Row(basic: "X"),  // Scheduled Procedure Step ID
        0x0040000B: E11Row(basic: "X"),  // Scheduled Performing Physician Identification Sequence
        0x00400010: E11Row(basic: "X", device: "K"),  // Scheduled Station Name
        0x00400011: E11Row(basic: "X", device: "K"),  // Scheduled Procedure Step Location
        0x00400012: E11Row(basic: "X", patient: "C"),  // Pre-Medication
        0x00400241: E11Row(basic: "X", device: "C"),  // Performed Station AE Title
        0x00400242: E11Row(basic: "X", device: "K"),  // Performed Station Name
        0x00400243: E11Row(basic: "X"),  // Performed Location
        0x00400244: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step Start Date
        0x00400245: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step Start Time
        0x00400250: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step End Date
        0x00400251: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step End Time
        0x00400253: E11Row(basic: "X"),  // Performed Procedure Step ID
        0x00400254: E11Row(basic: "X", cleanDescriptors: "C"),  // Performed Procedure Step Description
        0x00400275: E11Row(basic: "X", cleanDescriptors: "C"),  // Request Attributes Sequence
        0x00400280: E11Row(basic: "X", cleanDescriptors: "C"),  // Comments on the Performed Procedure Step
        0x00400310: E11Row(basic: "X", cleanDescriptors: "C"),  // Comments on Radiation Dose
        0x0040050A: E11Row(basic: "X"),  // Specimen Accession Number
        0x00400512: E11Row(basic: "D"),  // Container Identifier
        0x00400513: E11Row(basic: "Z"),  // Issuer of the Container Identifier Sequence
        0x0040051A: E11Row(basic: "X", cleanDescriptors: "C"),  // Container Description
        0x00400551: E11Row(basic: "D"),  // Specimen Identifier
        0x00400554: E11Row(basic: "U", uids: "K"),  // Specimen UID
        0x00400555: E11Row(basic: "X/Z", cleanStructuredContent: "C"),  // Acquisition Context Sequence
        0x00400556: E11Row(basic: "X", cleanDescriptors: "C"),  // Acquisition Context Description
        0x00400562: E11Row(basic: "Z"),  // Issuer of the Specimen Identifier Sequence
        0x00400600: E11Row(basic: "X", cleanDescriptors: "C"),  // Specimen Short Description
        0x00400602: E11Row(basic: "X", cleanDescriptors: "C"),  // Specimen Detailed Description
        0x00400610: E11Row(basic: "Z", cleanStructuredContent: "C"),  // Specimen Preparation Sequence
        0x004006FA: E11Row(basic: "X"),  // Slide Identifier
        0x00401001: E11Row(basic: "X"),  // Requested Procedure ID
        0x00401002: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for the Requested Procedure
        0x00401004: E11Row(basic: "X"),  // Patient Transport Arrangements
        0x00401005: E11Row(basic: "X"),  // Requested Procedure Location
        0x0040100A: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for Requested Procedure Code Sequence
        0x00401010: E11Row(basic: "X"),  // Names of Intended Recipients of Results
        0x00401011: E11Row(basic: "X"),  // Intended Recipients of Results Identification Sequence
        0x00401101: E11Row(basic: "D"),  // Person Identification Code Sequence
        0x00401102: E11Row(basic: "X"),  // Person's Address
        0x00401103: E11Row(basic: "X"),  // Person's Telephone Numbers
        0x00401104: E11Row(basic: "X"),  // Person's Telecom Information
        0x00401400: E11Row(basic: "X", cleanDescriptors: "C"),  // Requested Procedure Comments
        0x00402001: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for the Imaging Service Request
        0x00402004: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Issue Date of Imaging Service Request
        0x00402005: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Issue Time of Imaging Service Request
        0x00402008: E11Row(basic: "X"),  // Order Entered By
        0x00402009: E11Row(basic: "X"),  // Order Enterer's Location
        0x00402010: E11Row(basic: "X"),  // Order Callback Phone Number
        0x00402011: E11Row(basic: "X"),  // Order Callback Telecom Information
        0x00402016: E11Row(basic: "Z"),  // Placer Order Number / Imaging Service Request
        0x00402017: E11Row(basic: "Z"),  // Filler Order Number / Imaging Service Request
        0x00402400: E11Row(basic: "X", cleanDescriptors: "C"),  // Imaging Service Request Comments
        0x00403001: E11Row(basic: "X"),  // Confidentiality Constraint on Patient Data Description
        0x00404005: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step Start DateTime
        0x00404008: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step Expiration DateTime
        0x00404010: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Scheduled Procedure Step Modification DateTime
        0x00404011: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Expected Completion DateTime
        0x00404023: E11Row(basic: "U", uids: "K"),  // Referenced General Purpose Scheduled Procedure Step Transaction UID
        0x00404025: E11Row(basic: "X", device: "K"),  // Scheduled Station Name Code Sequence
        0x00404027: E11Row(basic: "X", device: "K"),  // Scheduled Station Geographic Location Code Sequence
        0x00404028: E11Row(basic: "X", device: "K"),  // Performed Station Name Code Sequence
        0x00404030: E11Row(basic: "X", device: "K"),  // Performed Station Geographic Location Code Sequence
        0x00404034: E11Row(basic: "X"),  // Scheduled Human Performers Sequence
        0x00404035: E11Row(basic: "X"),  // Actual Human Performers Sequence
        0x00404036: E11Row(basic: "X"),  // Human Performer's Organization
        0x00404037: E11Row(basic: "X"),  // Human Performer's Name
        0x00404050: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step Start DateTime
        0x00404051: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Performed Procedure Step End DateTime
        0x00404052: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Procedure Step Cancellation DateTime
        0x0040A023: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Findings Group Recording Date (Trial)
        0x0040A024: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Findings Group Recording Time (Trial)
        0x0040A027: E11Row(basic: "D"),  // Verifying Organization
        0x0040A030: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Verification DateTime
        0x0040A032: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Observation DateTime
        0x0040A033: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Observation Start DateTime
        0x0040A034: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Effective Start DateTime
        0x0040A035: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Effective Stop DateTime
        0x0040A073: E11Row(basic: "D"),  // Verifying Observer Sequence
        0x0040A075: E11Row(basic: "D"),  // Verifying Observer Name
        0x0040A078: E11Row(basic: "X"),  // Author Observer Sequence
        0x0040A07A: E11Row(basic: "X"),  // Participant Sequence
        0x0040A07C: E11Row(basic: "X"),  // Custodial Organization Sequence
        0x0040A082: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Participation DateTime
        0x0040A088: E11Row(basic: "Z"),  // Verifying Observer Identification Code Sequence
        0x0040A110: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Date of Document or Verbal Transaction (Trial)
        0x0040A112: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Time of Document Creation or Verbal Transaction (Trial)
        0x0040A120: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // DateTime
        0x0040A121: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Date
        0x0040A122: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Time
        0x0040A123: E11Row(basic: "D"),  // Person Name
        0x0040A124: E11Row(basic: "U"),  // UID
        0x0040A13A: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Referenced DateTime
        0x0040A171: E11Row(basic: "U", uids: "K"),  // Observation UID
        0x0040A172: E11Row(basic: "U", uids: "K"),  // Referenced Observation UID (Trial)
        0x0040A192: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Observation Date (Trial)
        0x0040A193: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Observation Time (Trial)
        0x0040A307: E11Row(basic: "X"),  // Current Observer (Trial)
        0x0040A352: E11Row(basic: "X"),  // Verbal Source (Trial)
        0x0040A353: E11Row(basic: "X"),  // Address (Trial)
        0x0040A354: E11Row(basic: "X"),  // Telephone Number (Trial)
        0x0040A358: E11Row(basic: "X"),  // Verbal Source Identifier Code Sequence (Trial)
        0x0040A402: E11Row(basic: "U", uids: "K"),  // Observation Subject UID (Trial)
        0x0040A730: E11Row(basic: "D", cleanStructuredContent: "C"),  // Content Sequence
        0x0040B020: E11Row(basic: "X/D", cleanStructuredContent: "C"),  // Waveform Annotation Sequence
        0x0040B034: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Annotation DateTime
        0x0040B036: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Segment Definition DateTime
        0x0040B03B: E11Row(basic: "X", cleanDescriptors: "C"),  // Montage Name
        0x0040B03F: E11Row(basic: "X", cleanDescriptors: "C"),  // Montage Channel Label
        0x0040DB06: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Template Version
        0x0040DB07: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Template Local Version
        0x0040DB0C: E11Row(basic: "U", uids: "K"),  // Template Extension Organization UID
        0x0040DB0D: E11Row(basic: "U", uids: "K"),  // Template Extension Creator UID
        0x0040E004: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // HL7 Document Effective Time
        0x00420011: E11Row(basic: "D"),  // Encapsulated Document
        0x00440004: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Approval Status DateTime
        0x0044000B: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Product Expiration DateTime
        0x00440010: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Substance Administration DateTime
        0x00440104: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Assertion DateTime
        0x00440105: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Assertion Expiration DateTime
        0x0050001B: E11Row(basic: "X"),  // Container Component ID
        0x00500020: E11Row(basic: "X", device: "K"),  // Device Description
        0x00500021: E11Row(basic: "X", cleanDescriptors: "C"),  // Long Device Description
        0x00620021: E11Row(basic: "U", uids: "K"),  // Tracking UID
        0x00640003: E11Row(basic: "U", uids: "K"),  // Source Frame of Reference UID
        0x00686226: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Effective DateTime
        0x00686270: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Information Issue DateTime
        0x006A0003: E11Row(basic: "D", uids: "K"),  // Annotation Group UID
        0x006A0005: E11Row(basic: "D", cleanDescriptors: "C"),  // Annotation Group Label
        0x006A0006: E11Row(basic: "X", cleanDescriptors: "C"),  // Annotation Group Description
        0x00700001: E11Row(basic: "D", cleanGraphics: "C"),  // Graphic Annotation Sequence
        0x00700006: E11Row(basic: "D", cleanDescriptors: "C"),  // Unformatted Text Value
        0x00700082: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Presentation Creation Date
        0x00700083: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Presentation Creation Time
        0x00700084: E11Row(basic: "Z/D"),  // Content Creator's Name
        0x00700086: E11Row(basic: "X"),  // Content Creator's Identification Code Sequence
        0x0070031A: E11Row(basic: "U", uids: "K"),  // Fiducial UID
        0x00701101: E11Row(basic: "U", uids: "K"),  // Presentation Display Collection UID
        0x00701102: E11Row(basic: "U", uids: "K"),  // Presentation Sequence Collection UID
        0x0072000A: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Hanging Protocol Creation DateTime
        0x0072005E: E11Row(basic: "D", device: "C"),  // Selector AE Value
        0x0072005F: E11Row(basic: "D", patient: "K"),  // Selector AS Value
        0x00720061: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Selector DA Value
        0x00720063: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Selector DT Value
        0x00720065: E11Row(basic: "D"),  // Selector OB Value
        0x00720066: E11Row(basic: "D", cleanDescriptors: "C"),  // Selector LO Value
        0x00720068: E11Row(basic: "D", cleanDescriptors: "C"),  // Selector LT Value
        0x0072006A: E11Row(basic: "D"),  // Selector PN Value
        0x0072006B: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Selector TM Value
        0x0072006C: E11Row(basic: "D", cleanDescriptors: "C"),  // Selector SH Value
        0x0072006D: E11Row(basic: "D"),  // Selector UN Value
        0x0072006E: E11Row(basic: "D", cleanDescriptors: "C"),  // Selector ST Value
        0x00720070: E11Row(basic: "D", cleanDescriptors: "C"),  // Selector UT Value
        0x00720071: E11Row(basic: "D"),  // Selector UR Value
        0x00741234: E11Row(basic: "X", device: "C"),  // Receiving AE
        0x00741236: E11Row(basic: "X", device: "C"),  // Requesting AE
        0x00880140: E11Row(basic: "U", uids: "K"),  // Storage Media File-set UID
        0x00880200: E11Row(basic: "X"),  // Icon Image Sequence | (see Note 11)
        0x00880904: E11Row(basic: "X"),  // Topic Title
        0x00880906: E11Row(basic: "X"),  // Topic Subject
        0x00880910: E11Row(basic: "X"),  // Topic Author
        0x00880912: E11Row(basic: "X"),  // Topic Keywords
        0x01000420: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // SOP Authorization DateTime
        0x04000100: E11Row(basic: "U"),  // Digital Signature UID
        0x04000105: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Digital Signature DateTime
        0x04000115: E11Row(basic: "D"),  // Certificate of Signer
        0x04000310: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Certified Timestamp
        0x04000402: E11Row(basic: "X"),  // Referenced Digital Signature Sequence
        0x04000403: E11Row(basic: "X"),  // Referenced SOP Instance MAC Sequence
        0x04000404: E11Row(basic: "X"),  // MAC
        0x04000550: E11Row(basic: "X"),  // Modified Attributes Sequence
        0x04000551: E11Row(basic: "X"),  // Nonconforming Modified Attributes Sequence
        0x04000552: E11Row(basic: "X"),  // Nonconforming Data Element Value
        0x04000561: E11Row(basic: "X"),  // Original Attributes Sequence
        0x04000562: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Attribute Modification DateTime
        0x04000563: E11Row(basic: "D", device: "K"),  // Modifying System
        0x04000564: E11Row(basic: "Z", institution: "K"),  // Source of Previous Values
        0x04000565: E11Row(basic: "D", cleanDescriptors: "C"),  // Reason for the Attribute Modification
        0x04000600: E11Row(basic: "X"),  // Instance Origin Status
        0x20300020: E11Row(basic: "X"),  // Text String
        0x21000040: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Creation Date
        0x21000050: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Creation Time
        0x21000070: E11Row(basic: "X", device: "C"),  // Originator
        0x21000140: E11Row(basic: "D", device: "C"),  // Destination AE
        0x22000002: E11Row(basic: "X/Z", cleanDescriptors: "C"),  // Label Text
        0x22000005: E11Row(basic: "X/Z"),  // Barcode Value
        0x30020121: E11Row(basic: "X", cleanDescriptors: "C"),  // Position Acquisition Template Name
        0x30020123: E11Row(basic: "X", cleanDescriptors: "C"),  // Position Acquisition Template Description
        0x30060002: E11Row(basic: "D", cleanDescriptors: "C"),  // Structure Set Label
        0x30060004: E11Row(basic: "X", cleanDescriptors: "C"),  // Structure Set Name
        0x30060006: E11Row(basic: "X", cleanDescriptors: "C"),  // Structure Set Description
        0x30060008: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Structure Set Date
        0x30060009: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Structure Set Time
        0x30060024: E11Row(basic: "U", uids: "K"),  // Referenced Frame of Reference UID
        0x30060026: E11Row(basic: "Z", cleanDescriptors: "C"),  // ROI Name
        0x30060028: E11Row(basic: "X", cleanDescriptors: "C"),  // ROI Description
        0x3006002D: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // ROI DateTime
        0x3006002E: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // ROI Observation DateTime
        0x30060038: E11Row(basic: "X", cleanDescriptors: "C"),  // ROI Generation Description
        0x3006004D: E11Row(basic: "X"),  // ROI Creator Sequence
        0x3006004E: E11Row(basic: "X"),  // ROI Interpreter Sequence
        0x30060085: E11Row(basic: "X", cleanDescriptors: "C"),  // ROI Observation Label
        0x30060088: E11Row(basic: "X", cleanDescriptors: "C"),  // ROI Observation Description
        0x300600A6: E11Row(basic: "Z"),  // ROI Interpreter
        0x300600C2: E11Row(basic: "U", uids: "K"),  // Related Frame of Reference UID
        0x30080024: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Treatment Control Point Date
        0x30080025: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Treatment Control Point Time
        0x30080054: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // First Treatment Date
        0x30080056: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Most Recent Treatment Date
        0x30080105: E11Row(basic: "X/Z", device: "K"),  // Source Serial Number
        0x30080162: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Safe Position Exit Date
        0x30080164: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Safe Position Exit Time
        0x30080166: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Safe Position Return Date
        0x30080168: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Safe Position Return Time
        0x30080250: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Treatment Date
        0x30080251: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Treatment Time
        0x300A0002: E11Row(basic: "D", cleanDescriptors: "C"),  // RT Plan Label
        0x300A0003: E11Row(basic: "X", cleanDescriptors: "C"),  // RT Plan Name
        0x300A0004: E11Row(basic: "X", cleanDescriptors: "C"),  // RT Plan Description
        0x300A0006: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // RT Plan Date
        0x300A0007: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // RT Plan Time
        0x300A000B: E11Row(basic: "X", cleanDescriptors: "C"),  // Treatment Sites
        0x300A000E: E11Row(basic: "X", cleanDescriptors: "C"),  // Prescription Description
        0x300A0013: E11Row(basic: "U", uids: "K"),  // Dose Reference UID
        0x300A0016: E11Row(basic: "X", cleanDescriptors: "C"),  // Dose Reference Description
        0x300A0054: E11Row(basic: "U", uids: "K"),  // Table Top Position Alignment UID
        0x300A0072: E11Row(basic: "X", cleanDescriptors: "C"),  // Fraction Group Description
        0x300A0083: E11Row(basic: "U", uids: "K"),  // Referenced Dose Reference UID
        0x300A00B2: E11Row(basic: "X/Z", device: "K"),  // Treatment Machine Name
        0x300A00C3: E11Row(basic: "X", cleanDescriptors: "C"),  // Beam Description
        0x300A00DD: E11Row(basic: "X", cleanDescriptors: "C"),  // Bolus Description
        0x300A0196: E11Row(basic: "X", cleanDescriptors: "C"),  // Fixation Device Description
        0x300A01A6: E11Row(basic: "X", cleanDescriptors: "C"),  // Shielding Device Description
        0x300A01B2: E11Row(basic: "X", cleanDescriptors: "C"),  // Setup Technique Description
        0x300A0216: E11Row(basic: "X", device: "K"),  // Source Manufacturer
        0x300A022C: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Source Strength Reference Date
        0x300A022E: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Source Strength Reference Time
        0x300A02EB: E11Row(basic: "X", cleanDescriptors: "C"),  // Compensator Description
        0x300A0608: E11Row(basic: "D", cleanDescriptors: "C"),  // Treatment Position Group Label
        0x300A0609: E11Row(basic: "U", uids: "K"),  // Treatment Position Group UID
        0x300A0611: E11Row(basic: "Z"),  // RT Accessory Holder Slot ID
        0x300A0615: E11Row(basic: "Z"),  // RT Accessory Device Slot ID
        0x300A0619: E11Row(basic: "D", cleanDescriptors: "C"),  // Radiation Dose Identification Label
        0x300A0623: E11Row(basic: "D", cleanDescriptors: "C"),  // Radiation Dose In-Vivo Measurement Label
        0x300A062A: E11Row(basic: "D", cleanDescriptors: "C"),  // RT Tolerance Set Label
        0x300A0650: E11Row(basic: "U", uids: "K"),  // Patient Setup UID
        0x300A0676: E11Row(basic: "X", cleanDescriptors: "C"),  // Equipment Frame of Reference Description
        0x300A067C: E11Row(basic: "D", cleanDescriptors: "C"),  // Radiation Generation Mode Label
        0x300A067D: E11Row(basic: "Z", cleanDescriptors: "C"),  // Radiation Generation Mode Description
        0x300A0700: E11Row(basic: "U", uids: "K"),  // Treatment Session UID
        0x300A0734: E11Row(basic: "D", cleanDescriptors: "C"),  // Treatment Tolerance Violation Description
        0x300A0736: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Treatment Tolerance Violation DateTime
        0x300A073A: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Recorded RT Control Point DateTime
        0x300A0741: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Interlock DateTime
        0x300A0742: E11Row(basic: "D", cleanDescriptors: "C"),  // Interlock Description
        0x300A0760: E11Row(basic: "D", fullDates: "K", modifiedDates: "C"),  // Override DateTime
        0x300A0783: E11Row(basic: "D", cleanDescriptors: "C"),  // Interlock Origin Description
        0x300A0785: E11Row(basic: "U", uids: "K"),  // Referenced Treatment Position Group UID
        0x300A078E: E11Row(basic: "X", cleanDescriptors: "C"),  // Patient Treatment Preparation Procedure Parameter Description
        0x300A0792: E11Row(basic: "X", cleanDescriptors: "C"),  // Patient Treatment Preparation Method Description
        0x300A0794: E11Row(basic: "X", cleanDescriptors: "C"),  // Patient Setup Photo Description
        0x300A079A: E11Row(basic: "X", cleanDescriptors: "C"),  // Displacement Reference Label
        0x300C0113: E11Row(basic: "X", cleanDescriptors: "C"),  // Reason for Omission Description
        0x300C0127: E11Row(basic: "D", device: "K", fullDates: "K", modifiedDates: "C"),  // Beam Hold Transition DateTime
        0x300E0004: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Review Date
        0x300E0005: E11Row(basic: "Z", fullDates: "K", modifiedDates: "C"),  // Review Time
        0x300E0008: E11Row(basic: "X/Z"),  // Reviewer Name
        0x30100006: E11Row(basic: "U", uids: "K"),  // Conceptual Volume UID
        0x3010000B: E11Row(basic: "U", uids: "K"),  // Referenced Conceptual Volume UID
        0x3010000F: E11Row(basic: "Z", cleanDescriptors: "C"),  // Conceptual Volume Combination Description
        0x30100013: E11Row(basic: "U", uids: "K"),  // Constituent Conceptual Volume UID
        0x30100015: E11Row(basic: "U", uids: "K"),  // Source Conceptual Volume UID
        0x30100017: E11Row(basic: "Z", cleanDescriptors: "C"),  // Conceptual Volume Description
        0x3010001B: E11Row(basic: "Z"),  // Device Alternate Identifier
        0x3010002D: E11Row(basic: "D", device: "K"),  // Device Label
        0x30100031: E11Row(basic: "U", uids: "K"),  // Referenced Fiducials UID
        0x30100033: E11Row(basic: "D", cleanDescriptors: "C"),  // User Content Label
        0x30100034: E11Row(basic: "D", cleanDescriptors: "C"),  // User Content Long Label
        0x30100035: E11Row(basic: "D", cleanDescriptors: "C"),  // Entity Label
        0x30100036: E11Row(basic: "X", cleanDescriptors: "C"),  // Entity Name
        0x30100037: E11Row(basic: "X", cleanDescriptors: "C"),  // Entity Description
        0x30100038: E11Row(basic: "D", cleanDescriptors: "C"),  // Entity Long Label
        0x3010003B: E11Row(basic: "U", uids: "K"),  // RT Treatment Phase UID
        0x30100043: E11Row(basic: "Z", device: "K"),  // Manufacturer's Device Identifier
        0x3010004C: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Intended Phase Start Date
        0x3010004D: E11Row(basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Intended Phase End Date
        0x30100054: E11Row(basic: "D", cleanDescriptors: "C"),  // RT Prescription Label
        0x30100056: E11Row(basic: "X/D", cleanDescriptors: "C"),  // RT Treatment Approach Label
        0x3010005A: E11Row(basic: "Z", cleanDescriptors: "C"),  // RT Physician Intent Narrative
        0x3010005C: E11Row(basic: "Z", cleanDescriptors: "C"),  // Reason for Superseding
        0x30100061: E11Row(basic: "X", cleanDescriptors: "C"),  // Prior Treatment Dose Description
        0x3010006E: E11Row(basic: "U", uids: "K"),  // Dosimetric Objective UID
        0x3010006F: E11Row(basic: "U", uids: "K"),  // Referenced Dosimetric Objective UID
        0x30100077: E11Row(basic: "X/D", cleanDescriptors: "C"),  // Treatment Site
        0x3010007A: E11Row(basic: "Z", cleanDescriptors: "C"),  // Treatment Technique Notes
        0x3010007B: E11Row(basic: "Z", cleanDescriptors: "C"),  // Prescription Notes
        0x3010007F: E11Row(basic: "Z", cleanDescriptors: "C"),  // Fractionation Notes
        0x30100081: E11Row(basic: "Z", cleanDescriptors: "C"),  // Prescription Notes Sequence
        0x30100085: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Intended Fraction Start Time
        0x40000010: E11Row(basic: "X"),  // Arbitrary
        0x40004000: E11Row(basic: "X"),  // Text Comments
        0x40080040: E11Row(basic: "X"),  // Results ID
        0x40080042: E11Row(basic: "X"),  // Results ID Issuer
        0x40080100: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Recorded Date
        0x40080101: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Recorded Time
        0x40080102: E11Row(basic: "X"),  // Interpretation Recorder
        0x40080108: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Transcription Date
        0x40080109: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Transcription Time
        0x4008010A: E11Row(basic: "X"),  // Interpretation Transcriber
        0x4008010B: E11Row(basic: "X", cleanDescriptors: "C"),  // Interpretation Text
        0x4008010C: E11Row(basic: "X"),  // Interpretation Author
        0x40080111: E11Row(basic: "X"),  // Interpretation Approver Sequence
        0x40080112: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Approval Date
        0x40080113: E11Row(basic: "X", fullDates: "K", modifiedDates: "C"),  // Interpretation Approval Time
        0x40080114: E11Row(basic: "X"),  // Physician Approving Interpretation
        0x40080115: E11Row(basic: "X", cleanDescriptors: "C"),  // Interpretation Diagnosis Description
        0x40080118: E11Row(basic: "X"),  // Results Distribution List Sequence
        0x40080119: E11Row(basic: "X"),  // Distribution Name
        0x4008011A: E11Row(basic: "X"),  // Distribution Address
        0x40080200: E11Row(basic: "X"),  // Interpretation ID
        0x40080202: E11Row(basic: "X"),  // Interpretation ID Issuer
        0x40080300: E11Row(basic: "X", cleanDescriptors: "C"),  // Impressions
        0x40084000: E11Row(basic: "X", cleanDescriptors: "C"),  // Results Comments
        0xFFFAFFFA: E11Row(basic: "X"),  // Digital Signatures Sequence
        0xFFFCFFFC: E11Row(basic: "X"),  // Data Set Trailing Padding
    ]
}
