// ConfidentialityProfileStructuredContent.swift
// DICOMKit
//
// GENERATED by Scripts/generate_confidentiality_profile.py from DICOM PS3.15 2026a - Security and System Management Profiles,
// Table E.3.4-1 (211 rows), and DICOM PS3.16 2026a - Content Mapping Resource Table O-1 (the SNOMED IDs of its SCT
// rows: 33 retired-code keys). Do not hand-edit: fix the generator and regenerate.
//
// NEMA-verified: 2026a, checked 2026-10-01 — every row of PS3.15 2026a Table E.3.4-1 Clean Structured Content Option Content Item Concept Name Codes (211: concept name, Value Type, Basic Profile action and the 7 option columns), generated from the DocBook, plus the retired SRT / SNM3 / 99SDM codes of its SCT rows from PS3.16 2026a Table O-1 (E.3.4) (D159); `generate_confidentiality_profile.py --check` re-verifies it.

extension ConfidentialityProfile {
    /// One row of PS3.15 Table E.3.4-1: the Basic Profile action for a Content Item with this
    /// Concept Name and Value Type and, per option, the action the option substitutes
    /// ("K" keep, "C" clean), as the table writes them.
    struct E341Row: Sendable, Equatable {
        let meaning: String
        let basic: String
        var uids: String? = nil
        var device: String? = nil
        var institution: String? = nil
        var patient: String? = nil
        var fullDates: String? = nil
        var modifiedDates: String? = nil
        var cleanDescriptors: String? = nil
    }

    /// Table E.3.4-1, keyed "<Coding Scheme Designator>|<Code Value>|<Value Type>".
    static let structuredContentRows: [String: E341Row] = [
        "99SDM|DD-60002|TEXT": E341Row(meaning: "Complication of Procedure", basic: "X", cleanDescriptors: "C"),  // Complication of Procedure (retired 99SDM DD-60002 = SCT 116224001)
        "99SDM|DF-0068E|DATETIME": E341Row(meaning: "Anesthesia Start Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Start Time (retired 99SDM DF-0068E = SCT 398325003)
        "99SDM|DF-0070B|DATETIME": E341Row(meaning: "Anesthesia Finish Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Finish Time (retired 99SDM DF-0070B = SCT 398164008)
        "99SDM|F-00033|TEXT": E341Row(meaning: "ECG Finding", basic: "X/D", cleanDescriptors: "C"),  // ECG Finding (retired 99SDM F-00033 = SCT 271921002)
        "99SDM|F-02455|TEXT": E341Row(meaning: "Social History", basic: "X", cleanDescriptors: "C"),  // Social History (retired 99SDM F-02455 = SCT 160476009)
        "99SDM|G-C0E3|TEXT": E341Row(meaning: "Finding Site", basic: "D", cleanDescriptors: "C"),  // Finding Site (retired 99SDM G-C0E3 = SCT 363698007)
        "99SDM|G-D320|DATETIME": E341Row(meaning: "Stop DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Stop DateTime (retired 99SDM G-D320 = SCT 397898000)
        "99SDM|G-D321|DATETIME": E341Row(meaning: "Start DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Start DateTime (retired 99SDM G-D321 = SCT 398201009)
        "99SDM|PA-30029|TEXT": E341Row(meaning: "Administration of radiopharmaceutical", basic: "D", cleanDescriptors: "C"),  // Administration of radiopharmaceutical (retired 99SDM PA-30029 = SCT 440252007)
        "99SDM|R-42B89|COMPOSITE": E341Row(meaning: "Clinical Report", basic: "X", uids: "K"),  // Clinical Report (retired 99SDM R-42B89 = SCT 371524004)
        "99SDM|R-42B89|TEXT": E341Row(meaning: "Clinical Report", basic: "X", cleanDescriptors: "C"),  // Clinical Report (retired 99SDM R-42B89 = SCT 371524004)
        "DCM|109054|TEXT": E341Row(meaning: "Patient State", basic: "X", cleanDescriptors: "C"),  // Patient State
        "DCM|109056|TEXT": E341Row(meaning: "Stress Protocol", basic: "X", cleanDescriptors: "C"),  // Stress Protocol
        "DCM|110119|TEXT": E341Row(meaning: "Station AE Title", basic: "X", device: "K"),  // Station AE Title
        "DCM|110180|UIDREF": E341Row(meaning: "Study Instance UID", basic: "D", uids: "K"),  // Study Instance UID
        "DCM|110190|TEXT": E341Row(meaning: "Issuer of Identifier", basic: "X"),  // Issuer of Identifier
        "DCM|111018|DATE": E341Row(meaning: "Content Date", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Content Date
        "DCM|111019|TIME": E341Row(meaning: "Content Time", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Content Time
        "DCM|111021|TEXT": E341Row(meaning: "Description of Change", basic: "X", cleanDescriptors: "C"),  // Description of Change
        "DCM|111033|TEXT": E341Row(meaning: "Impression Description", basic: "D", cleanDescriptors: "C"),  // Impression Description
        "DCM|111040|COMPOSITE": E341Row(meaning: "Original Source", basic: "D", uids: "K"),  // Original Source
        "DCM|111054|DATE": E341Row(meaning: "Recommended Follow-up Date", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Recommended Follow-up Date
        "DCM|111058|TEXT": E341Row(meaning: "Selected Region Description", basic: "D", cleanDescriptors: "C"),  // Selected Region Description
        "DCM|111060|DATE": E341Row(meaning: "Study Date", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Study Date
        "DCM|111061|TIME": E341Row(meaning: "Study Time", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Study Time
        "DCM|111469|DATETIME": E341Row(meaning: "Sampling DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Sampling DateTime
        "DCM|111516|TEXT": E341Row(meaning: "Medication Type", basic: "X", cleanDescriptors: "C"),  // Medication Type
        "DCM|111526|DATETIME": E341Row(meaning: "DateTime Started", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // DateTime Started
        "DCM|111527|DATETIME": E341Row(meaning: "DateTime Ended", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime Ended
        "DCM|111535|DATETIME": E341Row(meaning: "DateTime problem observed", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime problem observed
        "DCM|111536|DATETIME": E341Row(meaning: "DateTime of last evaluation", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime of last evaluation
        "DCM|111700|TEXT": E341Row(meaning: "Specimen Container Identifier", basic: "X"),  // Specimen Container Identifier
        "DCM|111702|DATETIME": E341Row(meaning: "DateTime of processing", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime of processing
        "DCM|111703|TEXT": E341Row(meaning: "Processing step description", basic: "X", cleanDescriptors: "C"),  // Processing step description
        "DCM|111705|TEXT": E341Row(meaning: "Parent Specimen Identifier", basic: "D"),  // Parent Specimen Identifier
        "DCM|111706|TEXT": E341Row(meaning: "Issuer of Parent Specimen Identifier", basic: "X"),  // Issuer of Parent Specimen Identifier
        "DCM|111724|TEXT": E341Row(meaning: "Issuer of Specimen Identifier", basic: "X"),  // Issuer of Specimen Identifier
        "DCM|112002|UIDREF": E341Row(meaning: "Series Instance UID", basic: "D", uids: "K"),  // Series Instance UID
        "DCM|112040|UIDREF": E341Row(meaning: "Tracking Unique Identifier", basic: "D", uids: "K"),  // Tracking Unique Identifier
        "DCM|112050|TEXT": E341Row(meaning: "Anatomic Identifier", basic: "X", cleanDescriptors: "C"),  // Anatomic Identifier
        "DCM|112227|UIDREF": E341Row(meaning: "Frame of Reference UID", basic: "X/D", uids: "K"),  // Frame of Reference UID
        "DCM|112229|IMAGE": E341Row(meaning: "Identifying Segment", basic: "D", uids: "K"),  // Identifying Segment
        "DCM|112347|TEXT": E341Row(meaning: "Component ID", basic: "D"),  // Component ID
        "DCM|112351|TEXT": E341Row(meaning: "Mating Feature Set ID", basic: "D"),  // Mating Feature Set ID
        "DCM|112352|TEXT": E341Row(meaning: "Mating Feature ID", basic: "D"),  // Mating Feature ID
        "DCM|112353|COMPOSITE": E341Row(meaning: "Spatial Registration", basic: "X", uids: "K"),  // Spatial Registration
        "DCM|112354|IMAGE": E341Row(meaning: "Patient Image", basic: "X", uids: "K"),  // Patient Image
        "DCM|112356|UIDREF": E341Row(meaning: "User Selected Fiducial", basic: "D", uids: "K"),  // User Selected Fiducial
        "DCM|112357|UIDREF": E341Row(meaning: "Derived Fiducial", basic: "D", uids: "K"),  // Derived Fiducial
        "DCM|112359|COMPOSITE": E341Row(meaning: "Supporting Information", basic: "X", uids: "K"),  // Supporting Information
        "DCM|112361|COMPOSITE": E341Row(meaning: "Patient Data Used During Planning", basic: "X", uids: "K"),  // Patient Data Used During Planning
        "DCM|112363|TEXT": E341Row(meaning: "Degree of Freedom ID", basic: "D"),  // Degree of Freedom ID
        "DCM|112364|COMPOSITE": E341Row(meaning: "Related Patient Data Not Used During Planning", basic: "X", uids: "K"),  // Related Patient Data Not Used During Planning
        "DCM|112366|COMPOSITE": E341Row(meaning: "Implant Assembly Template", basic: "X", uids: "K"),  // Implant Assembly Template
        "DCM|112371|COMPOSITE": E341Row(meaning: "Manufacturer Implant Template", basic: "D", uids: "K"),  // Manufacturer Implant Template
        "DCM|112372|COMPOSITE": E341Row(meaning: "Derived Planning Images", basic: "X", uids: "K"),  // Derived Planning Images
        "DCM|112373|COMPOSITE": E341Row(meaning: "Derived Planning Data", basic: "X", uids: "K"),  // Derived Planning Data
        "DCM|113012|TEXT": E341Row(meaning: "Key Object Description", basic: "X", cleanDescriptors: "C"),  // Key Object Description
        "DCM|113503|UIDREF": E341Row(meaning: "Radiopharmaceutical Administration Event UID", basic: "D", uids: "K"),  // Radiopharmaceutical Administration Event UID
        "DCM|113511|TEXT": E341Row(meaning: "Radiopharmaceutical Dispense Unit Identifier", basic: "X"),  // Radiopharmaceutical Dispense Unit Identifier
        "DCM|113512|TEXT": E341Row(meaning: "Radiopharmaceutical Lot Identifier", basic: "X"),  // Radiopharmaceutical Lot Identifier
        "DCM|113513|TEXT": E341Row(meaning: "Reagent Vial Identifier", basic: "X"),  // Reagent Vial Identifier
        "DCM|113514|TEXT": E341Row(meaning: "Radionuclide Identifier", basic: "X"),  // Radionuclide Identifier
        "DCM|113516|TEXT": E341Row(meaning: "Prescription Identifier", basic: "X"),  // Prescription Identifier
        "DCM|113552|TEXT": E341Row(meaning: "Recent Physical Activity", basic: "X", cleanDescriptors: "C"),  // Recent Physical Activity
        "DCM|113605|TEXT": E341Row(meaning: "Irradiation Event Label", basic: "X"),  // Irradiation Event Label
        "DCM|113701|COMPOSITE": E341Row(meaning: "X-Ray Radiation Dose Report", basic: "X", uids: "K"),  // X-Ray Radiation Dose Report
        "DCM|113720|TEXT": E341Row(meaning: "Calibration Protocol", basic: "X", cleanDescriptors: "C"),  // Calibration Protocol
        "DCM|113723|DATETIME": E341Row(meaning: "Calibration DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Calibration DateTime
        "DCM|113724|TEXT": E341Row(meaning: "Calibration Responsible Party", basic: "D", cleanDescriptors: "C"),  // Calibration Responsible Party
        "DCM|113769|UIDREF": E341Row(meaning: "Irradiation Event UID", basic: "D", uids: "K"),  // Irradiation Event UID
        "DCM|113795|IMAGE": E341Row(meaning: "Acquired Image", basic: "D", uids: "K"),  // Acquired Image
        "DCM|113809|DATETIME": E341Row(meaning: "Start of X-Ray Irradiation", basic: "D", fullDates: "K", modifiedDates: "C"),  // Start of X-Ray Irradiation
        "DCM|113810|DATETIME": E341Row(meaning: "End of X-Ray Irradiation", basic: "D", fullDates: "K", modifiedDates: "C"),  // End of X-Ray Irradiation
        "DCM|113815|TEXT": E341Row(meaning: "Patient Model", basic: "D", cleanDescriptors: "C"),  // Patient Model
        "DCM|113832|TEXT": E341Row(meaning: "Identification of the X-Ray Source", basic: "D", device: "K"),  // Identification of the X-Ray Source
        "DCM|113850|PNAME": E341Row(meaning: "Irradiation Authorizing", basic: "D"),  // Irradiation Authorizing
        "DCM|113870|PNAME": E341Row(meaning: "Person Name", basic: "D"),  // Person Name
        "DCM|113871|TEXT": E341Row(meaning: "Person ID", basic: "X"),  // Person ID
        "DCM|113872|TEXT": E341Row(meaning: "Person ID Issuer", basic: "X"),  // Person ID Issuer
        "DCM|113873|TEXT": E341Row(meaning: "Organization Name", basic: "X", institution: "K"),  // Organization Name
        "DCM|113877|TEXT": E341Row(meaning: "Device Name", basic: "X", device: "K"),  // Device Name
        "DCM|113880|TEXT": E341Row(meaning: "Device Serial Number", basic: "X/D", device: "K"),  // Device Serial Number
        "DCM|113907|TEXT": E341Row(meaning: "Reason for Proceeding", basic: "X", cleanDescriptors: "C"),  // Reason for Proceeding
        "DCM|113985|UIDREF": E341Row(meaning: "Series or Instance used for Water Equivalent Diameter estimation", basic: "D", uids: "K"),  // Series or Instance used for Water Equivalent Diameter estimation
        "DCM|120999|TEXT": E341Row(meaning: "Device Description", basic: "X", device: "K"),  // Device Description
        "DCM|121000|CONTAINER": E341Row(meaning: "Unique Device Identifiers", basic: "X", device: "K"),  // Unique Device Identifiers
        "DCM|121002|COMPOSITE": E341Row(meaning: "Quoted Source", basic: "D", uids: "K"),  // Quoted Source
        "DCM|121008|PNAME": E341Row(meaning: "Person Observer Name", basic: "D"),  // Person Observer Name
        "DCM|121009|TEXT": E341Row(meaning: "Person Observer's Organization Name", basic: "X", institution: "K"),  // Person Observer's Organization Name
        "DCM|121012|UIDREF": E341Row(meaning: "Device Observer UID", basic: "X/D", uids: "K", device: "K"),  // Device Observer UID
        "DCM|121013|TEXT": E341Row(meaning: "Device Observer Name", basic: "X", device: "K"),  // Device Observer Name
        "DCM|121016|TEXT": E341Row(meaning: "Device Observer Serial Number", basic: "X", device: "K"),  // Device Observer Serial Number
        "DCM|121017|TEXT": E341Row(meaning: "Device Observer Physical Location During Observation", basic: "X", institution: "K"),  // Device Observer Physical Location During Observation
        "DCM|121018|UIDREF": E341Row(meaning: "Procedure Study Instance UID", basic: "X", uids: "K"),  // Procedure Study Instance UID
        "DCM|121019|UIDREF": E341Row(meaning: "Procedure Study Component UID", basic: "X", uids: "K"),  // Procedure Study Component UID
        "DCM|121020|TEXT": E341Row(meaning: "Placer Number", basic: "X"),  // Placer Number
        "DCM|121021|TEXT": E341Row(meaning: "Filler Number", basic: "X"),  // Filler Number
        "DCM|121022|TEXT": E341Row(meaning: "Accession Number", basic: "X"),  // Accession Number
        "DCM|121028|UIDREF": E341Row(meaning: "Subject UID", basic: "X", uids: "K"),  // Subject UID
        "DCM|121029|PNAME": E341Row(meaning: "Subject Name", basic: "D"),  // Subject Name
        "DCM|121030|TEXT": E341Row(meaning: "Subject ID", basic: "X/D"),  // Subject ID
        "DCM|121031|DATE": E341Row(meaning: "Subject Birth Date", basic: "X"),  // Subject Birth Date
        "DCM|121032|CODE": E341Row(meaning: "Subject Sex", basic: "X", patient: "K"),  // Subject Sex
        "DCM|121033|NUM": E341Row(meaning: "Subject Age", basic: "X", patient: "K"),  // Subject Age
        "DCM|121036|PNAME": E341Row(meaning: "Mother of fetus", basic: "X"),  // Mother of fetus
        "DCM|121039|UIDREF": E341Row(meaning: "Specimen UID", basic: "X", uids: "K"),  // Specimen UID
        "DCM|121041|TEXT": E341Row(meaning: "Specimen Identifier", basic: "X"),  // Specimen Identifier
        "DCM|121065|TEXT": E341Row(meaning: "Procedure Description", basic: "X/D", cleanDescriptors: "C"),  // Procedure Description
        "DCM|121071|TEXT": E341Row(meaning: "Finding", basic: "X/D", cleanDescriptors: "C"),  // Finding
        "DCM|121075|TEXT": E341Row(meaning: "Recommendation", basic: "X", cleanDescriptors: "C"),  // Recommendation
        "DCM|121077|TEXT": E341Row(meaning: "Conclusion", basic: "X", cleanDescriptors: "C"),  // Conclusion
        "DCM|121080|IMAGE": E341Row(meaning: "Best illustration of finding", basic: "X", uids: "K"),  // Best illustration of finding
        "DCM|121080|WAVEFORM": E341Row(meaning: "Best illustration of finding", basic: "X", uids: "K"),  // Best illustration of finding
        "DCM|121088|PNAME": E341Row(meaning: "Fellow", basic: "X"),  // Fellow
        "DCM|121106|TEXT": E341Row(meaning: "Comment", basic: "X", cleanDescriptors: "C"),  // Comment
        "DCM|121110|TEXT": E341Row(meaning: "Patient Presentation", basic: "X", cleanDescriptors: "C"),  // Patient Presentation
        "DCM|121111|TEXT": E341Row(meaning: "Summary", basic: "X", cleanDescriptors: "C"),  // Summary
        "DCM|121112|IMAGE": E341Row(meaning: "Source of Measurement", basic: "D", uids: "K"),  // Source of Measurement
        "DCM|121112|WAVEFORM": E341Row(meaning: "Source of Measurement", basic: "X", uids: "K"),  // Source of Measurement
        "DCM|121114|PNAME": E341Row(meaning: "Performing Physician", basic: "D"),  // Performing Physician
        "DCM|121120|COMPOSITE": E341Row(meaning: "Cath Lab Procedure Log", basic: "X", uids: "K"),  // Cath Lab Procedure Log
        "DCM|121121|TEXT": E341Row(meaning: "Room Identification", basic: "X"),  // Room Identification
        "DCM|121122|TEXT": E341Row(meaning: "Equipment Identification", basic: "X", device: "K", cleanDescriptors: "C"),  // Equipment Identification
        "DCM|121124|TEXT": E341Row(meaning: "Procedure Action ID", basic: "X/D"),  // Procedure Action ID
        "DCM|121125|DATETIME": E341Row(meaning: "DateTime of Recording of Log Entry", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime of Recording of Log Entry
        "DCM|121126|UIDREF": E341Row(meaning: "Performed Procedure Step SOP Instance UID", basic: "D", uids: "K"),  // Performed Procedure Step SOP Instance UID
        "DCM|121138|IMAGE": E341Row(meaning: "Image Acquired", basic: "D", uids: "K"),  // Image Acquired
        "DCM|121143|WAVEFORM": E341Row(meaning: "Waveform Acquired", basic: "D", uids: "K"),  // Waveform Acquired
        "DCM|121145|TEXT": E341Row(meaning: "Description of Material", basic: "X", cleanDescriptors: "C"),  // Description of Material
        "DCM|121152|PNAME": E341Row(meaning: "Person administering drug/contrast", basic: "X"),  // Person administering drug/contrast
        "DCM|121154|TEXT": E341Row(meaning: "Intervention attempt identifier", basic: "D"),  // Intervention attempt identifier
        "DCM|121173|TEXT": E341Row(meaning: "Physician Note", basic: "X", cleanDescriptors: "C"),  // Physician Note
        "DCM|121191|IMAGE": E341Row(meaning: "Referenced Segment", basic: "X/D", uids: "K"),  // Referenced Segment
        "DCM|121193|TEXT": E341Row(meaning: "Device Subject Name", basic: "D", device: "K"),  // Device Subject Name
        "DCM|121196|TEXT": E341Row(meaning: "Device Subject Serial Number", basic: "X", device: "K"),  // Device Subject Serial Number
        "DCM|121197|TEXT": E341Row(meaning: "Device Subject Physical Location during observation", basic: "X", institution: "K"),  // Device Subject Physical Location during observation
        "DCM|121198|UIDREF": E341Row(meaning: "Device Subject UID", basic: "X", uids: "K", device: "K"),  // Device Subject UID
        "DCM|121200|IMAGE": E341Row(meaning: "Illustration of ROI", basic: "X", uids: "K"),  // Illustration of ROI
        "DCM|121214|IMAGE": E341Row(meaning: "Referenced Segmentation Frame", basic: "D", uids: "K"),  // Referenced Segmentation Frame
        "DCM|121232|UIDREF": E341Row(meaning: "Source series for segmentation", basic: "D", uids: "K"),  // Source series for segmentation
        "DCM|121233|IMAGE": E341Row(meaning: "Source image for segmentation", basic: "D", uids: "K"),  // Source image for segmentation
        "DCM|121342|IMAGE": E341Row(meaning: "Dose Image", basic: "X", uids: "K"),  // Dose Image
        "DCM|121431|DATETIME": E341Row(meaning: "DateTime Concern Noted", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime Concern Noted
        "DCM|121432|DATETIME": E341Row(meaning: "DateTime Concern Resolved", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime Concern Resolved
        "DCM|121433|DATETIME": E341Row(meaning: "DateTime Problem Resolved", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime Problem Resolved
        "DCM|121434|TEXT": E341Row(meaning: "Service Delivery Location", basic: "X", institution: "K"),  // Service Delivery Location
        "DCM|121435|PNAME": E341Row(meaning: "Service Performer", basic: "X"),  // Service Performer
        "DCM|121435|TEXT": E341Row(meaning: "Service Performer", basic: "X"),  // Service Performer
        "DCM|122073|COMPOSITE": E341Row(meaning: "Current procedure evidence", basic: "X", uids: "K"),  // Current procedure evidence
        "DCM|122075|COMPOSITE": E341Row(meaning: "Prior report for current patient", basic: "X", uids: "K"),  // Prior report for current patient
        "DCM|122081|DATETIME": E341Row(meaning: "Drug start", basic: "X", fullDates: "K", modifiedDates: "C"),  // Drug start
        "DCM|122082|DATETIME": E341Row(meaning: "Drug end", basic: "X", fullDates: "K", modifiedDates: "C"),  // Drug end
        "DCM|122083|TEXT": E341Row(meaning: "Drug administered", basic: "X/D", cleanDescriptors: "C"),  // Drug administered
        "DCM|122105|DATETIME": E341Row(meaning: "DateTime of Intervention", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime of Intervention
        "DCM|122128|TEXT": E341Row(meaning: "Patient Transferred From", basic: "X", institution: "K"),  // Patient Transferred From
        "DCM|122146|DATETIME": E341Row(meaning: "Procedure DateTime", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Procedure DateTime
        "DCM|122163|DATETIME": E341Row(meaning: "Discharge DateTime", basic: "X", fullDates: "K", modifiedDates: "C"),  // Discharge DateTime
        "DCM|122165|DATETIME": E341Row(meaning: "DateTime of Death", basic: "X", fullDates: "K", modifiedDates: "C"),  // DateTime of Death
        "DCM|122173|DATETIME": E341Row(meaning: "ST Elevation Onset DateTime", basic: "X", fullDates: "K", modifiedDates: "C"),  // ST Elevation Onset DateTime
        "DCM|122177|TEXT": E341Row(meaning: "Procedure Result", basic: "X", cleanDescriptors: "C"),  // Procedure Result
        "DCM|122701|DATETIME": E341Row(meaning: "Procedure Time Base", basic: "X", fullDates: "K", modifiedDates: "C"),  // Procedure Time Base
        "DCM|122712|DATETIME": E341Row(meaning: "Imaging Start DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Imaging Start DateTime
        "DCM|123003|DATETIME": E341Row(meaning: "Radiopharmaceutical Start DateTime", basic: "X/D", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Start DateTime
        "DCM|123004|DATETIME": E341Row(meaning: "Radiopharmaceutical Stop DateTime", basic: "X", fullDates: "K", modifiedDates: "C"),  // Radiopharmaceutical Stop DateTime
        "DCM|125010|TEXT": E341Row(meaning: "Identifier", basic: "X"),  // Identifier
        "DCM|125201|IMAGE": E341Row(meaning: "Illustration of Finding", basic: "X", uids: "K"),  // Illustration of Finding
        "DCM|125203|TEXT": E341Row(meaning: "Acquisition Protocol", basic: "X", cleanDescriptors: "C"),  // Acquisition Protocol
        "DCM|126070|TEXT": E341Row(meaning: "Subject Time Point Identifier", basic: "X", cleanDescriptors: "C"),  // Subject Time Point Identifier
        "DCM|126071|TEXT": E341Row(meaning: "Protocol Time Point Identifier", basic: "X", cleanDescriptors: "C"),  // Protocol Time Point Identifier
        "DCM|126100|COMPOSITE": E341Row(meaning: "Real World Value Map used for measurement", basic: "X", uids: "K"),  // Real World Value Map used for measurement
        "DCM|126201|DATE": E341Row(meaning: "Acquisition Date", basic: "X", fullDates: "K", modifiedDates: "C"),  // Acquisition Date
        "DCM|126202|TIME": E341Row(meaning: "Acquisition Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Acquisition Time
        "DCM|127857|DATE": E341Row(meaning: "Glucose Measurement Date", basic: "D", fullDates: "K", modifiedDates: "C"),  // Glucose Measurement Date
        "DCM|127858|TIME": E341Row(meaning: "Glucose Measurement Time", basic: "D", fullDates: "K", modifiedDates: "C"),  // Glucose Measurement Time
        "DCM|128230|TEXT": E341Row(meaning: "Pulse Sequence Name", basic: "X", cleanDescriptors: "C"),  // Pulse Sequence Name
        "DCM|128403|TEXT": E341Row(meaning: "Radiation Dose Estimate Name", basic: "D", cleanDescriptors: "C"),  // Radiation Dose Estimate Name
        "DCM|128414|COMPOSITE": E341Row(meaning: "Radiation Dose Representation Data", basic: "D", uids: "K"),  // Radiation Dose Representation Data
        "DCM|128414|IMAGE": E341Row(meaning: "Radiation Dose Representation Data", basic: "D", uids: "K"),  // Radiation Dose Representation Data
        "DCM|128416|COMPOSITE": E341Row(meaning: "SR Instance Used", basic: "D", uids: "K"),  // SR Instance Used
        "DCM|128425|COMPOSITE": E341Row(meaning: "Patient Radiation Dose Model Data", basic: "X", uids: "K"),  // Patient Radiation Dose Model Data
        "DCM|128425|IMAGE": E341Row(meaning: "Patient Radiation Dose Model Data", basic: "X", uids: "K"),  // Patient Radiation Dose Model Data
        "DCM|128425|UIDREF": E341Row(meaning: "Patient Radiation Dose Model Data", basic: "X", uids: "K"),  // Patient Radiation Dose Model Data
        "DCM|128426|TEXT": E341Row(meaning: "Patient Radiation Dose Model Reference", basic: "X", cleanDescriptors: "C"),  // Patient Radiation Dose Model Reference
        "DCM|128429|UIDREF": E341Row(meaning: "Event UID Used", basic: "D", uids: "K"),  // Event UID Used
        "DCM|128436|COMPOSITE": E341Row(meaning: "Radiation Dose Composite Parameters", basic: "D", uids: "K"),  // Radiation Dose Composite Parameters
        "DCM|128444|COMPOSITE": E341Row(meaning: "Spatial Registration Reference", basic: "D", uids: "K"),  // Spatial Registration Reference
        "DCM|128447|COMPOSITE": E341Row(meaning: "Spatial Fiducials", basic: "X", uids: "K"),  // Spatial Fiducials
        "DCM|128470|COMPOSITE": E341Row(meaning: "X-Ray Attenuator Model Data", basic: "X", uids: "K"),  // X-Ray Attenuator Model Data
        "DCM|128470|IMAGE": E341Row(meaning: "X-Ray Attenuator Model Data", basic: "X", uids: "K"),  // X-Ray Attenuator Model Data
        "DCM|128470|UIDREF": E341Row(meaning: "X-Ray Attenuator Model Data", basic: "X", uids: "K"),  // X-Ray Attenuator Model Data
        "DCM|128774|TEXT": E341Row(meaning: "Person Observer's Login Name", basic: "X"),  // Person Observer's Login Name
        "DCM|128775|TEXT": E341Row(meaning: "Identifier within Person Observer's Role", basic: "X"),  // Identifier within Person Observer's Role
        "DCM|130507|TEXT": E341Row(meaning: "RDSR Frame of Reference Description", basic: "X", cleanDescriptors: "C"),  // RDSR Frame of Reference Description
        "DCM|130527|TEXT": E341Row(meaning: "Identification of the Attenuator", basic: "D", institution: "K"),  // Identification of the Attenuator
        "DCM|130884|DATETIME": E341Row(meaning: "Acquisition DateTime", basic: "X", fullDates: "K", modifiedDates: "C"),  // Acquisition DateTime
        "DCM|130885|UIDREF": E341Row(meaning: "Synchronization Frame of Reference UID", basic: "X", uids: "K"),  // Synchronization Frame of Reference UID
        "LN|11329-0|TEXT": E341Row(meaning: "History", basic: "X", cleanDescriptors: "C"),  // History
        "LN|11778-8|DATE": E341Row(meaning: "EDD", basic: "X", fullDates: "K", modifiedDates: "C"),  // EDD
        "LN|11951-1|TEXT": E341Row(meaning: "Fetus ID", basic: "D"),  // Fetus ID
        "LN|11955-2|DATE": E341Row(meaning: "Date of last menstrual period", basic: "X", fullDates: "K", modifiedDates: "C"),  // Date of last menstrual period
        "LN|18118-0|TEXT": E341Row(meaning: "LV Wall Motion Segmental Findings", basic: "X", cleanDescriptors: "C"),  // LV Wall Motion Segmental Findings
        "LN|18785-6|TEXT": E341Row(meaning: "Indications for Procedure", basic: "D", cleanDescriptors: "C"),  // Indications for Procedure
        "LN|74711-3|TEXT": E341Row(meaning: "Unique Device Identifier", basic: "X", device: "K"),  // Unique Device Identifier
        "NCDR|15|DATETIME": E341Row(meaning: "Admission DateTime", basic: "X", fullDates: "K", modifiedDates: "C"),  // Admission DateTime
        "NCDR|52|DATETIME": E341Row(meaning: "Procedure DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Procedure DateTime
        "NCDR|53|TEXT": E341Row(meaning: "Procedure Number in this admission", basic: "X"),  // Procedure Number in this admission
        "NCDR|76|PNAME": E341Row(meaning: "Catheterization Operator", basic: "D"),  // Catheterization Operator
        "NCIt|C54627|NUM": E341Row(meaning: "Experience", basic: "X"),  // Experience
        "NCIt|C67447|TEXT": E341Row(meaning: "Activity Session", basic: "X", cleanDescriptors: "C"),  // Activity Session
        "SCT|116224001|TEXT": E341Row(meaning: "Complication of Procedure", basic: "X", cleanDescriptors: "C"),  // Complication of Procedure
        "SCT|160476009|TEXT": E341Row(meaning: "Social History", basic: "X", cleanDescriptors: "C"),  // Social History
        "SCT|271921002|TEXT": E341Row(meaning: "ECG Finding", basic: "X/D", cleanDescriptors: "C"),  // ECG Finding
        "SCT|363698007|TEXT": E341Row(meaning: "Finding Site", basic: "D", cleanDescriptors: "C"),  // Finding Site
        "SCT|371524004|COMPOSITE": E341Row(meaning: "Clinical Report", basic: "X", uids: "K"),  // Clinical Report
        "SCT|371524004|TEXT": E341Row(meaning: "Clinical Report", basic: "X", cleanDescriptors: "C"),  // Clinical Report
        "SCT|397898000|DATETIME": E341Row(meaning: "Stop DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Stop DateTime
        "SCT|398164008|DATETIME": E341Row(meaning: "Anesthesia Finish Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Finish Time
        "SCT|398201009|DATETIME": E341Row(meaning: "Start DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Start DateTime
        "SCT|398325003|DATETIME": E341Row(meaning: "Anesthesia Start Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Start Time
        "SCT|440252007|TEXT": E341Row(meaning: "Administration of radiopharmaceutical", basic: "D", cleanDescriptors: "C"),  // Administration of radiopharmaceutical
        "SNM3|DD-60002|TEXT": E341Row(meaning: "Complication of Procedure", basic: "X", cleanDescriptors: "C"),  // Complication of Procedure (retired SNM3 DD-60002 = SCT 116224001)
        "SNM3|DF-0068E|DATETIME": E341Row(meaning: "Anesthesia Start Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Start Time (retired SNM3 DF-0068E = SCT 398325003)
        "SNM3|DF-0070B|DATETIME": E341Row(meaning: "Anesthesia Finish Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Finish Time (retired SNM3 DF-0070B = SCT 398164008)
        "SNM3|F-00033|TEXT": E341Row(meaning: "ECG Finding", basic: "X/D", cleanDescriptors: "C"),  // ECG Finding (retired SNM3 F-00033 = SCT 271921002)
        "SNM3|F-02455|TEXT": E341Row(meaning: "Social History", basic: "X", cleanDescriptors: "C"),  // Social History (retired SNM3 F-02455 = SCT 160476009)
        "SNM3|G-C0E3|TEXT": E341Row(meaning: "Finding Site", basic: "D", cleanDescriptors: "C"),  // Finding Site (retired SNM3 G-C0E3 = SCT 363698007)
        "SNM3|G-D320|DATETIME": E341Row(meaning: "Stop DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Stop DateTime (retired SNM3 G-D320 = SCT 397898000)
        "SNM3|G-D321|DATETIME": E341Row(meaning: "Start DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Start DateTime (retired SNM3 G-D321 = SCT 398201009)
        "SNM3|PA-30029|TEXT": E341Row(meaning: "Administration of radiopharmaceutical", basic: "D", cleanDescriptors: "C"),  // Administration of radiopharmaceutical (retired SNM3 PA-30029 = SCT 440252007)
        "SNM3|R-42B89|COMPOSITE": E341Row(meaning: "Clinical Report", basic: "X", uids: "K"),  // Clinical Report (retired SNM3 R-42B89 = SCT 371524004)
        "SNM3|R-42B89|TEXT": E341Row(meaning: "Clinical Report", basic: "X", cleanDescriptors: "C"),  // Clinical Report (retired SNM3 R-42B89 = SCT 371524004)
        "SRT|DD-60002|TEXT": E341Row(meaning: "Complication of Procedure", basic: "X", cleanDescriptors: "C"),  // Complication of Procedure (retired SRT DD-60002 = SCT 116224001)
        "SRT|DF-0068E|DATETIME": E341Row(meaning: "Anesthesia Start Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Start Time (retired SRT DF-0068E = SCT 398325003)
        "SRT|DF-0070B|DATETIME": E341Row(meaning: "Anesthesia Finish Time", basic: "X", fullDates: "K", modifiedDates: "C"),  // Anesthesia Finish Time (retired SRT DF-0070B = SCT 398164008)
        "SRT|F-00033|TEXT": E341Row(meaning: "ECG Finding", basic: "X/D", cleanDescriptors: "C"),  // ECG Finding (retired SRT F-00033 = SCT 271921002)
        "SRT|F-02455|TEXT": E341Row(meaning: "Social History", basic: "X", cleanDescriptors: "C"),  // Social History (retired SRT F-02455 = SCT 160476009)
        "SRT|G-C0E3|TEXT": E341Row(meaning: "Finding Site", basic: "D", cleanDescriptors: "C"),  // Finding Site (retired SRT G-C0E3 = SCT 363698007)
        "SRT|G-D320|DATETIME": E341Row(meaning: "Stop DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Stop DateTime (retired SRT G-D320 = SCT 397898000)
        "SRT|G-D321|DATETIME": E341Row(meaning: "Start DateTime", basic: "D", fullDates: "K", modifiedDates: "C"),  // Start DateTime (retired SRT G-D321 = SCT 398201009)
        "SRT|PA-30029|TEXT": E341Row(meaning: "Administration of radiopharmaceutical", basic: "D", cleanDescriptors: "C"),  // Administration of radiopharmaceutical (retired SRT PA-30029 = SCT 440252007)
        "SRT|R-42B89|COMPOSITE": E341Row(meaning: "Clinical Report", basic: "X", uids: "K"),  // Clinical Report (retired SRT R-42B89 = SCT 371524004)
        "SRT|R-42B89|TEXT": E341Row(meaning: "Clinical Report", basic: "X", cleanDescriptors: "C"),  // Clinical Report (retired SRT R-42B89 = SCT 371524004)
        "UMLS|C2348792|TEXT": E341Row(meaning: "Time Point", basic: "X/D", cleanDescriptors: "C"),  // Time Point
    ]
}
