// ConfidentialityProfileSafePrivate.swift
// DICOMKit
//
// GENERATED by Scripts/generate_confidentiality_profile.py from DICOM PS3.15 2026a - Security and System Management Profiles,
// Table E.3.10-1 (479 rows). Do not hand-edit: fix the generator and regenerate.
//
// NEMA-verified: 2026a, checked 2026-10-01 — every row of PS3.15 2026a Table E.3.10-1 Safe Private Attributes (479: Private Creator, group, element within the block, VR), generated from the DocBook (D159); `generate_confidentiality_profile.py --check` re-verifies it.

extension ConfidentialityProfile {
    /// PS3.15 2026a Table E.3.10-1 Safe Private Attributes, keyed
    /// "<Private Creator>|<group hex>|<element within the block, 2 hex digits>" (upper-case hex),
    /// with the VR the table lists. The Retain Safe Private Option keeps these (E.3.10).
    static let safePrivateAttributes: [String: String] = [
        "ELSCINT1|00E1|21": "DS",  // DLP
        "ELSCINT1|00E1|50": "DS",  // Acquisition Duration
        "ELSCINT1|01E1|26": "CS",  // Phantom Type
        "ELSCINT1|01F1|01": "CS",  // Acquisition Type
        "ELSCINT1|01F1|07": "DS",  // Table Velocity
        "ELSCINT1|01F1|26": "DS",  // Pitch
        "ELSCINT1|01F1|27": "DS",  // Rotation Time
        "GEIIS PACS|0903|10": "US",  // Reject Image Flag
        "GEIIS PACS|0903|11": "US",  // Significant Flag
        "GEIIS PACS|0903|12": "US",  // Confidential Flag
        "GEMS_ACQU_01|0019|23": "DS",  // Table Speed [mm/rotation]
        "GEMS_ACQU_01|0019|24": "DS",  // Mid Scan Time [sec]
        "GEMS_ACQU_01|0019|27": "DS",  // Rotation Speed (Gantry Period)
        "GEMS_ACQU_01|0019|9E": "LO",  // Internal Pulse Sequence Name
        "GEMS_HELIOS_01|0045|01": "SS",  // Number of Macro Rows in Detector
        "GEMS_HELIOS_01|0045|02": "FL",  // Macro width at ISO Center
        "GEMS_PARM_01|0043|27": "SH",  // Scan Pitch Ratio in the form "n.nnn:1"
        "GEMS_PARM_01|0043|39": "IS",  // 1stvalue is B Value
        "GEMS_PARM_01|0043|6F": "DS",  // Scanner Table Entry + Gradient Coil Selected
        "GEMS_SERS_01|0025|07": "SL",  // Images in Series
        "HOLOGIC, Inc.|7E01|01": "LO",  // Codec Version
        "HOLOGIC, Inc.|7E01|02": "SH",  // Codec Content Type
        "HOLOGIC, Inc.|7E01|10": "SQ",  // High Resolution Data Sequence
        "HOLOGIC, Inc.|7E01|11": "SQ",  // Low Resolution Data Sequence
        "HOLOGIC, Inc.|7E01|12": "OB",  // Codec Content
        "NQHeader|0099|01": "UI",  // Version
        "NQHeader|0099|02": "UI",  // Analyzed Series UID
        "NQHeader|0099|04": "SS",  // Return Code
        "NQHeader|0099|05": "LT",  // Return Message
        "NQHeader|0099|10": "FL",  // MI
        "NQHeader|0099|20": "SH",  // Units
        "NQHeader|0099|21": "FL",  // ICV
        "NQLeft|0199|01": "FL",  // Left Cortical White Matter
        "NQLeft|0199|02": "FL",  // Left Cortical Gray Matter
        "NQLeft|0199|03": "FL",  // Left 3rd Ventricle
        "NQLeft|0199|04": "FL",  // Left 4th Ventricle
        "NQLeft|0199|05": "FL",  // Left 5th Ventricle
        "NQLeft|0199|06": "FL",  // Left Lateral Ventricle
        "NQLeft|0199|07": "FL",  // Left Inferior Lateral Ventricle
        "NQLeft|0199|08": "FL",  // Left Inferior CSF
        "NQLeft|0199|09": "FL",  // Left Cerebellar White Matter
        "NQLeft|0199|0A": "FL",  // Left Cerebellar Gray Matter
        "NQLeft|0199|0B": "FL",  // Left Hippocampus
        "NQLeft|0199|0C": "FL",  // Left Amygdala
        "NQLeft|0199|0D": "FL",  // Left Thalamus
        "NQLeft|0199|0E": "FL",  // Left Caudate
        "NQLeft|0199|0F": "FL",  // Left Putamen
        "NQLeft|0199|10": "FL",  // Left Pallidum
        "NQLeft|0199|11": "FL",  // Left Ventral Diencephalon
        "NQLeft|0199|12": "FL",  // Left Nucleus Accumbens
        "NQLeft|0199|13": "FL",  // Left Brain Stem
        "NQLeft|0199|14": "FL",  // Left Exterior CSF
        "NQLeft|0199|15": "FL",  // Left WM Hypo
        "NQLeft|0199|16": "FL",  // Left Other
        "NQRight|0299|01": "FL",  // Right Cortical White Matter
        "NQRight|0299|02": "FL",  // Right Cortical Gray Matter
        "NQRight|0299|03": "FL",  // Right 3rd Ventricle
        "NQRight|0299|04": "FL",  // Right 4th Ventricle
        "NQRight|0299|05": "FL",  // Right 5th Ventricle
        "NQRight|0299|06": "FL",  // Right Lateral Ventricle
        "NQRight|0299|07": "FL",  // Right Inferior Lateral Ventricle
        "NQRight|0299|08": "FL",  // Right Inferior CSF
        "NQRight|0299|09": "FL",  // Right Cerebellar White Matter
        "NQRight|0299|0A": "FL",  // Right Cerebellar Gray Matter
        "NQRight|0299|0B": "FL",  // Right Hippocampus
        "NQRight|0299|0C": "FL",  // Right Amygdala
        "NQRight|0299|0D": "FL",  // Right Thalamus
        "NQRight|0299|0E": "FL",  // Right Caudate
        "NQRight|0299|0F": "FL",  // Right Putamen
        "NQRight|0299|10": "FL",  // Right Pallidum
        "NQRight|0299|11": "FL",  // Right Ventral Diencephalon
        "NQRight|0299|12": "FL",  // Right Nucleus Accumbens
        "NQRight|0299|13": "FL",  // Right Brain Stem
        "NQRight|0299|14": "FL",  // Right Exterior CSF
        "NQRight|0299|15": "FL",  // Right WM Hypo
        "NQRight|0299|16": "FL",  // Right Other
        "Philips Imaging DD 001|2001|01": "FL",  // MR Image Chemical Shift
        "Philips Imaging DD 001|2001|02": "IS",  // MR Image Chemical Shift Number
        "Philips Imaging DD 001|2001|03": "FL",  // MR Image Diffusion B-Factor
        "Philips Imaging DD 001|2001|04": "CS",  // MR Image Diffusion Direction
        "Philips Imaging DD 001|2001|05": "SS",  // Graphic Annotation Parent ID
        "Philips Imaging DD 001|2001|06": "CS",  // MR Image Enhanced
        "Philips Imaging DD 001|2001|07": "CS",  // MR Image Type Edes
        "Philips Imaging DD 001|2001|08": "IS",  // MR Image Phase Number
        "Philips Imaging DD 001|2001|09": "FL",  // MR Image Prepulse Delay
        "Philips Imaging DD 001|2001|0A": "IS",  // Image Plane Number
        "Philips Imaging DD 001|2001|0B": "CS",  // Image Plane Orientation
        "Philips Imaging DD 001|2001|0C": "CS",  // MR Series Arrhythmia Rejection
        "Philips Imaging DD 001|2001|0E": "CS",  // MR Series Cardiac Cycled
        "Philips Imaging DD 001|2001|0F": "SS",  // MR Series Cardiac Gate Width
        "Philips Imaging DD 001|2001|10": "CS",  // MR Series Cardiac Sync
        "Philips Imaging DD 001|2001|11": "FL",  // MR Series Diffusion Echo Time
        "Philips Imaging DD 001|2001|12": "CS",  // MR Series Dynamic Series
        "Philips Imaging DD 001|2001|13": "SL",  // MR Series Epi Factor
        "Philips Imaging DD 001|2001|14": "SL",  // MR Series Nr Of Echoes
        "Philips Imaging DD 001|2001|15": "SS",  // MR Series Nr Of Locations
        "Philips Imaging DD 001|2001|16": "SS",  // MR Series Nr Of Phase Contrast Directions
        "Philips Imaging DD 001|2001|17": "SL",  // MR Series Nr Of Phases
        "Philips Imaging DD 001|2001|18": "SL",  // MR Series Nr Of Slices
        "Philips Imaging DD 001|2001|19": "CS",  // MR Series Partial Matrix Scanned
        "Philips Imaging DD 001|2001|1A": "FL",  // MR Series Pc Velocity
        "Philips Imaging DD 001|2001|1B": "FL",  // MR Series Prepulse Delay
        "Philips Imaging DD 001|2001|1C": "CS",  // MR Series Prepulse Type
        "Philips Imaging DD 001|2001|1D": "IS",  // MR Series Reconstruction Number
        "Philips Imaging DD 001|2001|1E": "CS",  // MR Series Reformat Accuracy
        "Philips Imaging DD 001|2001|1F": "CS",  // MR Series Respiration Sync
        "Philips Imaging DD 001|2001|21": "CS",  // MR Series Sel Part Inversion Recovery
        "Philips Imaging DD 001|2001|22": "FL",  // MR Series Water Fat Shift
        "Philips Imaging DD 001|2001|23": "DS",  // MR Series Flip Angle
        "Philips Imaging DD 001|2001|24": "CS",  // MR Series Is Interactive
        "Philips Imaging DD 001|2001|25": "SH",  // MR Series Echo Time Display
        "Philips Imaging DD 001|2001|26": "CS",  // Presentation State Subtraction Active
        "Philips Imaging DD 001|2001|27": "CS",  // Edge Enhancement Kernel Size
        "Philips Imaging DD 001|2001|28": "FL",  // Edge Enhancement Gain Factor Sub
        "Philips Imaging DD 001|2001|29": "FL",  // Edge Enhancement Gain Factor
        "Philips Imaging DD 001|2001|2A": "CS",  // Edge Enhancement Taste Adapt Sub
        "Philips Imaging DD 001|2001|2B": "CS",  // Edge Enhancement Taste Adapt
        "Philips Imaging DD 001|2001|2C": "FL",  // Harmonization Factor
        "Philips Imaging DD 001|2001|2D": "SS",  // Stack Number Of Slices
        "Philips Imaging DD 001|2001|2E": "CS",  // Harmonization Kernel Size
        "Philips Imaging DD 001|2001|2F": "FL",  // Harmonization Gain
        "Philips Imaging DD 001|2001|30": "UL",  // Log Subtraction Gain Step Taste
        "Philips Imaging DD 001|2001|31": "US",  // Mixing Nr Of Mask Image Numbers
        "Philips Imaging DD 001|2001|32": "FL",  // Stack Radial Angle
        "Philips Imaging DD 001|2001|33": "CS",  // Stack Radial Axis
        "Philips Imaging DD 001|2001|34": "CS",  // Mixing Mask Operation Type
        "Philips Imaging DD 001|2001|35": "SS",  // Stack Slice Number
        "Philips Imaging DD 001|2001|36": "CS",  // Stack Type
        "Philips Imaging DD 001|2001|37": "CS",  // Mixing Operation Type
        "Philips Imaging DD 001|2001|38": "FL",  // Overlay Mix Factor
        "Philips Imaging DD 001|2001|39": "FL",  // Overscan Factor
        "Philips Imaging DD 001|2001|3A": "CS",  // Pixel Shift
        "Philips Imaging DD 001|2001|3B": "FL",  // Pixel Shift Split Line Coordinates
        "Philips Imaging DD 001|2001|3C": "FL",  // Pixel Shift Shift Vectora
        "Philips Imaging DD 001|2001|3D": "UL",  // Contour Fill Color
        "Philips Imaging DD 001|2001|3E": "FL",  // Pixel Shift Shift Vectorb
        "Philips Imaging DD 001|2001|3F": "CS",  // Displayed Area Zoom Interpolation Meth
        "Philips Imaging DD 001|2001|40": "CS",  // Pixel Shift Split Screen
        "Philips Imaging DD 001|2001|41": "FL",  // Subtraction Land Marking Factor
        "Philips Imaging DD 001|2001|42": "CS",  // Subtraction Land Marking Active
        "Philips Imaging DD 001|2001|43": "IS",  // Ellips Displ Shut Major Ax Frst End Pnt
        "Philips Imaging DD 001|2001|44": "IS",  // Ellips Displ Shut Major Ax Scnd End Pnt
        "Philips Imaging DD 001|2001|45": "IS",  // Ellips Displ Shut Other Ax Frst End Pnt
        "Philips Imaging DD 001|2001|46": "CS",  // Graphic Line Style
        "Philips Imaging DD 001|2001|47": "FL",  // Graphic Line Width
        "Philips Imaging DD 001|2001|48": "SS",  // Graphic Annotation Id
        "Philips Imaging DD 001|2001|49": "IS",  // Trace First Image
        "Philips Imaging DD 001|2001|4A": "CS",  // Trace Taste
        "Philips Imaging DD 001|2001|4B": "CS",  // Interpolation Method
        "Philips Imaging DD 001|2001|4C": "CS",  // Poly Line Begin Point Style
        "Philips Imaging DD 001|2001|4D": "CS",  // Poly Line End Point Style
        "Philips Imaging DD 001|2001|4E": "CS",  // Window Smoothing Taste
        "Philips Imaging DD 001|2001|4F": "FD",  // Harmonization Offset
        "Philips Imaging DD 001|2001|50": "LO",  // Graphic Marker Type
        "Philips Imaging DD 001|2001|51": "IS",  // Overlay Plane Id
        "Philips Imaging DD 001|2001|53": "CS",  // Presentation Gl Trafo Invert
        "Philips Imaging DD 001|2001|54": "FL",  // Contour Fill Transparency
        "Philips Imaging DD 001|2001|55": "UL",  // Graphic Line Color
        "Philips Imaging DD 001|2001|56": "CS",  // Graphic Type
        "Philips Imaging DD 001|2001|57": "CS",  // Log Subtraction Taste
        "Philips Imaging DD 001|2001|58": "UL",  // Series Xray Contrast Transfer Taste
        "Philips Imaging DD 001|2001|59": "IS",  // Curve Id
        "Philips Imaging DD 001|2001|5A": "ST",  // Graphic Annotation Model
        "Philips Imaging DD 001|2001|5D": "ST",  // Measurement Text Units
        "Philips Imaging DD 001|2001|5E": "ST",  // Measurement Text Type
        "Philips Imaging DD 001|2001|5F": "SQ",  // Stack Sequence
        "Philips Imaging DD 001|2001|60": "SL",  // MR Series Nr Of Stacks
        "Philips Imaging DD 001|2001|61": "CS",  // Series Transmitted
        "Philips Imaging DD 001|2001|62": "CS",  // Series Committed
        "Philips Imaging DD 001|2001|63": "CS",  // Examination Source
        "Philips Imaging DD 001|2001|64": "SH",  // Text Type
        "Philips Imaging DD 001|2001|65": "SQ",  // Overlay Plane Sequence
        "Philips Imaging DD 001|2001|66": "SQ",  // Image Curve
        "Philips Imaging DD 001|2001|67": "CS",  // Linear Presentation Gl Trafo Shape Sub
        "Philips Imaging DD 001|2001|68": "SQ",  // Modality Gl Trafo Sequence
        "Philips Imaging DD 001|2001|69": "SQ",  // Display Shutter Sequence
        "Philips Imaging DD 001|2001|6A": "SQ",  // Spatial Transformation Sequence
        "Philips Imaging DD 001|2001|6B": "SQ",  // Edge Enhancement Sequence
        "Philips Imaging DD 001|2001|6D": "LO",  // Text Font
        "Philips Imaging DD 001|2001|6E": "SH",  // Series Type
        "Philips Imaging DD 001|2001|6F": "SQ",  // Mixing Sequence
        "Philips Imaging DD 001|2001|71": "CS",  // Graphic Constraint
        "Philips Imaging DD 001|2001|72": "IS",  // Ellips Displ Shut Other Ax Scnd End Pnt
        "Philips Imaging DD 001|2001|73": "SQ",  // Referenced Mask Image Sequence
        "Philips Imaging DD 001|2001|74": "DS",  // Window Center Sub
        "Philips Imaging DD 001|2001|75": "DS",  // Window Width Sub
        "Philips Imaging DD 001|2001|76": "UL",  // Presentation State Xray Contrast Transfer Taste
        "Philips Imaging DD 001|2001|77": "CS",  // Gl Trafo Type
        "Philips Imaging DD 001|2001|79": "SQ",  // Harmonisation Sequence
        "Philips Imaging DD 001|2001|7A": "FL",  // Window Rounding Factor
        "Philips Imaging DD 001|2001|7B": "IS",  // MR Series Acquisition Number
        "Philips Imaging DD 001|2001|7C": "UL",  // Frame Number
        "Philips Imaging DD 001|2001|7D": "OW/OB",  // Frame Pixel Data
        "Philips Imaging DD 001|2001|7E": "US",  // Edge Enhancement Gain Taste
        "Philips Imaging DD 001|2001|7F": "US",  // Edge Enhancement Gain Taste Sub
        "Philips Imaging DD 001|2001|80": "LO",  // Text Anchor Point Alignment
        "Philips Imaging DD 001|2001|81": "IS",  // MR Series Nr Of Dynamic Scans
        "Philips Imaging DD 001|2001|82": "IS",  // MR Series Echo Train Length
        "Philips Imaging DD 001|2001|83": "DS",  // MR Series Imaging Frequency
        "Philips Imaging DD 001|2001|84": "DS",  // MR Series Inversion Time
        "Philips Imaging DD 001|2001|85": "DS",  // MR Series Magnetic Field Strength
        "Philips Imaging DD 001|2001|86": "IS",  // MR Series Nr Of Phase Encoding Steps
        "Philips Imaging DD 001|2001|87": "SH",  // MR Series Nucleus
        "Philips Imaging DD 001|2001|88": "DS",  // MR Series Number Of Averages
        "Philips Imaging DD 001|2001|89": "DS",  // MR Series Percent Phase Field Of View
        "Philips Imaging DD 001|2001|8A": "DS",  // MR Series Percent Sampling
        "Philips Imaging DD 001|2001|8B": "SH",  // MR Series Transmitting Coil
        "Philips Imaging DD 001|2001|8C": "CS",  // Needs Processing
        "Philips Imaging DD 001|2001|90": "LO",  // Text Foreground Color
        "Philips Imaging DD 001|2001|91": "LO",  // Text Background Color
        "Philips Imaging DD 001|2001|92": "LO",  // Text Shadow Color
        "Philips Imaging DD 001|2001|93": "LO",  // Text Style
        "Philips Imaging DD 001|2001|94": "LO",  // Processing Order Specialization
        "Philips Imaging DD 001|2001|9A": "SQ",  // Graphic Number Sequence
        "Philips Imaging DD 001|2001|9B": "UL",  // Graphic Number
        "Philips Imaging DD 001|2001|9D": "LO",  // Subtraction Type
        "Philips Imaging DD 001|2001|9F": "US",  // Pixel Processing Kernel Size
        "Philips Imaging DD 001|2001|A1": "CS",  // Is Raw Image
        "Philips Imaging DD 001|2001|A2": "US",  // Log Subtraction Curve Taste
        "Philips Imaging DD 001|2001|A3": "UL",  // Text Color Foreground
        "Philips Imaging DD 001|2001|A4": "UL",  // Text Color Background
        "Philips Imaging DD 001|2001|A5": "UL",  // Text Color Shadow
        "Philips Imaging DD 001|2001|C0": "UL",  // Content Item Identifier
        "Philips Imaging DD 001|2001|C1": "LO",  // Nested Object Type Name
        "Philips Imaging DD 001|2001|C2": "FD",  // Subtraction Rescale Factor
        "Philips Imaging DD 001|2001|C3": "UL",  // Subtraction Offset
        "Philips Imaging DD 001|2001|C5": "SQ",  // Mask Image Lut Sequence
        "Philips Imaging DD 001|2001|C6": "SQ",  // Gain Lut Sequence
        "Philips Imaging DD 001|2001|C7": "SQ",  // Contrast Image Lut Sequence
        "Philips Imaging DD 001|2001|CA": "SQ",  // Reversed Modality Lut
        "Philips Imaging DD 001|2001|CB": "IS",  // Redundant Overlay Plane Id
        "Philips Imaging DD 001|2001|D0": "AT",  // Frame Index Pointer
        "Philips Imaging DD 001|2001|D1": "US",  // Index Number Vector
        "Philips Imaging DD 001|2001|D2": "US",  // Frame Detector Number
        "Philips Imaging DD 001|2001|D3": "US",  // Frame Phase Number
        "Philips Imaging DD 001|2001|D4": "US",  // Frame Rotation Number
        "Philips Imaging DD 001|2001|D5": "US",  // Frame Rr Interval Number
        "Philips Imaging DD 001|2001|D6": "US",  // Frame Time Slot Number
        "Philips Imaging DD 001|2001|D7": "US",  // Frame Slice Number
        "Philips Imaging DD 001|2001|D8": "US",  // Frame Angular View Number
        "Philips Imaging DD 001|2001|D9": "US",  // Frame Time Slice Number
        "Philips Imaging DD 001|2001|DA": "CS",  // Is Arrowhead
        "Philips Imaging DD 001|2001|DB": "US",  // PET Rr Interval Index
        "Philips Imaging DD 001|2001|DC": "US",  // PET Time Slot Index
        "Philips Imaging DD 001|2001|DD": "US",  // PET Time Slice Index
        "Philips Imaging DD 001|2001|DE": "US",  // PET Slice Index
        "Philips Imaging DD 001|2001|DF": "UL",  // Voxel Number
        "Philips Imaging DD 001|2001|E9": "SQ",  // Per Frame Voxels Functional Group
        "Philips Imaging DD 001|2001|F1": "FL",  // MR Image Prospective Motion Correction
        "Philips Imaging DD 001|2001|F2": "FL",  // MR Image Retrospective Motion Correction
        "Philips Imaging DD 001|2001|F3": "CS",  // Dynamic Linear Voigl Trafo
        "Philips Imaging DD 001|2001|F4": "UL",  // Color Key
        "Philips Imaging DD 001|2001|F5": "CS",  // Rotated Text Allowed
        "Philips Imaging DD 001|2001|F6": "UL",  // Number Of Represented Images
        "Philips Imaging DD 001|2001|F7": "LO",  // Data Type Icons
        "Philips Imaging DD 001|2001|F9": "SQ",  // Flagging Sequence
        "Philips Imaging DD 001|2001|FB": "SQ",  // Bookmark Sequence
        "Philips Imaging DD 001|2001|FC": "SQ",  // Ris Code Sequence
        "Philips Imaging DD 001|2001|FD": "SQ",  // Workflow Step Sequence
        "Philips Imaging DD 001|2001|FF": "OW/OB",  // Volume Pixel
        "Philips Imaging DD 002|2001|01": "US",  // Edr Setgp
        "Philips Imaging DD 002|2001|02": "FD",  // Edr Setsk
        "Philips Imaging DD 002|2001|03": "CS",  // Um Rank Type
        "Philips Imaging DD 002|2001|04": "SS",  // Um Rank Number
        "Philips Imaging DD 002|2001|05": "FD",  // Um Rank Enhancement
        "Philips Imaging DD 002|2001|06": "US",  // Um Kernel Size
        "Philips Imaging DD 002|2001|07": "CS",  // Um Gamma Type
        "Philips Imaging DD 002|2001|08": "FD",  // Um Gamma Angle
        "Philips Imaging DD 002|2001|09": "FD",  // Um Gamma Shift
        "Philips Imaging DD 002|2001|0A": "FD",  // Um Gamma Center
        "Philips Imaging DD 002|2001|0B": "FD",  // Drr Contrast Equalization
        "Philips Imaging DD 002|2001|0C": "US",  // Drr Contrast Equalization Kernel Size
        "Philips Imaging DD 002|2001|0D": "CS",  // Drr Sharp Lut Type
        "Philips Imaging DD 002|2001|0E": "FD",  // Drr Sharpening
        "Philips Imaging DD 002|2001|0F": "US",  // Drr Sharp Kernel Size
        "Philips Imaging DD 002|2001|10": "SS",  // Drr Window Width
        "Philips Imaging DD 002|2001|11": "SS",  // Drr Window Level
        "Philips Imaging DD 002|2001|12": "CS",  // Drr Lut Type
        "Philips Imaging DD 002|2001|13": "SS",  // Unique Processing Mode
        "Philips Imaging DD 002|2001|14": "FD",  // Unique Contrast Balance
        "Philips Imaging DD 002|2001|15": "FD",  // Unique Center Density
        "Philips Imaging DD 002|2001|16": "FD",  // Unique Bright Density
        "Philips Imaging DD 002|2001|17": "FD",  // Unique Detail Contrast
        "Philips Imaging DD 002|2001|18": "CS",  // Unique Density Curve
        "Philips Imaging DD 002|2001|19": "FD",  // Unique Density Min
        "Philips Imaging DD 002|2001|1A": "FD",  // Unique Density Max
        "Philips Imaging DD 002|2001|1B": "FD",  // Unique Gamma
        "Philips Imaging DD 002|2001|1C": "FD",  // Unique Gamma Min
        "Philips Imaging DD 002|2001|1D": "FD",  // Unique Gamma Max
        "Philips Imaging DD 002|2001|1E": "FD",  // Unique Structure Preference
        "Philips Imaging DD 002|2001|1F": "FD",  // Unique Noise Limit
        "Philips Imaging DD 002|2001|20": "FD",  // Unique Noise Band
        "Philips Imaging DD 002|2001|21": "FD",  // Unique Noise Step
        "Philips Imaging DD 002|2001|22": "FD",  // Unique Noise Compensation
        "Philips Imaging DD 002|2001|23": "FD",  // Unique Structure Boost
        "Philips Imaging DD 002|2001|24": "FD",  // Unique Strong Contrast Limit
        "Philips Imaging DD 002|2001|25": "FD",  // Unique Strong Contrast Factor
        "Philips Imaging DD 002|2001|26": "FD",  // Unique Structure Boost Offset
        "Philips Imaging DD 002|2001|27": "FD",  // Unique Weak Contrast Limit
        "Philips Imaging DD 002|2001|28": "US",  // Unique Smooth Gain
        "Philips Imaging DD 002|2001|29": "US",  // Unique Level
        "Philips Imaging DD 002|2001|2A": "US",  // Unique Gain Up Single
        "Philips Imaging DD 002|2001|2B": "SS",  // Unique Smh Limit One
        "Philips Imaging DD 002|2001|2C": "FD",  // Unique Film Density Min
        "Philips Imaging DD 002|2001|2D": "FD",  // Unique Film Density Max
        "Philips Imaging DD 002|2001|2E": "SS",  // Unique Version
        "Philips Imaging DD 002|2001|2F": "SS",  // Ranger Version
        "Philips Imaging DD 002|2001|30": "SS",  // Ranger Mode
        "Philips Imaging DD 002|2001|31": "SS",  // Ranger Field1
        "Philips Imaging DD 002|2001|32": "SS",  // Ranger Field2
        "Philips Imaging DD 002|2001|33": "SS",  // Ranger Percentile Key1
        "Philips Imaging DD 002|2001|34": "SS",  // Ranger Percentile Key2
        "Philips Imaging DD 002|2001|35": "FD",  // Ranger Dose1
        "Philips Imaging DD 002|2001|36": "FD",  // Ranger Dose2
        "Philips Imaging DD 002|2001|37": "FD",  // Ranger Manual Dose1
        "Philips Imaging DD 002|2001|38": "FD",  // Ranger Manual Dose2
        "Philips Imaging DD 002|2001|39": "CS",  // Unique Rox Shape
        "Philips Imaging DD 002|2001|3A": "SQ",  // Ranger Set Sequence
        "Philips Imaging DD 002|2001|3B": "SQ",  // Rox Sequence
        "Philips Imaging DD 002|2001|3C": "SQ",  // Xray Edge Enhancement Sequence
        "Philips Imaging DD 002|2001|3D": "SQ",  // Edr Lut Sequence
        "Philips Imaging DD 002|2001|3E": "SS",  // Unique Dose Decades
        "Philips Imaging DD 002|2001|3F": "SS",  // Unique Dose Unit
        "Philips Imaging DD 002|2001|40": "SS",  // Unique Density Unit
        "Philips Imaging DD 002|2001|50": "CS",  // Workflow Status
        "Philips Imaging DD 002|2001|52": "LO",  // Workflow Step Id
        "Philips Imaging DD 002|2001|53": "CS",  // Workflow Step Status
        "Philips Imaging DD 002|2001|57": "SQ",  // Workflow Step Input Sequence
        "Philips Imaging DD 002|2001|58": "SQ",  // Workflow Step Output Sequence
        "Philips Imaging DD 002|2001|5A": "LO",  // Workflow Step Type
        "Philips Imaging DD 002|2001|5C": "LO",  // Workflow Id
        "Philips Imaging DD 002|2001|5D": "UL",  // Pixel Data Representation Rows
        "Philips Imaging DD 002|2001|5E": "UL",  // Pixel Data Representation Columns
        "Philips Imaging DD 002|2001|5F": "SQ",  // Private Dicom Extension Sequence
        "Philips Imaging DD 002|2001|63": "ST",  // Isyntax Reference
        "Philips Imaging DD 002|2001|64": "SQ",  // Workflow Step Job Params Sequence
        "Philips Imaging DD 002|2001|65": "CS",  // Preserve Aspect
        "Philips Imaging DD 002|2001|66": "CS",  // Interpolated
        "Philips Imaging DD 002|2001|67": "LO",  // Error Flag
        "Philips Imaging DD 002|2001|68": "LO",  // Error Message Id
        "Philips Imaging DD 002|2001|6B": "LO",  // Suitable For
        "Philips Imaging DD 002|2001|71": "CS",  // Submit Mpps Job
        "Philips Imaging DD 002|2001|72": "FL",  // Displayed Area Bottom Right Hand Corner Fraction
        "Philips Imaging DD 002|2001|73": "FL",  // Displayed Area Top Left Hand Corner Fraction
        "Philips Imaging DD 002|2001|74": "LO",  // Interpolation Mode
        "Philips Imaging DD 002|2001|75": "SS",  // Graphic Annotation Id Reference
        "Philips Imaging DD 097|2001|01": "SQ",  // View Geometry
        "Philips Imaging DD 097|2001|02": "FD",  // Frame Geometry Origin
        "Philips Imaging DD 097|2001|03": "FD",  // Frame Geometry Extent
        "Philips Imaging DD 097|2001|04": "FD",  // Frame Geometry Orientation
        "Philips Imaging DD 097|2001|05": "SQ",  // Visual Sequence
        "Philips Imaging DD 097|2001|06": "SQ",  // Cut Sequence
        "Philips Imaging DD 097|2001|07": "FD",  // Visual Opacity
        "Philips Imaging DD 097|2001|08": "SQ",  // Opacity Map Sequence
        "Philips Imaging DD 097|2001|0A": "SQ",  // Light Sequence
        "Philips Imaging DD 097|2001|0B": "SQ",  // Color Map Sequence
        "Philips Imaging DD 097|2001|0D": "FD",  // Visual Threshold
        "Philips Imaging DD 097|2001|0E": "SQ",  // Scene Sequence
        "Philips Imaging DD 097|2001|0F": "FD",  // Frame Geometry Slab
        "Philips Imaging DD 097|2001|12": "SQ",  // Gradient Map Sequence
        "Philips Imaging DD 097|2001|17": "US",  // Display Rows
        "Philips Imaging DD 097|2001|18": "US",  // Display Columns
        "Philips Imaging DD 097|2001|19": "LO",  // Frame Geometry Type
        "Philips Imaging DD 097|2001|1A": "FD",  // Light Intensity
        "Philips Imaging DD 097|2001|1B": "UL",  // Light Color
        "Philips Imaging DD 097|2001|1C": "FD",  // Light Origin
        "Philips Imaging DD 097|2001|1D": "FD",  // Light Direction
        "Philips Imaging DD 097|2001|1E": "FD",  // Color Map Samples
        "Philips Imaging DD 097|2001|1F": "FD",  // Opacity Map Samples
        "Philips Imaging DD 097|2001|21": "UL",  // Visual Color
        "Philips Imaging DD 097|2001|22": "FD",  // Illumination Ambient
        "Philips Imaging DD 097|2001|23": "FD",  // Illumination Diffuse
        "Philips Imaging DD 097|2001|24": "FD",  // Illumination Specular
        "Philips Imaging DD 097|2001|25": "FD",  // Illumination Specular Power
        "Philips Imaging DD 097|2001|26": "FD",  // Depth Cue Begin
        "Philips Imaging DD 097|2001|27": "FD",  // Depth Cue Lambda
        "Philips Imaging DD 097|2001|28": "LO",  // Depth Cue Function
        "Philips Imaging DD 097|2001|2A": "LO",  // Cut Set Type
        "Philips Imaging DD 097|2001|2B": "FD",  // Cut Plane Origin
        "Philips Imaging DD 097|2001|2C": "FD",  // Cut Plane Normal
        "Philips Imaging DD 097|2001|2D": "UL",  // Volume Definition Number
        "Philips Imaging DD 097|2001|2E": "SQ",  // Volume Mask Sequence
        "Philips Imaging DD 097|2001|2F": "OB",  // Volume Mask Data
        "Philips Imaging DD 097|2001|30": "SL",  // Volume Mask Offset
        "Philips Imaging DD 097|2001|31": "SL",  // Volume Mask Size
        "Philips Imaging DD 097|2001|32": "SL",  // Volume Mask Alignment
        "Philips Imaging DD 097|2001|36": "LO",  // Light Anchor
        "Philips Imaging DD 097|2001|37": "FD",  // Cone Geometry Origin
        "Philips Imaging DD 097|2001|38": "FD",  // Cone Geometry Orientation
        "Philips Imaging DD 097|2001|39": "FD",  // Cone Geometry View Distance
        "Philips Imaging DD 097|2001|3A": "FD",  // Cone Geometry Slab Extent
        "Philips Imaging DD 097|2001|3B": "FD",  // Cone Geometry Field Of View
        "Philips Imaging DD 097|2001|3C": "SQ",  // Intensity Map Sequence
        "Philips Imaging DD 097|2001|3D": "FD",  // Intensity Map Samples
        "Philips Imaging DD 097|2001|3E": "SQ",  // Mesh Sequence
        "Philips Imaging DD 097|2001|40": "UL",  // Mesh Color
        "Philips Imaging DD 097|2001|41": "LO",  // Mesh Draw Style
        "Philips Imaging DD 097|2001|42": "SQ",  // Mesh Section Sequence
        "Philips Imaging DD 097|2001|44": "LO",  // Mesh Section Vertex Connectivity
        "Philips Imaging DD 097|2001|45": "SL",  // Mesh Section Vertex Size
        "Philips Imaging DD 097|2001|46": "LO",  // Mesh Section Vertex Format
        "Philips Imaging DD 097|2001|47": "OB",  // Mesh Section Vertex Data
        "Philips Imaging DD 097|2001|49": "SQ",  // Referenced Volume Definition Sequence
        "Philips Imaging DD 097|2001|4A": "OB",  // Mesh Section Index Data
        "Philips Imaging DD 097|2001|4B": "SL",  // Mesh Section Index Size
        "Philips Imaging DD 097|2001|4C": "LO",  // Shutter Interaction Type
        "Philips Imaging DD 097|2001|A1": "CS",  // Volume Type
        "Philips Imaging DD 097|2001|A2": "FD",  // Volume Origin
        "Philips Imaging DD 097|2001|A3": "FD",  // Volume Axis
        "Philips Imaging DD 097|2001|A4": "FD",  // Volume Pixel Spacing
        "Philips Imaging DD 097|2001|A5": "FD",  // Volume Slice Spacing
        "Philips Imaging DD 097|2001|A6": "US",  // Volume Slices
        "Philips Imaging DD 097|2001|A8": "IS",  // Referenced Volume Definition Number
        "Philips Imaging DD 097|2001|A9": "SQ",  // Linear Modality Gl Trafo Sequence
        "Philips Imaging DD 097|2001|AA": "FD",  // Volume Slice Offsets
        "Philips Imaging DD 097|2001|AB": "IS",  // Number Of Volume Definitions
        "Philips Imaging DD 129|2001|00": "SQ",  // Presentation State Sequence
        "Philips Imaging DD 129|2001|01": "SQ",  // Embedded Original Presentation State Sequence
        "Philips Imaging DD 129|2001|02": "SQ",  // Planar Intersection Sequence
        "Philips Imaging DD 129|2001|03": "UL",  // Plane Separator Line Color
        "Philips Imaging DD 129|2001|04": "SQ",  // Plane Sequence
        "Philips Imaging DD 129|2001|05": "FD",  // Plane Equation
        "Philips Imaging DD 129|2001|06": "FD",  // Plane Opacity
        "Philips Imaging DD 129|2001|07": "CS",  // Plane Enabled
        "Philips Imaging DD 129|2001|08": "CS",  // Plane Selected
        "Philips Imaging DD 129|2001|09": "UL",  // Plane Highlight Color
        "Philips MR Imaging DD 001|2005|0D": "FL",  // Scale Intercept
        "Philips MR Imaging DD 001|2005|0E": "FL",  // Scale Slope
        "Philips PET Private Group|7053|00": "DS",  // SUV Factor - Multiplying Stored Pixel Values by Rescale Slope then this factor r
        "Philips PET Private Group|7053|09": "DS",  // Activity Concentration Factor - Multiplying Stored Pixel Values by Rescale Slope
        "Philips ST80i|0025|01": "OW",  // ST80i Stress Study file data
        "SIEMENS MR HEADER|0019|0C": "IS",  // B Value
        "SIEMENS MR HEADER|0019|0D": "CS",  // Diffusion Directionality
        "SIEMENS MR HEADER|0019|0E": "FD",  // Diffusion Gradient Direction
        "SIEMENS MR HEADER|0019|27": "FD",  // B Matrix
        "SIEMENS SYNGO ULTRA-SOUND TOYON DATA STREAMING|7FD1|01": "OB",  // Padding
        "SIEMENS SYNGO ULTRA-SOUND TOYON DATA STREAMING|7FD1|09": "UI",  // Version ID
        "SIEMENS SYNGO ULTRA-SOUND TOYON DATA STREAMING|7FD1|10": "OB",  // Volume Payload
        "SIEMENS SYNGO ULTRA-SOUND TOYON DATA STREAMING|7FD1|11": "OB",  // After Payload
        "SIEMENS Ultrasound SC2000|0119|00": "LO",  // Acoustic Meta Information Version
        "SIEMENS Ultrasound SC2000|0119|01": "OB",  // Common Acoustic Meta Information
        "SIEMENS Ultrasound SC2000|0119|02": "SQ",  // Multi Stream Sequence
        "SIEMENS Ultrasound SC2000|0119|03": "SQ",  // Acoustic Data Sequence
        "SIEMENS Ultrasound SC2000|0119|04": "OB",  // Per Transaction Acoustic Control Information
        "SIEMENS Ultrasound SC2000|0119|05": "UL",  // Acoustic Data Offset
        "SIEMENS Ultrasound SC2000|0119|06": "UL",  // Acoustic Data Length
        "SIEMENS Ultrasound SC2000|0119|07": "UL",  // Footer Offset
        "SIEMENS Ultrasound SC2000|0119|08": "UL",  // Footer Length
        "SIEMENS Ultrasound SC2000|0119|09": "SS",  // Acoustic Stream Number
        "SIEMENS Ultrasound SC2000|0119|10": "SH",  // Acoustic Stream Type
        "SIEMENS Ultrasound SC2000|0119|11": "",  // Stage Timer Time
        "SIEMENS Ultrasound SC2000|0119|12": "",  // Stop Watch Time
        "SIEMENS Ultrasound SC2000|0119|13": "IS",  // Volume Rate
        "SIEMENS Ultrasound SC2000|0119|21": "SH",  // 
        "SIEMENS Ultrasound SC2000|0129|00": "SQ",  // MPR View Sequence
        "SIEMENS Ultrasound SC2000|0129|02": "UI",  // Bookmark UID
        "SIEMENS Ultrasound SC2000|0129|03": "",  // Plane Origin Vector
        "SIEMENS Ultrasound SC2000|0129|04": "",  // Row Vector
        "SIEMENS Ultrasound SC2000|0129|05": "",  // Column Vector
        "SIEMENS Ultrasound SC2000|0129|06": "SQ",  // Visualization Sequence
        "SIEMENS Ultrasound SC2000|0129|07": "UI",  // Bookmark UID
        "SIEMENS Ultrasound SC2000|0129|08": "OB",  // Visualization Information
        "SIEMENS Ultrasound SC2000|0129|09": "SQ",  // Application State Sequence
        "SIEMENS Ultrasound SC2000|0129|10": "OB",  // Application State Information
        "SIEMENS Ultrasound SC2000|0129|11": "SQ",  // Referenced Bookmark Sequence
        "SIEMENS Ultrasound SC2000|0129|12": "UI",  // Referenced Bookmark UID
        "SIEMENS Ultrasound SC2000|0129|20": "SQ",  // Cine Parameters Sequence
        "SIEMENS Ultrasound SC2000|0129|21": "OB",  // Cine Parameters Schema
        "SIEMENS Ultrasound SC2000|0129|22": "OB",  // Values of Cine Parameters
        "SIEMENS Ultrasound SC2000|0129|29": "OB",  // 
        "SIEMENS Ultrasound SC2000|0129|30": "CS",  // Raw Data Object Type
        "SIEMENS Ultrasound SC2000|0139|01": "SL",  // Physio Capture ROI
        "SIEMENS Ultrasound SC2000|0149|01": "FD",  // Vector of BROI Points
        "SIEMENS Ultrasound SC2000|0149|02": "FD",  // Start/End Timestamps of Strip Stream
        "SIEMENS Ultrasound SC2000|0149|03": "FD",  // Timestamps of Visible R-waves
        "SIEMENS Ultrasound SC2000|7FD1|01": "OB",  // Acoustic Image and Footer Data
        "SIEMENS Ultrasound SC2000|7FD1|09": "UI",  // Volume Version ID
        "SIEMENS Ultrasound SC2000|7FD1|10": "OB",  // Volume Payload
        "SIEMENS Ultrasound SC2000|7FD1|11": "OB",  // After Payload
    ]
}
