/// DICOM Storage SOP Classes
///
/// GENERATED by Scripts/generate_storage_sop_classes.py from DICOM PS3.4 2026a - Service Class Specifications and DICOM PS3.6 2026a - Data Dictionary.
/// Do not edit by hand; change the generator (its PRIORITY list sets the order) and re-run it.
///
/// NEMA-verified: 2026a, checked 2026-09-28 — `allUIDs` is exactly the 170 rows of
/// PS3.4 2026a Table B.5-1 (Standard SOP Classes of the Storage Service Class) and
/// `retiredUIDs` the 4 rows of Table B.6-1; every UID and name checked against
/// PS3.6 2026a Table A-1.

import Foundation

/// Canonical registry of DICOM Storage SOP Class UIDs.
///
/// This is the **single source of truth** for "which SOP Classes are storage
/// objects" across the DICOMKit package. Every component that negotiates
/// storage presentation contexts MUST derive its list from here rather than
/// maintaining its own copy, so the SCU, the SCP and the validator can never
/// drift apart:
///
/// - `DICOMRetrieveService` (C-GET SCU) proposes one storage presentation
///   context per UID so the SCP has somewhere to send each instance.
/// - `StorageSCP` (C-STORE / C-MOVE destination) accepts these abstract
///   syntaxes during association negotiation.
/// - `DICOMValidator` recognises these as known storage objects.
///
/// ## Why this matters
///
/// C-GET and C-MOVE deliver images as C-STORE sub-operations whose abstract
/// syntax must be negotiated up front. If a study's SOP Class is missing from
/// the proposed/accepted set, the peer has no presentation context to send it
/// on and silently transfers **zero** instances (e.g. an X-Ray Angiographic
/// study returning "0 files" while reporting success). Keeping this list
/// complete and shared prevents that class of bug.
///
/// ## Order
///
/// An association allows 127 storage presentation contexts after the C-GET
/// context (odd IDs 1...255, PS3.8 9.3.2.2), fewer than the classes in
/// `allUIDs`, so the C-GET SCU proposes the list in order until it runs out of
/// IDs. Common imaging classes come first; the rest follow in PS3.4 Table
/// B.5-1 order. Membership, not order, is what matters for the SCP and the
/// validator.
///
/// Reference: DICOM PS3.4 Annex B (Storage Service Class), Table B.5-1 and
/// B.6-1; PS3.6 Table A-1 for the names.
public enum StorageSOPClass {
    /// All current Storage SOP Class UIDs (PS3.4 Table B.5-1), in negotiation order.
    public static let allUIDs: [String] = [
        // MARK: Projection X-Ray
        "1.2.840.10008.5.1.4.1.1.1", // Computed Radiography Image Storage
        "1.2.840.10008.5.1.4.1.1.1.1", // Digital X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.1.1", // Digital X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.1.2", // Digital Mammography X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.2.1", // Digital Mammography X-Ray Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.1.3", // Digital Intra-Oral X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.1.3.1", // Digital Intra-Oral X-Ray Image Storage - For Processing
        // MARK: X-Ray Angiography & Radiofluoroscopy
        "1.2.840.10008.5.1.4.1.1.12.1", // X-Ray Angiographic Image Storage
        "1.2.840.10008.5.1.4.1.1.12.1.1", // Enhanced XA Image Storage
        "1.2.840.10008.5.1.4.1.1.12.2", // X-Ray Radiofluoroscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.12.2.1", // Enhanced XRF Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.1", // X-Ray 3D Angiographic Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.2", // X-Ray 3D Craniofacial Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.3", // Breast Tomosynthesis Image Storage
        "1.2.840.10008.5.1.4.1.1.13.1.4", // Breast Projection X-Ray Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.13.1.5", // Breast Projection X-Ray Image Storage - For Processing
        // MARK: CT
        "1.2.840.10008.5.1.4.1.1.2", // CT Image Storage
        "1.2.840.10008.5.1.4.1.1.2.1", // Enhanced CT Image Storage
        "1.2.840.10008.5.1.4.1.1.2.2", // Legacy Converted Enhanced CT Image Storage
        // MARK: MR
        "1.2.840.10008.5.1.4.1.1.4", // MR Image Storage
        "1.2.840.10008.5.1.4.1.1.4.1", // Enhanced MR Image Storage
        "1.2.840.10008.5.1.4.1.1.4.2", // MR Spectroscopy Storage
        "1.2.840.10008.5.1.4.1.1.4.3", // Enhanced MR Color Image Storage
        "1.2.840.10008.5.1.4.1.1.4.4", // Legacy Converted Enhanced MR Image Storage
        // MARK: Ultrasound
        "1.2.840.10008.5.1.4.1.1.6.1", // Ultrasound Image Storage
        "1.2.840.10008.5.1.4.1.1.6.2", // Enhanced US Volume Storage
        "1.2.840.10008.5.1.4.1.1.3.1", // Ultrasound Multi-frame Image Storage
        // MARK: Nuclear Medicine / PET
        "1.2.840.10008.5.1.4.1.1.20", // Nuclear Medicine Image Storage
        "1.2.840.10008.5.1.4.1.1.128", // Positron Emission Tomography Image Storage
        "1.2.840.10008.5.1.4.1.1.128.1", // Legacy Converted Enhanced PET Image Storage
        "1.2.840.10008.5.1.4.1.1.130", // Enhanced PET Image Storage
        // MARK: Secondary Capture
        "1.2.840.10008.5.1.4.1.1.7", // Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.1", // Multi-frame Single Bit Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.2", // Multi-frame Grayscale Byte Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.3", // Multi-frame Grayscale Word Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.4", // Multi-frame True Color Secondary Capture Image Storage
        // MARK: Visible Light / Microscopy / Ophthalmic
        "1.2.840.10008.5.1.4.1.1.77.1.1", // VL Endoscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.1.1", // Video Endoscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.2", // VL Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.2.1", // Video Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.3", // VL Slide-Coordinates Microscopic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.4", // VL Photographic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.4.1", // Video Photographic Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.1", // Ophthalmic Photography 8 Bit Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.2", // Ophthalmic Photography 16 Bit Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.4", // Ophthalmic Tomography Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.6", // VL Whole Slide Microscopy Image Storage
        // MARK: Radiotherapy
        "1.2.840.10008.5.1.4.1.1.481.1", // RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.2", // RT Dose Storage
        "1.2.840.10008.5.1.4.1.1.481.3", // RT Structure Set Storage
        "1.2.840.10008.5.1.4.1.1.481.4", // RT Beams Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.5", // RT Plan Storage
        // MARK: Presentation States
        "1.2.840.10008.5.1.4.1.1.11.1", // Grayscale Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.2", // Color Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.3", // Pseudo-Color Softcopy Presentation State Storage
        // MARK: Structured Reporting & Documents
        "1.2.840.10008.5.1.4.1.1.88.11", // Basic Text SR Storage
        "1.2.840.10008.5.1.4.1.1.88.22", // Enhanced SR Storage
        "1.2.840.10008.5.1.4.1.1.88.33", // Comprehensive SR Storage
        "1.2.840.10008.5.1.4.1.1.88.34", // Comprehensive 3D SR Storage
        "1.2.840.10008.5.1.4.1.1.88.59", // Key Object Selection Document Storage
        "1.2.840.10008.5.1.4.1.1.104.1", // Encapsulated PDF Storage
        "1.2.840.10008.5.1.4.1.1.104.2", // Encapsulated CDA Storage
        // MARK: Raw / Spatial / Segmentation
        "1.2.840.10008.5.1.4.1.1.66", // Raw Data Storage
        "1.2.840.10008.5.1.4.1.1.66.1", // Spatial Registration Storage
        "1.2.840.10008.5.1.4.1.1.66.2", // Spatial Fiducials Storage
        "1.2.840.10008.5.1.4.1.1.66.3", // Deformable Spatial Registration Storage
        "1.2.840.10008.5.1.4.1.1.66.4", // Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.66.5", // Surface Segmentation Storage
        // MARK: Waveform
        "1.2.840.10008.5.1.4.1.1.9.1.1", // 12-lead ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.1.2", // General ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.1.3", // Ambulatory ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.2.1", // Hemodynamic Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.3.1", // Cardiac Electrophysiology Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.4.1", // Basic Voice Audio Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.4.2", // General Audio Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.5.1", // Arterial Pulse Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.6.1", // Respiratory Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.6.2", // Multi-channel Respiratory Waveform Storage
        // MARK: Remaining PS3.4 Table B.5-1 classes, in table order
        "1.2.840.10008.5.1.4.1.1.6.3", // Photoacoustic Image Storage
        "1.2.840.10008.5.1.4.1.1.9.1.4", // General 32-bit ECG Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.1", // Routine Scalp Electroencephalogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.2", // Electromyogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.3", // Electrooculogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.7.4", // Sleep Electroencephalogram Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.8.1", // Body Position Waveform Storage
        "1.2.840.10008.5.1.4.1.1.9.100.1", // Waveform Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.9.100.2", // Waveform Acquisition Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.4", // Blending Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.5", // XA/XRF Grayscale Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.6", // Grayscale Planar MPR Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.7", // Compositing Planar MPR Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.8", // Advanced Blending Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.9", // Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.10", // Segmented Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.11", // Multiple Volume Rendering Volumetric Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.11.12", // Variable Modality LUT Softcopy Presentation State Storage
        "1.2.840.10008.5.1.4.1.1.14.1", // Intravascular Optical Coherence Tomography Image Storage - For Presentation
        "1.2.840.10008.5.1.4.1.1.14.2", // Intravascular Optical Coherence Tomography Image Storage - For Processing
        "1.2.840.10008.5.1.4.1.1.30", // Parametric Map Storage
        "1.2.840.10008.5.1.4.1.1.66.6", // Tractography Results Storage
        "1.2.840.10008.5.1.4.1.1.66.7", // Label Map Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.66.8", // Height Map Segmentation Storage
        "1.2.840.10008.5.1.4.1.1.67", // Real World Value Mapping Storage
        "1.2.840.10008.5.1.4.1.1.68.1", // Surface Scan Mesh Storage
        "1.2.840.10008.5.1.4.1.1.68.2", // Surface Scan Point Cloud Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.3", // Stereometric Relationship Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.5", // Wide Field Ophthalmic Photography Stereographic Projection Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.6", // Wide Field Ophthalmic Photography 3D Coordinates Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.7", // Ophthalmic Optical Coherence Tomography En Face Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.5.8", // Ophthalmic Optical Coherence Tomography B-scan Volume Analysis Storage
        "1.2.840.10008.5.1.4.1.1.77.1.7", // Dermoscopic Photography Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.8", // Confocal Microscopy Image Storage
        "1.2.840.10008.5.1.4.1.1.77.1.9", // Confocal Microscopy Tiled Pyramidal Image Storage
        "1.2.840.10008.5.1.4.1.1.78.1", // Lensometry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.2", // Autorefraction Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.3", // Keratometry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.4", // Subjective Refraction Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.5", // Visual Acuity Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.6", // Spectacle Prescription Report Storage
        "1.2.840.10008.5.1.4.1.1.78.7", // Ophthalmic Axial Measurements Storage
        "1.2.840.10008.5.1.4.1.1.78.8", // Intraocular Lens Calculations Storage
        "1.2.840.10008.5.1.4.1.1.79.1", // Macular Grid Thickness and Volume Report Storage
        "1.2.840.10008.5.1.4.1.1.80.1", // Ophthalmic Visual Field Static Perimetry Measurements Storage
        "1.2.840.10008.5.1.4.1.1.81.1", // Ophthalmic Thickness Map Storage
        "1.2.840.10008.5.1.4.1.1.82.1", // Corneal Topography Map Storage
        "1.2.840.10008.5.1.4.1.1.88.35", // Extensible SR Storage
        "1.2.840.10008.5.1.4.1.1.88.40", // Procedure Log Storage
        "1.2.840.10008.5.1.4.1.1.88.50", // Mammography CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.65", // Chest CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.67", // X-Ray Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.68", // Radiopharmaceutical Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.69", // Colon CAD SR Storage
        "1.2.840.10008.5.1.4.1.1.88.70", // Implantation Plan SR Storage
        "1.2.840.10008.5.1.4.1.1.88.71", // Acquisition Context SR Storage
        "1.2.840.10008.5.1.4.1.1.88.72", // Simplified Adult Echo SR Storage
        "1.2.840.10008.5.1.4.1.1.88.73", // Patient Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.74", // Planned Imaging Agent Administration SR Storage
        "1.2.840.10008.5.1.4.1.1.88.75", // Performed Imaging Agent Administration SR Storage
        "1.2.840.10008.5.1.4.1.1.88.76", // Enhanced X-Ray Radiation Dose SR Storage
        "1.2.840.10008.5.1.4.1.1.88.77", // Waveform Annotation SR Storage
        "1.2.840.10008.5.1.4.1.1.90.1", // Content Assessment Results Storage
        "1.2.840.10008.5.1.4.1.1.91.1", // Microscopy Bulk Simple Annotations Storage
        "1.2.840.10008.5.1.4.1.1.104.3", // Encapsulated STL Storage
        "1.2.840.10008.5.1.4.1.1.104.4", // Encapsulated OBJ Storage
        "1.2.840.10008.5.1.4.1.1.104.5", // Encapsulated MTL Storage
        "1.2.840.10008.5.1.4.1.1.131", // Basic Structured Display Storage
        "1.2.840.10008.5.1.4.1.1.200.2", // CT Performed Procedure Protocol Storage
        "1.2.840.10008.5.1.4.1.1.200.8", // XA Performed Procedure Protocol Storage
        "1.2.840.10008.5.1.4.1.1.481.6", // RT Brachy Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.7", // RT Treatment Summary Record Storage
        "1.2.840.10008.5.1.4.1.1.481.8", // RT Ion Plan Storage
        "1.2.840.10008.5.1.4.1.1.481.9", // RT Ion Beams Treatment Record Storage
        "1.2.840.10008.5.1.4.1.1.481.10", // RT Physician Intent Storage
        "1.2.840.10008.5.1.4.1.1.481.11", // RT Segment Annotation Storage
        "1.2.840.10008.5.1.4.1.1.481.12", // RT Radiation Set Storage
        "1.2.840.10008.5.1.4.1.1.481.13", // C-Arm Photon-Electron Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.14", // Tomotherapeutic Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.15", // Robotic-Arm Radiation Storage
        "1.2.840.10008.5.1.4.1.1.481.16", // RT Radiation Record Set Storage
        "1.2.840.10008.5.1.4.1.1.481.17", // RT Radiation Salvage Record Storage
        "1.2.840.10008.5.1.4.1.1.481.18", // Tomotherapeutic Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.19", // C-Arm Photon-Electron Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.20", // Robotic Radiation Record Storage
        "1.2.840.10008.5.1.4.1.1.481.21", // RT Radiation Set Delivery Instruction Storage
        "1.2.840.10008.5.1.4.1.1.481.22", // RT Treatment Preparation Storage
        "1.2.840.10008.5.1.4.1.1.481.23", // Enhanced RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.24", // Enhanced Continuous RT Image Storage
        "1.2.840.10008.5.1.4.1.1.481.25", // RT Patient Position Acquisition Instruction Storage
        "1.2.840.10008.5.1.4.34.7", // RT Beams Delivery Instruction Storage
        "1.2.840.10008.5.1.4.34.10", // RT Brachy Application Setup Delivery Instruction Storage
    ]

    /// Retired Storage SOP Class UIDs (PS3.4 Table B.6-1). Not proposed by the
    /// SCU, but still recognised by `isStorage(_:)` because archives hold them.
    public static let retiredUIDs: [String] = [
        "1.2.840.10008.5.1.4.1.1.5", // Nuclear Medicine Image Storage (Retired)
        "1.2.840.10008.5.1.4.1.1.6", // Ultrasound Image Storage (Retired)
        "1.2.840.10008.5.1.4.1.1.3", // Ultrasound Multi-frame Image Storage (Retired)
        "1.2.840.10008.5.1.4.1.1.12.3", // X-Ray Angiographic Bi-Plane Image Storage (Retired)
    ]

    /// All current Storage SOP Class UIDs as a set, for fast membership checks.
    public static let allUIDSet: Set<String> = Set(allUIDs)

    /// Retired Storage SOP Class UIDs as a set.
    public static let retiredUIDSet: Set<String> = Set(retiredUIDs)

    /// Returns `true` if the given UID is a current or retired Storage SOP Class.
    public static func isStorage(_ uid: String) -> Bool {
        allUIDSet.contains(uid) || retiredUIDSet.contains(uid)
    }
}
