#!/usr/bin/env python3
"""
Generate the UID registry of DICOMDictionary from PS3.6 Table A-1 (UID Values).

Usage:
    python3 Scripts/generate_uid_dictionary.py part06_2026a.xml [--date YYYY-MM-DD]

Writes Sources/DICOMDictionary/UIDDictionaryEntries.swift: one `UIDEntry` per A-1 row,
name and keyword verbatim, `retired` when the name ends in "(Retired)", and the A-1
"UID Type" column mapped onto `UIDType`. The lookup API stays hand-written in
UIDDictionary.swift, which also holds the two Fragmentable HEVC UIDs that DICOMCore
supports but no PS3.6 edition registers (DICOMCore report, P2 / D20).
"""
import argparse
import datetime
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nema_docbook import Part  # noqa: E402

OUT = "Sources/DICOMDictionary/UIDDictionaryEntries.swift"

# A-1 "UID Type" column -> UIDType case (DictionaryEntry.swift)
TYPES = {
    "Transfer Syntax": "transferSyntax",
    "SOP Class": "sopClass",
    "Meta SOP Class": "metaSOPClass",
    "Well-known SOP Instance": "wellKnown",
    "LDAP OID": "ldap",
    "Coding Scheme": "codingScheme",
    "DICOM UIDs as a Coding Scheme": "codingScheme",
    "Application Context Name": "applicationContext",
    "Service Class": "serviceClass",
    "Application Hosting Model": "applicationHostingModel",
    "Mapping Resource": "mappingResource",
    "Synchronization Frame of Reference": "synchronizationFrameOfReference",
}


def lit(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("part06")
    ap.add_argument("--date", default=datetime.date.today().isoformat())
    a = ap.parse_args()
    p6 = Part(a.part06)
    if "PS3.6" not in p6.subtitle:
        sys.exit(f"expected PS3.6, got {p6.subtitle!r}")
    edition = re.search(r"\b(\d{4}[a-e])\b", p6.subtitle).group(1)

    entries, by_type = [], {}
    for r in p6.rows(p6.table("A-1")):
        if len(r) < 4:
            continue
        uid, name, kw, typ = r[0].strip(), r[1].strip(), r[2].strip(), r[3].strip()
        if typ not in TYPES:
            sys.exit(f"unmapped UID Type {typ!r} for {uid}; add it to TYPES and UIDType")
        retired = name.endswith("(Retired)")
        entries.append((uid, name, kw, TYPES[typ], retired))
        by_type[typ] = by_type.get(typ, 0) + 1

    out = [
        "/// DICOM UID Registry entries",
        "///",
        f"/// GENERATED by Scripts/generate_uid_dictionary.py from {p6.subtitle}, Table A-1 (UID Values).",
        "/// Do not edit by hand; change the generator and re-run it.",
        "///",
        f"/// NEMA-verified: {edition}, checked {a.date} — all {len(entries)} rows of PS3.6 {edition} Table A-1",
        "/// (UID Value, UID Name, UID Keyword, UID Type) copied verbatim; `retired` is set when the name",
        "/// ends in \"(Retired)\"; the UID Type column maps onto `UIDType` as: "
        + ", ".join(f"{k} → .{v}" for k, v in TYPES.items()) + ".",
        "///",
        "/// Rows by type: " + ", ".join(f"{k} {n}" for k, n in by_type.items()) + ".",
        "",
        "extension UIDDictionary {",
        "    /// Every UID of PS3.6 Table A-1, in table order.",
        "    static let registryEntries: [UIDEntry] = [",
    ]
    for uid, name, kw, typ, retired in entries:
        ret = ", retired: true" if retired else ""
        out.append(f"        UIDEntry(uid: {lit(uid)}, name: {lit(name)}, keyword: {lit(kw)}, type: .{typ}{ret}),")
    out += ["    ]", "}", ""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"Wrote {OUT}: {len(entries)} entries; {by_type}")


if __name__ == "__main__":
    main()
